app:

endpoint:
  ip:
  port:

service:
  enabled: true
  port: 80
  targetPort: ingress
  protocol: TCP

loadBalancer:
  ip:
  port:
  targetPort: ingress
  protocol: TCP

ingress:
  enabled: true
  routes: []
