kind: Deployment
apiVersion: apps/v1
metadata:
  name: lsyncd
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: lsyncd
          image: alpine:3.21.2
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache rsync sshpass openssh-client lsyncd;
              mkdir -p /root/.ssh;
              ssh-keyscan -H 192.168.1.198 >> /root/.ssh/known_hosts;
              lsyncd /config.lua;
          env:
            - name: TZ
              value: America/New_York
            - name: RSYNC_RSH
              value: sshpass -e ssh
            - name: SSHPASS
              valueFrom:
                secretKeyRef:
                  name: remote-synology
                  key: password
          volumeMounts:
            - name: libraries
              mountPath: /libraries/movies/assets
              subPath: movies/assets
            - name: libraries
              mountPath: /libraries/movies/requested/Mom
              subPath: movies/requested/Mom
            - name: libraries
              mountPath: /libraries/movies/sd
              subPath: movies/sd
            - name: libraries
              mountPath: /libraries/tv/assets
              subPath: tv/assets
            - name: libraries
              mountPath: /libraries/tv/requested/Mom
              subPath: tv/requested/Mom
            - name: libraries
              mountPath: /libraries/tv/sd
              subPath: tv/sd
            - name: config
              mountPath: /config.lua
              subPath: config.lua
      volumes:
        - name: libraries
          persistentVolumeClaim:
            claimName: libraries
        - name: config
          configMap:
            name: lsyncd
