apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volume-recovery
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments/scale
      - statefulsets/scale
    verbs:
      - get
      - patch
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
