apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volume-recovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volume-recovery
subjects:
  - kind: ServiceAccount
    name: volume-recovery
    namespace: kube-system
