---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ceph-csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgA+KkEQZv+hZlfwWWpdB8qVV/E5+ivsnXNS8pG4WN0DrmZd33J/a3J4aR7d3K99KdeMDx9u+lb0GxSGiCd+iv5IJSM/a6+bx2BZ02BGGY2/kACbc+NNCPT/tCDu5H+y/jiwFHNduJYXwof+oY/hBGFvJjP113eVBHCM9o4GV5zTmOb2zTbHWJUaVsY40biPBSM7/XHHoCT3DQ9pPD3bb5SK5Iyp+g4RpARpTxdWzricBiUNT51uqyD3rnUQ/iLVwwxbb7R9cmdBNcaS8j92QRng7WC+ravPMGsVwJa/oxtb54RF0Eh74P/6+Q2Zsdix31VECxBMCR3eqwacK7/rveaChwPsRPNYj4/xAUMW4ypafDTbsa7JuCx5AnenIFvtOgbEmQ9g588yPWBnoAh2Z6QYE5zg11jOIOsGBDrrOMdAXGKL8tjbXzHoROyeVIA1Z0OI55wGUn3deO4AGwo8ifm6EwB16OC3Iuftp2ZRjDFmw2522uroldVzai58emH9G3mcod0LZoPjnKVSbDg0H2Km5TBwLPhof2dwtpVMEcq4R5U+H6SMmJbCKUakBUqqu5O9GrVajUs1SPN1qGhW2juXd/AU2FrvIVhKckNp1VoZk9fKp93xWZS+TAIJ2kq+9Dx20PDIA4wE7yG37lb21WJGvLIGBZRayM6XXQDFAQUaNrZZIEV0bysedill7MD7APyU6Z4=
    userKey: AgBJYNeegaN3qiZMaaveLSHl9R42dWxflvh9k+Xo1OMxWZE7wlby5pY6Un0O8tMGQgzIeO4yyYiUygXtynCCg8r6Hfne9esc+pLLtDW2sidpa5nkGSPmGOLBjWEVowq/0OvkTfZRMHwUlSTGlpqqIhf0+pdHapH2wjpieM3EJv8TImfiTnQUoL31UnDnkWEqYKcAcnq3qRglLwYbF53+fKpHJY2TDGoOrfu2Kp/z+17DTAtRDbxT3FtgOGlVZzTy5kdTqlGFJDWcwNQvDhvvuOxSz7KIwo1BDvSn8cDBpjWeI8Vmru9lrrsJB64XvM1Pt+kZIENKpeMx8kB5Gjb2S+YHQ7R0qWkaF0quzY/izFEjOIBSJ++2YnjBocHo42VTb8cTP9A52WAwo8TgWYKYCOSiVVqhfGAOuZfMuxU4AMj6VQRHBtIVpeXK6sIRj4o+mgIX4Rd8aZdFPbyeaTlPPkMkrAf7krbomb51jWFw4pqpxXirLssg0L3qviebobVtHodO1rUS4wFikw6wBjW/lFtt0z6BUeBpN1wJGAXyMTB6V6Xhew9m9a8RtyAXT5KmmElKVrRD/CUW/9PWIVzum3byYq1rI6jaQ5VpsBkjyVqPYpeyXRfbOM6t47c0QcsjA2VLtZ+biiSIdMIFmu5Ibb+peFku4r0IecQntERM+0PZclDlLajx74EAIamOXRmwQ5Eqn4+Bfgz5K8bpOiNQiT5MUrvI/RkgyX5SbML+WagqYy2nbs1gDJVl
  template:
    metadata:
      name: ceph-csi-rbd-secret
      namespace: ceph-csi-rbd
