---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ceph-csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgBVnEkKjt7TwdifTrvUNRYPc9U222GB4aI6kwAGOzMKdZ/3PTbXERkEHMQ3gpGS3ldyxMcBgdBY1rFQcQT4bu60OMPS9IcmVxMSQiegNyQDOoO7e4U1hk6WbhlGA8spqu2DdLcctu8e2JobEG4N+BtxuQlgdqMQzfCFw0gXYqqYqIDtya3dcp4/m++BFCFabYqmF0vNZFGKunixXX6r2l7w0kyeaj5p71u2zZxv9Kg3D32NY34bj4TonoclO4Gt7dwhJ3PzOFSWbDlgV8sGxsM3A4kFuhYqSVyvaT5ZGQI3dv7AD9awj3VUjIIfrGO5uSDS+XLO8mlGBrzbRuB4YTC/9IyijRZDkTMXT80zi3tyrJTCCZwykjnF+LqW7Gq8xZuPFtH72Mos5qx12LhISAZLghgU0tfeOLfK1oZQ1ol8TD6Z7F/ZIpP3QHgk/d6/hOpLd277347/ZPTi8apMsAZiymdQACPy2wqvYjKMcZ1wVqDHG8iKBxiFin6OmSzqEMQE0lOYc5SdZtmKLpXZEYg5+3i6phxlPTsuio4gs+RQUoaDqH+Fm+/ekFzKLMYj63jaA2HZqG6tIYv899XKjVpbZ9yMk9GJXLKZuUPsj4kmIDH6pJggaBKHfJx36Wcg/FPGv/TsjYtH0R7hyYPkHjDENRboaQuMyTaOKWcF4InBfsAtOgAYF61vUEe//vtG59knKa0=
    userKey: AgCMVsvgLreI0GzSrDulXn+AvXVcwaakVgImDfwGUUyLwdBMFTIqb/sbyzs+PJCy4JSw3iNE3j2wOWtTSomMuWNuVPfSJPyxYpqP5rgi/JHD9zZ3pDWNmf4XHuHQaSQcgWBoKX8mi67rmDCTCV+9OdPOEdC2xCHI7mbGBt+5gXUNHM7wFnczu+kyTbn2Ms/0KJ/53+BlLMzPQg19pxCC+lbPXYJdC1hw/N2XqJUAMC08vR195lpYinndaqt9XwMpMLM9/4V0XfVAwJ2+zEqHdxukxFnZAh4eWYXIMd878aJTXQU8gyyPxqXvcVbAj4ArmEczxnomQX9cXKpiF2UrXYK23AObkPBTPEHvVDdqAAf3U+gozzA+ge3QWccnWCGgM/+6pcpBb6MIxe1ZSXTwPdaOvqG1HtAOHGmgTHMTuGpWQEKH8VY84ofGhso+uS3KmUNo1xhCv0uUx/UqavZekhHm6g6FoKbtYH6tse4d37nLOuTyIKbw77s+Z5O/H6txi3wITn6Y8pMSQIQChXQOk0YKs7jyvNMzi1KGOwPePl369FNdmOq9mzvgFLt3psZGt6dMHdk3AJxNDO+RN9BymeRABPQNWyjil31tkz7GF1XmrLhPWpr2gdKkM1tsmWkCdVBy7pOzG24cQ/GL0EK98zfKJUe3wmd9kSNKjtiss7rs3L3RaLjgmrErYntN91DSoB7CPUcfdZEp7n2WP3CDLGEMpaJxJmsVKqACWVjpkK69eY4P6Op4h5c5
  template:
    metadata:
      name: ceph-csi-rbd-secret
      namespace: ceph-csi-rbd
