---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dawarich
  namespace: server
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAh/lZF0ExTNYQVPX+Dre0NrwEpQTdG9gLBSFcOZ8JwI1IWFVDM9pynNmTYqBMpuTX3YlLNB9rreADLQbkratCQwujGnCqNGUEQUJlLZsSmxPXmbdYzuctE380nPZrwaT8z/gbQM6mV5McaxWulirlWoOFM+AyJWbDGcqvgMZVI43ZGPMFfDoRpqEEYdW4Ya3x2Zv3vg9u7x1wquxgmLBA3mRM6tAGhiobiChPapRiQUuQsKG7hPWsyN5tg7llNjGNob+fTCr/cb1vdl9K5jJ2Px3gQrJ+DQnNgv+QU4yY7ahA9863k/3tvy9KIJGRBUYKPGiLQwmMFAJJVxFzCNozYzp9fSM1p7sIlvVyOuay1hvZro++Ge8QI9Vf0Pz2KmHk3BCapD2rVbO1/YtE9zZ0Bkn7xb3gBb1yVgR48z8R6M1Jaba/4J1k3y/1UF9EGi5yUk1ESEcLXqtMg8f9gjm15uPsSIohhoqD4wQiOU2qyVaBAdBMer5lfohWVGLvN7uklhfW4mpGBnSQDcKeAuVEzy8GEWKbTmppVGol16kN/cLfdtWZ3B3R49ZbeSRAygyDnWRpE+RDnlbSII9slsLJLy6BURHFSE/i0LJztRCw4vMM9vUfDbB8bG6S+MeP4wLrlzxXKUtAALdHFDOGrTuPOfTYT1aDWtbFecmugWshfIhlP1Wg6U2hjdHDJTmsKN4AH6YOb6jHCgY9urvNTHuhrvtH8E3VfatHCvvU2fMB7IA==
  template:
    metadata:
      name: dawarich
      namespace: server
    type: Opaque
