resources:
  - ingress.yaml
  - sealed-secret.yaml
helmCharts:
  - name: kube-prometheus-stack
    includeCRDs: true
    version: 41.7.4
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    namespace: server
    valuesFile: values.yaml
patches:
  - path: patch.yaml
    target:
      group: batch
      version: v1
      kind: Job
