apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: server
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgDTLEc5lHbgDAeu7YWCbJd9EhO5ofERIuQr730WIWrazWO47+WK7CjZiyrnsAeoweAWZS74C0zREeEj+sHC95GwpWKDovf//9PXqmLifX5lT0LEGVXMXuriZvMSI/scmhIq4mCS1Jg3ECPcJXCHwMKe8FaNoarvimmJO+qUCvbt+4pl3QIDQemaSwFQE9L41bi4lrYZBNVXDbIAalU5EOgkt2fyFNiphAgkhUat1PgBVo2DdfC5a7a6tZtR7TYnXWkJzBLW+xrZE6Q01Db18ftrzvcQsmZpD/jREqpbeQbtsqX/lGlQoQFq5giJTV1bjcgmIuQ42lnXhjvKkYOcqW3hPYogExBgQyKtMXhxhyhjV4ETM2jhe4S/va6lF+Pi77jOUOfgHxAaJrh0/PZrEmRS3A8FTVSB5xgarPQlk7ZUJNwCFPXGJaOQrwlgw0b0iNi2w1Clq3RiTk2O1f8BQVqwcnUn64CC960MQT15e6Mxo6RWb4vcjXjvCi+XeNqc31Phdhq9w/lXQrfqaeDP+vMkMdpTcTjSfmIrInPUB23KTxnnoQd/qSHZ39DwQTJY0NozwLoIaSZxMw2nVhakXKRUT4YwsZ5zU926gfJLD1ItGIE3TEOeCXrjgbxJgEtqssH+fpOL7t5G0kpJRaSKpGX9dhZYMXp/ergqc+q2H+eUf9DNCvAVh6LQ0JVJ9Y9jBvzbvYrilnYv26Dhpd+sBscF
    GF_SMTP_USER: AgBHEtmX7zXJxRiUVq6P7j+BcyKeV4oFeL4az4+G++2sOZN/EgWH7K7HTSIzn09haa0cqnwWWNP8A8uX63dt3WQkNeWMskEOEfv/Mq9mv9ibugSGwaL8YJNNeJv4cUiZ8CY8QKwvRnuLIC4v2k7M5W0WSp63RfyHw6vygAwH8X/hwkFm2VhAGF+JEHanp/lDQ1guPiQAHwFqL1wPBy9YHnABlE7hUnEWUi+0cXUGpiHCCz50mIJQEW+L8cJYj6YKNpexbUSoyw+XXcngeXNqsuBGYqO3auDIvlId2krwVdMKRzZSaSGudpUoxaIxNgaz/KuxC3H4anVZtGXIB1E94Dj3nORgAwGU8TjOFd7qXBn/sRegUj4fqtFs8bn1WhY/qPCWVOmjfg1XYg7m9D/pYpYKUP8ydZAxelNHsF82W9+M+VMrAwWksLF8pa0+x9uH/q7aZolASwdypmhqTQnNw/9BLKFzx57ynEJ5n93I/c+hL51gRNzyJW0jyo3bIrt04bYPkLuXhKOjVWTUX488Z3AGsTO2qResx0nKO6uJjYD+fB7jZGJ3sgCwyYOUPM8asrh4BCGp5txWMpVLp5FJ5B/7m/gfJj8X2LghSj5whoXdw7LsMzg/yIuExZvyCmBeak24q7dB9U3IP/rvXY6N/QZ6epjl/xRxRUxY4qY8ubsw3LMl4ew5QCQkbDZPg9HnkCTX5K6XAX1hJrSioSk6/fJ1RJW4yg44DA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: server
    type: Opaque

