apiVersion: v1
kind: PersistentVolume
metadata:
  name: libraries
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 16Ti
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0775
    - file_mode=0664
    - uid=1000
    - gid=1000
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: //192.168.0.201/Libraries##
    volumeAttributes:
      source: //192.168.0.201/Libraries
    nodeStageSecretRef:
      name: synology
      namespace: server
