apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: applications
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: smb
  volumeName: applications
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libraries
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: smb
  volumeName: libraries
