apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libraries
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Ti
  storageClassName: ""
  volumeName: libraries
