kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: static
spec:
  template:
    spec:
      containers:
        - name: static
          image: nginx:1.27.4
          ports:
            - name: ingress
              containerPort: 80
          env:
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: libraries
              mountPath: /usr/share/nginx/html/podcasts
              subPath: podcasts
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 0.1
              memory: 128Mi
      volumes:
        - name: libraries
          persistentVolumeClaim:
            claimName: libraries
