namespace: server
resources:
  - daemon-set.yaml
  - middleware.yaml
  - sealed-secret.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: static
      ingress:
        routes:
          - match: Host("static.mchill.io")
            disableForwardAuth: true
            middlewares:
              - name: static
