namespace: server
commonLabels:
  app: static
  subdomain: static
resources:
  - ../../overlays/ingress
  - daemon-set.yaml
  - middleware.yaml
  - sealed-secret.yaml
patches:
  - target:
      kind: IngressRoute
    patch: |-
      - op: add
        path: /spec/routes/0/middlewares/-
        value:
          name: static
