---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: static
  namespace: server
spec:
  encryptedData:
    users: AgCeOcu4VGh5GXSCGugFUVloyE63iDQro6iOYAUwzi2zs4YE+rlMXTRq6qnWamIHmF8ad0g8FwWK1BXQo0QIhTjMFrmU2Ax0M+lNk/6hj6SrhtcFQHaWY+17CknMa2ADTchTovdalo/CFq6VSf0NN6oEQiH7GSHE9EHfNLMiuS22gfAkG1s6mSEVnS9I80GNEO/8JghX20BWQjHGIwBEEEVRz0qbaKYloDZYuDrZtnDCkrhubj6g2exjyGrL4FZlidrwIe5LTqfmULwsBRKUlmBLCUVwUfvXBaefz6NR9EcktokOELZf4RwNl2mMW1fjQgm7yo15c4IzgD8EDQdyZpju2y39fC7BQWZXjZZwoD0/rHSX0GkO+/a11cHMcKn6N2otgo2PKKNmRY4SfQLYaNICnCWzp6Jn6iFXukNs6Un2CGdYESReaWSkYv3CzJsxMxNl/zbht204gkYiaLwMhVFhphF8xTqoJt5ERICZEtxSDJTsI6BMOnf1ahkbkf7YcmkAp6DA6VCc+AXjw3P2c/qP9CJ2kJnH2cIJxZnbDHGnoGX/eCALXcPdnDrEyjjlQrfzLQkmHdM6Ujrt+KyGq9thchle4Duy0MCeKTJWFeVSm5V6YICb9n17k/wSLeLqw++xHL14JMq+oEAxspD2AMd1iMtanyGK/TVohCo/F+a4JBvgrokBpnX9tT1X4hP+7gH+pxzEj7TbaSe282laCWFKPTGb+pl1reCuXdTACJSoIcuPA0Cym06csMTNQ3I=
  template:
    metadata:
      name: static
      namespace: server
    type: Opaque
