---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: static
  namespace: server
spec:
  encryptedData:
    users: AgAu2wkDSvX6nKI9/Dn9Y36C+d/keVE0ppLyd7PIBUcusxH3qzAy5p3Pew/+FC6bGj5WtQLYwNxoBui7TCGSdXCvZ2AthBf0zkxRmKcJNGN4Ge5RKbSbVmj2LFPzTu9Z7DXms1TJqixkj95agIdiBje7TR9V5/+imBk5HRBgEcc+s+N5nN0HKORX0NIF11v0fUvD0GgKw083NAZ5WyAyKe0oZKoTlvQadeex96I81oDnA1DsLsH2s32h1uZu5xChss+Cv8o9VHyMSBmuyetaUxgDQ0tknL3ouIcpb27moim4ULnDsDIUPzQ9a9y9ucLd6AXsgJtD7LFp5q561nNKiu1h9kYfwRlaibO5G45NMygQqL94Ase/X8/ToPrn5f4k+acpZP91spSAXY78n9Dl5KTEA6EI6sfcxnskqEM2fQrdkAa+l7OHG1sEz8ZppYPcfSLJsHXbGVTSMLqTldOcAgGnOIDJwCj7Ro7//3JXx4/IwIj8ryrON5FdWdzS68c5oKN7jUSvmj+qlzRw1fybOhQluHjL0+fiLEB1ZIFkHd6P1+ERcL7VW5uq5Kjjdh1yrq9tRROI3N8+ylNe3DbxShzBnOKqJYMwgOmEAe1DyLFWo6dhO1MXfH4gzDay5WqmHtPdxKC/hJvkmHaD6x67WF+Tu6UYzuR7WFfiDl018Iwrk2IXxEQdLfkmf3hZTWoeiBhzyk1oyqejxlCXF8MSWMCsJeNsR74pJ9lUQIRKCnCe2ED2TwGEVfGYEPN2YLE=
  template:
    metadata:
      name: static
      namespace: server
    type: Opaque
