namespace: server
commonLabels:
  app: mealie
  subdomain: recipes
resources:
  - ../../overlays/ingress
  - deployment.yaml
configMapGenerator:
  - name: mealie
    files:
      - run.sh
      - custom.css
