---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: event-exporter
  namespace: monitoring
spec:
  encryptedData:
    HOMEASSISTANT_WEBHOOK: AgA1g53N9yp1+YAQUqu9VUhjEyUFpSIQkcyAHMt4W2tIjKE7DFgECAIosZ5dRgRXxIgL3uxRWqtRaWw+cL7BZBUQPxQ9IkIGcj9+vQn9oN4ItM5x9gujQLTt8vJwr604RYTapQHc8bAqX1hEhziS0RQlKM3i6hM6V8D6OICqUEiVSuBmMKqljSEkCtLiwj/nNVplvCMuznJScZpbZq88f2r2nAolE41ehu4VgiT4Dl3PUnrlZazP+ei+F2MUg7cMrNSR02Gtx3z+Zg3IQtNg2Bsb787hhHku6KdKAUc4YfNOqboGyV0Ok8u1KQrocvJwRMut94aQdhSbWVe+B5UME+Yx8023L9JeAf82ktwdgRJGzd8seDbKvd+TBch+Qjtlx5O8kUhjorfXdc/GWfqD+fbr44LZSEe6dLtkxFERyy7PrxyML1CHnsIwBfn1V0xZZ3uZKaau0nCXq7iyeww1A8zm8B77Rc6vxWFuW+E+/nLHHpur2WZ4WCge9VnDTs5Ej3cb0eLDHW4+F4rhnu2dgKpxbIS/kvx0duViOmOLM5Z3HVDmm34R00e5E1a08fMvKTrIs1JlJ/732wtGrffU8uYoEEnPAHGtRp4QRUIESvSHZY1O+PHub7IYXAx2hbRcTNaHDHUNSHDG8s5ZD5mvD0+4nORaQDflwX3p7wU8FDrHYg0tc/WFpTo6FVImA8jP0GDw0Xc0acU14uHGPN26HuEy1lOQUezD4GVQDcwRSusP/GdLD8j+zF34Thr0O15qQYL/S7mDztyUGHnBs/o=
  template:
    metadata:
      creationTimestamp: null
      name: event-exporter
      namespace: monitoring
    type: Opaque
