---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: peanut
  namespace: server
spec:
  encryptedData:
    UPS_PASSWORD: AgAiqG94Ra5mN8ZJrYrmGF/IPTAtRmEe+BMiKyXscEE4n84q52HT9AQ0HPJHzCzGqUqLaC0NzpbXFIWQhkI4hoXYCuO/BUN6V75n9tHcKLTP9GXmsOYu/yIlkaXh8ecoDi4Nh/+3Pl/pcpRNDFPcIvMrQySsEzJhXwBd2c8m5K9TGgWIVV+ihI/C5t9YJv9158jfvbdAxBUHN0Ae8ADzU2GWJlxrBlRJV8vc5LNNwT0hI+BKFpowATIMCkclr0H23Z78GaxEaLqlnPEjHhiIQMzkXQcAb9YRPoMnXSVyo+6rbAMJ8U6CHYDYQw8scqrp29dnUSlqMkK8mL+zziLfc65UGlYyOp8OKme5DoXWQya2agok4+t2vVTEvwUIKdzU7YmCJbpwSaPyYe9XFeEiHWBVF+dYgvHGQxL+GlgZ/kToFtQA4OUC+Y68FeLcajp4f8A0m3Nc18USrFlkZ/EeNSFfi+q1VctBtzdPpXJ3MwfxzVfyV1n++nreXPoh1tbzLWQ2znauhQFUxEXRaZfZCftZ10m9JWbvNj+wl3feiovPdgGLVvLHMZ+LM5VtBFvnys7cNIIcUmQHUJXpebrILEeV6+RxT0T0Eydpg+Qkt6wkNZFg0bTZoOq0gBBdoTQQKQuqlM144PuIc9BWJFs9spMenFYpPJfLcswqLC37sBH3fejxEFMPoH2orZl+O6grSyebD99BU3c=
    UPS_USER: AgAqZyMIN48D0/SYl8WQgMZg9kv9dh0jT9UeafDXk9llz9MnFPA8uK40hFxlhcyjmNTdmZcec/AJjQ2MIPfWBToUDzcVGWn6RwX/kvO8gPGBqr5FK5hwuYBumwATZ3OeJ524HD21txzQ+kE8lXkGh2YyR7QNhP31SY/+ZmZSPAPQzrXqooeIKE9TdIR63SMhweCOmqTMEwwU6difsZhuBSUQw+cgd7SQq+WCK4YQmprWN4k36Q7BZhknvfnVG5cpBWiImSVudx789sA6TYA4jN4uIQ4ddz7KwG2JgRpkZ5oT+R7XwnNIYKiX/rCmeusywFRKLn5tzWBUR2obOzG9LPb6lx+tNIqiHHyxPZTpkIlq5q+1UvUMpor1+OgnrAJkZmTz9xp7vjc29jtJaS/VZuTwX+3fbxyavgPMeiaaJQoKgf5Fh8vkCvgPCYF7cv5kM0iyUrjSCwyQKgo5Gmbri8s1OR9FmJwDVLvMaEdqW4OlerljoU5fDJAc+TSVXyzVbu9aj42kjS5QXEaqtB78CBP2cQ8zbk/j+WxI4K4TlcehelOvTDgUWru8HII1zdKK/SwzG2s5sR6BkKsEIe5J5j/Mspdv84g+OPEtU2EcBszRGHuKICHD65rDm90nSpmR3wmG7wjkhBo475LfUVzjjUdDyyR029JyZrvOzdsMJX3LM3Zrdi6r2oU7roFh4UsMiCL993Fzd5j/
  template:
    metadata:
      creationTimestamp: null
      name: peanut
      namespace: server
    type: Opaque
