---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: peanut
  namespace: server
spec:
  encryptedData:
    UPS_PASSWORD: AgCi/BI3M/7bEQFthhdSt0QNKs2ebPM0kXMqY77yD1+fpIeCmXTPDMl1GPZqow6m0KBpBZNQ6/lO20esC+QOkINe2cTVF95YtV0CM5eJIQSpX9zx3yTVZNII6IM8U9wYFa3m6LXFRpjXu2Xaso3rUpVRfZIVWURHbSB5oYgby1nqF6qUdcq0OAth016kOLO6fQwFP30Q8euUaO5zAdsFTjacVIyY8NQJBHxZWGre2ueChIb7ae8ypmVeuQcX+z6Md1n4oRS+ab5H1XzQqgUPu7BSpzuYKtRGWQpDCUbX+pU0VAEpWdjIPwaK3RcVRL6T73vFNB8MFabgr0UbSq145fGM2LbE6z8Em48IPnWGAujD/I0L04CzZp1UFea6ZZUbNyYtB4cpAtE0HTzd6G1Iz5XSfK0isck3gW/Jl3RCXpQdDsyPRmUCrIzFGYMcC7He5OQyUL1QsPU/unHGjP7qAxp1SBa44+wBw52uV564B6WMtEE4adOtyQ8znPYu2tBLfJIL9iewxSo1ZxV8XrbUR4S7Ca1cAmPxF5xVGlbwOeuDovuYkUE3/yJMQNcf4e+bJ8GMHkuIeFcUX6Ngw7ZSTtt7irpXs4xFXmrYrg+A3aZUiTdN+9M0MYiDHBvz627vs2LaZtCN7sppW99iTgmZscQ4ITPYxTnTYIbSomKnZdNXdAbwPkR2J0aeb8Yo73D/aKKZy/Nt3fQ=
    UPS_USER: AgAyImr3jwQlV2GNek74omyEcBBdyRwRtbsfKHJJFJAS+lexbs7qf5CBHNCbt/nF/w8b6yJExuOmEQyiw2W0LDil7hKslP8BLy2CJldV+vT0nkbxaM/4nutIZA4XMcIee3qJiw4J34/chQVdheZJFciF/Xv9y1mUWvZ1DAyJeoI3Z6uTPnzcdlsaEz84+Ob4WIHcs1uL5zR6PK4dCmTxI/atodFcBFD606LPiBnCDiw+1A7Cpfy/PZKUVXadJUxNyvrPTIbo9gK/lyLvTL+wGsR/YFbb4zvx9hRDUehidCGEWGzS1wtGwIz11ps8YrBu9WZYfsTZtlbgSkson6OwwezxhysGthA3nOiIfSe7VNYS6zGK+OsxMH4jmZj0ZT/fY3f4sJsXy4Ji5dguNzLsX8zca5COPsrwI0v/SXAZJpjdgJn1Vpt3ng23Yunl3Hkijw1G++w2Tgv+G87UwP+yWDNn2VRlmTM7fUJGQx2xHmWkYC7A1OY2fh/Z2SruejShsY4JhuUyIjjal9E3P2x7GV72fAK1ZJ+8KEEqxhdvDpBW50tyBYABSvF5x67VJapVZ9+JNb6K/NaeGmCIzmu9sJyFfMpa2ruoKtL/R2KrbHKQYaUHrvs4W2Ap+EK/5f1Ya51SwsJGwsBda3BadC+LDn7YqN35vruBS4JuJqUAjIcC3kJ6P3KwOF+1j1Pdulq1MCxbwWjkEqkK
  template:
    metadata:
      name: peanut
      namespace: server
    type: Opaque
