---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: peanut
  namespace: server
spec:
  encryptedData:
    UPS_PASSWORD: AgB+e1neduAGCUtG+GFWB6sWAN6vMrJfxFyhD8kvWwS+MY8b2fsyQzEdWle0hzkGGlf0c7qIIejWo+ID3rhc9g1vBDkEUexCpFI2QGHF1JTxb8xGPjUdtFn1StqPHlUqRojLi0h2e4Az6P2Yoo+oNcY3dfRF1iYTIyhJIal9UH+TtIXx8lJs6RIClt4z/HfHLxd4rX0rMoO+wdMm8HcfbKuLZw61yg8b5KwP/a36geugJTMdGk2S6hRoeI11YoD4XrdlNezDdUUImbos5ZRrfqt8XETfUtEKkF0S7FbbZUFffHh3mCYwu3mhDmwsT+W4DlSqWKjiveu9ynDKbkn2ITCObeZN1I518vxKZg3y6QbX+3riy1d+GOSpd1nap5HTMZ0y3PtHJUlZtSccGpi17+YjrmCyIzJaIsJS0gt5GS5rpbfyPwMPcVNCd4ghGUS5oRU/9cdXtKTyADVDTVVqklTVQipVRjzLW9VZeUBYgQsOWV99YwzlpQTNgDyQaW1+G7bVZ+jPRgdsOTKdzOTPE1vDEvNCYjAi4k7ODxF4oVZVCqiHnFDJeQlvFNo0D8/Q3bjm+/gYX3rSOhTD28kE/4d8zIRhb356X1ywMWRf+WAeHPr/3HQ5KSDULefaUv7nRXkiyLYV17kpSJI/qZZ9cVWzD8j7zG10sPdLlzjqxlZR0aTU/eORNtHhHqBI/GcY/iOfs6Z61ho=
    UPS_USER: AgBk1q6c0GB1s9VXj4IzaUqyVjAaBf+Ka0WfnneF9ZIlsuSqA3cJXTzT4MIAs0Rhk8wqPaziKMjuW8h4EgdDJX0NC04xsQA7O0V5iyUn7FmB2lMkys7fqdhSyOlgVhokaevWzIUJhTFwCYExfYaCqbjhif69Om7yOnx/CuRbRoEjOh473DZWvr0Vr1agfUEGOe53YVlUTrfVEoyy2SUpxHutRenQIzoTn3QwQ22Zn5jRxXo25AOcvIRYWvgJoX06H4AtnVOAcFHJ19LIIBMQ/tBjUxbRXDQi2KshaQEPWxUUS+xowGFfezeVg8CPwIRq78mzhgwBLpPWOZYakuy8tmDgwlB+MIyOgTqBwklJqoTEnKtzr4AVb8h5jYPoH98fCNNS/Vyw0qDp4TCzZLwLHl60Ds3T1T/5I10SMBnp4+9ETkvlLl+jI8RttEpQjmoZwQZcUm/wOxUB25kGmZ1rifjKfJAQw0PdEaNxA6BdMdaXDnJZ2MLTRjn3utEw+IPTccVop6FtCVLxsDwuFSOPt9E0rL3LViUtXVlISArZq/spLUdO6Rxb8OIiLoTOTPjSFIiGz7sKXBm9iG9HkZ3iLLq6nFzph/joY7/vYg+ReOiyKQ9bDs//kam8OJ8/oszRK0unhfMmgNl3xoEEil4YmfXEHvSBshDaQweJfrB4MAXDH1/q6mCpMh5SAZiaRirZZRqBArRDzFn7
  template:
    metadata:
      name: peanut
      namespace: server
    type: Opaque
