apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kube-karp
  namespace: kube-karp
spec:
  encryptedData:
    KARP_PASSWORD: AgAFU5Ks/uV61PzM4/n+iJVEuJ+n8SNW7rRpzmA8ZA0sj2oGcFLKqKtnXYpUKXFv+WuDcq6cNirIBdqYpv1IIDioeDDBGJaTnMTavid8AiF1u3Kr17YW9zll7+74YiEJdD7nwAsOic+wkYku1TZu+UP2B0n32Un6LQw2AQhPIltO8zMTKgJsYYxSCVWzo2Yh+FGQlEpWhah2OUqJbIqSPoAQpEe2KrXZY8rLjACf1EP1sWqRWBsC6D9cODHbqqDdiLWZRd1CD7VXGq7hxi1wR1iCFP5ueI4PqJ/4aErzWsNiHU8EgLXQaslIc15UFR07GUbqN8WKsghE3lGAMi8bqGqA6vettjQu6AuRuqrkwreqpB11eUMU/ljMFycrRybhVkvvscgGC/CNN9Qi5l9BE0yLLyVgF7rDkyc8apDS5g2RAKhSC28nSrKLU1MMNM5fgT7aNWWW5TCTztQ+CrnDLLv7popd4eZRzgwOvsiVIzUg9ehjaZpcjrhnJWuVdbTQEFCRSHAZKxA0jvlxW7zek1AIzJ5XVnWU/05isV4n57hAW80L9DSfMnOk0AFqMN3q5Nkx8yT5l4xG5Vszr8WugPsE6PJIUy1knHFxn3X+gCuenQ9vccyohK6Y8EG6ycFHjGfnTM5rTTyl1AGive0CD7b/FBSuZAUM6vI1dqTmJn9E05LguCh1OVWKgzMCgh2jZWFVg4lOQFFB60rIPDTzH37i6Q==
  template:
    metadata:
      creationTimestamp: null
      name: kube-karp
      namespace: kube-karp
    type: Opaque

