namespace: server
resources:
  - endpoint.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: nas
      addSelector: false
      routes:
        - match: Host("nas.mchill.io")
patches:
  - target:
      kind: Service
    patch: |-
      - op: add
        path: /spec/ports/-
        value:
          name: ssh
          port: 22
