app:

service:
  enabled: true
  type: ClusterIP
  host:
  port: 80
  targetPort: ingress
  protocol: TCP

loadBalancer:
  ip:
  port:
  targetPort: ingress
  protocol: TCP

ingress:
  enabled: true
  routes: []
