kind: Deployment
apiVersion: apps/v1
metadata:
  name: romm
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: romm
          image: rommapp/romm:3.10.2
          ports:
            - name: ingress
              containerPort: 8080
          env:
            - name: TZ
              value: America/New_York
            - name: ROMM_PORT
              value: "8080"
            - name: DB_NAME
              value: romm
            - name: DB_USER
              value: romm-user
          envFrom:
            - secretRef:
                name: romm
          volumeMounts:
            - name: romm
              mountPath: /romm/config
              subPath: config
            - name: romm
              mountPath: /redis-data
              subPath: redis
            - name: libraries
              mountPath: /romm/library
              subPath: games
            - name: libraries
              mountPath: /romm/assets
              subPath: games/assets
            - name: libraries
              mountPath: /romm/resources
              subPath: games/resources
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 1Gi
        - name: db
          image: mariadb:11.8.2
          env:
            - name: MYSQL_DATABASE
              value: romm
            - name: MYSQL_USER
              value: romm-user
          envFrom:
            - secretRef:
                name: romm
          volumeMounts:
            - name: romm
              mountPath: /var/lib/mysql
              subPath: mysql
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 512Mi
      volumes:
        - name: romm
          persistentVolumeClaim:
            claimName: romm
        - name: libraries
          persistentVolumeClaim:
            claimName: libraries
