apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: traefik-internal
spec:
  encryptedData:
    password: AgAAb8WzIPBGFWIepoPyErxuD2h18N/B0dJguKpmRRmGBCotchbm7LE8fcltgLy9QrqUM5ncKHSmLOBEi6RnI3V7t8M9Itt94oqERmJcqFi8VaXzdiZC8uP2l/2OS9NT3kJvi5IzmVrev6ZKZP7IgkYce8H/dGW4as/5wX5921s8nA25Lm4C53/zOGCkKvVdQWtIL1Qson7DMfUxaJAeC4BOmsuiWsujk+N+GL/zC4JcbTzh13h9RMskxg2qyuKvOMgBxW3ezVi/GOAIJTpqeeUwNljTW7qfuVgikesaNkzB8zCPUXm3y/4E96nbWKSyFlhB6RflRWRkktdE3Ln26TVhcB7tCRgLWX7QC83u5h7I+xCIICjeVUmABC10B4ujaSwFZlntCcnv7BmSATmhrcByfPWN+2aMoJbiWO6yblcj3IlVcxQYMUdY2BfNQ3Q5xAPsgkTX2y8vI5kG7ki3mIjcXHPCbzc4ENO2S3bwlQGe8SVkUNRANrary4FMo+kPTtOWCY7LhOjivwsoJAzSmD/KafjqMUf/7b9gurlH380eCZ83amBYkP2oSvXOvmnEdGAax6Vw+OZMS2XzgcpAXN5io/JeFPELIBKp92o3vWGjRgEFI8nHgE4FTJShLPbJ6HxP+WZUUce4qZQzDHa9ZSGFFLrACmZvxrpHhKSADvi6BR3rd3ED/6ZzjYq9kVj9qxP49bnSwFGz+hHt7vanAls5wYYjepuHBjhkmicuGKDuZA==
    username: AgADDQmyapev0Fk9w4cWgQV3SYuSQahlarMXQFPCztIZfpEr6ADmRththfN9A39Ww2iTumG4iqNK4leb44s2KYd0usDZ9uOFZpjHeN9cOg8sgtFt+HnpEhQP8ZFHgruFEMq/XZJ1fiiN8WlUJjwKpGAJiCpXwfNWhxpulSfIkInU2J2Vxt8hkcsZ51Pv+Jf6Ufev4LsOpFqsb3zgcrFJAHgu+kdOHD2LJMvKtsHXijEmlkJA0OZvpVdiGXeI6jB+3zBFig+SoVH6QdS7QaCrgFTOXrPjHv5SzaRJPJBqg66IIYlo68vCXJ0I6cDK3ZpE2OA61Zkl0ryYOeR44fScJL1cjPPOqgNru3Ffea40QT5FY3QHN6SQnhj2+uHE36fiPgpR4jnml1BbgroBQgrZ2l/bODn9zNxrHLjhuscPMMUWA9lydjQnm0bSJTPkAjVQyquockJhJT+RlvuBJellF652TNNciKS9lUPpYdff5XCIilUR1oRqMZCjXsgXGVocQE2PthuYo/tKPwD9DrJMK1oDwUojKQxBZg0laIaqaEu/1RKsCW2eq8SjCRLH4kEx96s+EGenTjoJ3GjliClRp2qOCxR/t97lB7wHEyYsVPQYZMP1YYYq5xm6wZ22fyQkmJT+bzaSc6iKaNhrLYH4wvZUp83Eh8IeC3noyK595kbL8eFIb05loaGUxBP+pKIpltOPnJ28HA==
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: traefik-internal
    type: kubernetes.io/basic-auth

