apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: traefik-internal
spec:
  encryptedData:
    password: AgAqnyQzIq1sSzRDsRK80qh4xVVPvim6uOmIZC1W7nuGlD2dombp4BgvD9qNsxtv0bvPjZajZQFEt/jjrJ1AoXuGFcMxkwHVED90ATcGwF27nn4bchM+DQtg6RsOzU2WajpgrWCMD3eHeO4gMMJwoZpG7hVFoFnpZWyIWPfbux7QuO9RF55BJWyXJG/mJDxGapmKcjmFAl/Z0spO+cFMmFc8RmaNPAlX4d9Q3q6bL8cUiNG00tSv3efgAlH2wEcYc+/q9pmQoZyv27VDJpBGgnKO3ZdBK0jV1BDOzfjTOnZZZri93Un+ZaGxzurADP98q6kHXIwfQ7ohpRq8AWjy6cjLiWpY7XOWBQd/gFP7yrwZiVueefz3gsMvxG7gQBUtoUQ2opuXuR9cBTrysiyg9QSwSKDxApL7GVGq6V1SjgDgpldeKjAaCke8n68+l8w47hrvTz8WFi3rd2RjH2FRIpgo5i5GS86Khv6gC+YMED21mHPoAdrSTU5chATcz34JKhfodvltKvSiPekQYs3ZBivFo/h51rBSFj4L3by0gCEYd3kD+1/fQl7Z+85aD+nrcEwYCuy7sJ+E3HpaTG6nvPIz6cw+y1iz+usUlsEiCKpHfF8JYhNeHIbz6QM1wWb1ICakLsI/bNa5bSz8GQfdsALKIkxEhMvPMY11StXpOZxhhs626y/yDJ5xm5ehWADABWJPqoOPUn5mX1TGglQiZ0ehI/H8VOlYTVmAldLHMWf1ZA==
    username: AgCCDTQ7uNZYGgGqafqEKakKeA1+c+XbDq72/yzXfJSRTL0qa+4lidyAlz84EQ3rWlzF67ER1mfIgd+5Z4v25QzezByPv8Ob37Zwyk83Nqz/Zzc28yW27+PvmqAcCbN2pHW1pCyjymnn4GWxGgMsGJUvdOdh1JAS0TAiuKFnzNqxH0912onrUm3o7+o0qtv18OiAoIRMhdSFjgoEM5A4sU70bvjv7hnIvweAiYIjDWRjAA3TgVBBhaFe0fSI567o3omF+SN+imPKHybuYfzKWygtlSZA29vePgVqnpYghQifTeqSag4JsysoLjx/GEJ7d/BnWidmXhQ9AuFtZeMz0n2zYsIuhlEuN4VAFRmbJ5rTEzYBzACIIYglbPchO1fH1O5vUwVlQdf8Qog3/ioHtUxN9U1+CGQqef/ziD66BbV7yjsEHDSzVIOIg2Ked0O0pNPs+Low48Mv9+N/2JXCt+0qgth88IfzBpEnCMK0iloUfoUD9jGB4R4+Um5xKkqY20+UTd1D1u7V21N4sqGgnkU23urQGS1uMUL+sRr9Yy5UbStKUWTsbBRDZH2WFzQMKQo6QE2urAA7TofAGAsEww6ilQ9Cu84HtCG4SjIzK+9wLB5NXRSkmG131ye8fhsMXFKSzUXx/uuUMiDP+pSQGeqYcBBJGuD4WQKpEOk1OrGXCAVhueQUDz7ANfbvUrFxOQnX4+StIQ==
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: traefik-internal
    type: kubernetes.io/basic-auth

