---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik
  namespace: traefik-internal
spec:
  encryptedData:
    password: AgDxLkWjFhTK5491CkdImCLWOWSO8WnX9ktHfDNqKMiPBjqLtSwB3VleFRnUXhJANjvGMPr8R7ljbnZioBAirTFewm7UrcUvwzYcex8uMfnwBB0sTFy0CIKhAUC9UVHayhN/PDKqEXIEMbwfDwcdj1dwjc61ugFqDdb90p1GBQt5NY+/0ox5zXeXbiDDSln/SoVAxjyHTZdboiJE0BdhWBBz3NnQwE8TzqUk2NpHyCO84UZZFCPIzKLmzHo+SWhv3Ld6w7XO52Kw85XYbZAeZDo+U3crK3w5Qlzpez2D2i4TsjUqdNqgZQF9tXiDbZes72ulEt1WTsRYH1+KTiPYhOZevB/6XDGydpcNNuzX6HD76nbG91mkK5ucRCHASnRZE8Z8E7sncagCAMUF37oq7BAQGtQk2YidIeaVLi8N5IVCBs+hB8A8SWbOzqLHaqA/kINsrt91kZ/HSc22i83/GsuiZDeF8KJG6MopBKW77BlpfiI50ZFVUqqE4zwCCmlZfmWImQZjdwOkiuJrYFWvWD8OlJGRpCAc3Nx594NGxYypJ5b1tf6WeCGjEywcl+F6/eiy9xcH866izO4nJDR9JJ2qk/YQdBXvl3yIy14K7KR0W0uDa4w165WPI6CQfDhXu4p5N5y176QrTm8/Zq2cKcqAw514qvITCIi+Gb+NuyhdkRUVmajanFQPKnLII4pieAuKPMKmtG/FIBCGqEeTFuwoEDh42LDujNI2U4j8buVruw==
    username: AgByQjZR6UbzO492TSk1keW5tt3L53BnIq8mVQ6w02M5XYtTMJC0idCAszO3o/lEAcS9pQMchd9zrtoaA1qsAoCYGwafL1oSDl/97rCddKnbA4TW7R9gEPtoW4Ak9BH1pGG8ALAk1MDevsf1K+SMDWunVtGIZZDBq7m9lwCy96dogYQiNA3+/v/25l4EuQ8ul9lQhlQpgliCA1SjOL47fQnt3+Myuhw0txSZVeG0ZICSv/ehfvDdKyM8jgk+QtHmlNipLDeSatmkX9iP0jNXR640te3W73zFL339/Z5eVARrCmcimJvKAM6OYxjKldRpSMv1zCx0b6KmGF0AAYD0LcjkJB8kICsIhpgParBO+y3NcxzdZygPIUB5vHid4vREO4+Kvy7uJui+bqAk6iU7IRtpjZT0Ula9wUxugv9qJeiv60FvjXHqcFvZUXbV/c1/aiDkf1R4xDo9fwfcH9bKw1hqbX5eqIwcESC8az+PmOPi+r5rSpzO06iohYpn+U12yHM8CM8c8fjRITXrZzMh2qVGoY75iNeIYyisKY/JDC7rNTrMCkkMYuzWgl4VqMCV/X78jwTaief+2VHfcSLAYAjNjFGOflDQRFULny+/Zmo+zxT6vL4UxuUr8rvFfsmJ6U14QgLuZOXrW9Y0DF/KwlINbP4EslMDv+cFsDQXmkURfzqbsE/hCA43kXLk0n2Gbj5WIDriIQ==
  template:
    metadata:
      creationTimestamp: null
      name: traefik
      namespace: traefik-internal
    type: kubernetes.io/basic-auth
