apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
spec:
  selector:
    matchLabels:
      app: syncthing
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      hostNetwork: true
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: syncthing
          image: syncthing/syncthing:2.1.2
          ports:
            - name: ingress
              containerPort: 8384
            - name: discovery
              containerPort: 21027
              protocol: UDP
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: syncthing
              mountPath: /var/syncthing
            - name: media
              mountPath: /data/obsidian/Personal Notes
              subPath: documents/personal
            - name: media
              mountPath: /data/obsidian/Work Notes
              subPath: documents/work
      volumes:
        - name: syncthing
          persistentVolumeClaim:
            claimName: syncthing
        - name: media
          persistentVolumeClaim:
            claimName: media
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 256Mi
