{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app }}"
spec:
  type: ClusterIP
  ports:
    - name: ingress
      port: 80
      targetPort: ingress
{{- if not .Values.service.disableSelector }}
  selector:
    app: "{{ .Values.app }}"
{{- end}}
{{- end }}
