namespace: server
resources:
  - deployment.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: flaresolverr
      ingress:
        routes:
          - match: Host("flaresolverr.mchill.io")
  - name: persistence
    valuesInline:
      app: flaresolverr
      size: 128Mi
