namespace: monitoring
resources:
  - config-map.yaml
  - helm.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: prometheus
      service:
        enabled: false
      ingress:
        routes:
          - match: Host("grafana.mchill.io")
            service:
              name: prometheus-grafana
          - match: Host("prometheus.mchill.io")
            service:
              name: prometheus-kube-prometheus-prometheus
              port: 9090
