apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgCvNss0Wqpqv3RLkaU9JEHDT9ODjttFtACHebdwnt0XaYoCw6+H/hZfhPRAGPCUGUBe6/f/ftxQKgkLt8MGK9hLj0oWo6x9+lrFZy6+dWeofmjiu5dvoUyMOKXhrlwWA7QdVkuiqe5ci0f0/vXo9ASyjeq5JnLSixN6ETKYfV+3qMDxbD+APltlyN//u2JKWsXEwxQUVR3Vbvni6V8Iutz0RkwKdOpco1qahYIiCEqt30Fhb84fqrQgaaogvPS7CJQGQEm+8CFsQmyw03dtIFGoLCafLuALfFw2tvyRQdpQqf0J+rQyQ14LGNIZMFdOnWcMqeGc74f56rgyaxRR6SXFPFdiHMevqqHwX/sObqVBhBpLfWiJ2OGBwerxLV7gY3hLCuadklfzIdylh8wNZVBRgItJu37FRa8lcxHyt0ggzJkKy5/uJ723QROpml7ERIN1ZH04jaUnnk6GMfUtC+hIvW6sCDuMgvZwtlkL/NQaGxVLN3TUuvBiKld5MZ2Nn0U4xD4KCL5XLYW6mF+O2k9wRrH9AE/NAf4SuSjapCl3gec0/ilrYP+pUBM+h/iGb93vb6eiJSk6DrW6UMRbShIYJMLfuvl62i7fFSc1WZLxpgXwOBlSm22txEHPqoxZQ4h1LcEJ5iztcHn8wdPaegjKQTpCRNhLaX5VxPYvV5KnNCPZyoaNPsVjDIC27xPBqgamHvt5AhNyp/4/JNw1UxbU
    GF_SMTP_USER: AgCj2PzoQsf9RoBdy7wgVigNCmdlRyBAFhAlKzCJIlsbvwPkmyTCSpbhBmLoT/JkAjC+SFdjiHYDE7yNqbltv9Xa9xg1xRT5h8QAAIuo4sgVG/mAram+p9mHPQcq2Fzh5K8Dinw4d2VxyMBXBVf0Y7AxiXvZqgto56H6AkM5ZDlBy+pC1zdiI1RSq/uAJlKuBuQswWvxqobpyczI158QDUTVtWKo/v4bCEhYU6+1SgcnAeyextqaYcvIkZ2oQk1LfaBOMhAItGMTNTiDtYvDU3v9E4vxofwwKoszLDPiLygFZ3HWozPsaRkG8AtUoA+b+v9nf6dK728jWzFStAHd8ZNbQC27DVgMExBiRoY5cDWIqwdPuHOarhojjQnZ05eqJ9GlpuksYzYV5U8FrLwG/IDbXqvQOFB5ywx7NjVI2m6ITzFZXIHT1mmY2yQSvWT/zQxDKhU6MNe8TBItirO3cXRBuTw17cFialZnWHl08il/FlJ2/ia71I6JELYDuxn6E6mt0WuvSRlAh4RODkv+1HvIXhSUtGZvHtTF+TfQufAiq+jlLVu1PVnwziXk31fAPaMnujaqQupU/IAWo0x2MezcjoTnRWUnU4yW7iA7UP79E5V8KerGT85Tzii0FhMD/+YRYkk6pcRWcbVYRwVG6av8ZqBSvKdZ2mFFF8ffrS6WitCpZzj9/vPE2AUfqQ+MtP8zsaMDavG9WLL7N0UV/qV9ppwRjfkItw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque

