apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgAoyfe8OtlBGblj78W0MeYK9H+OWHY6RJ+BPK3Vz6wIn+6ImuPRDBUPXmLIR2nDS1nwzCQMRAIylnhNjkJldZMBCWO88lHIwSUgTFDNTNbdMqRjqQZ8tVr8BvkgqGnsYaQ874naLSgWcCsQlk4PSS9lLILe2tRL4eBem7B0p4oTiMGn5UgGy3PqQ4WsUn2gU5vRHX6tXGLAa7WVXfYBBs64tjU6lgxilYqErtkPYsilNYRL0686nqqimmZ0Qr+F+bKrcowR3DGIUGXZxdJSpfbO6sAaB6f+NuKzO9Y4Ivthlp5le1NA2I4WMx1mxwBwA5dWG6kT6HRoLKsVdfseDDZl/L3g2dperk3pJus5BdG6WJhOPbvnvHCj1Em8tMFn+MnkPhGOiWZVQLcKoKquWgdKnI+nFa+j864KOXWg+xTdYJu0NTUyEAwghf010oAVnOrzxHdmb1VhtPLuy+Ds7AEqzafsYZvwLumPTtQTyjz5wGq5QREIIlavJr6L8wVKla+qJPcYQzSr2G7FyFZhpDyeVm7drFxkBeNR+Wv31Lwgme21yze0GA0QoxZkKqXpIe3EgD+xP+hYHoA7DXeBhwTkWclUJhIZfEknzm7fQRaCW3+/MXu4qMEjHU5DZTAsNBSCLdNDVxrC1h52O5RfnQuRV1hUcW2TS4ENVl1jwRsKeOdV8k3vq81lBEU0EunBetlHkSPhyUeHeGNd0Q1yBJ+Y
    GF_SMTP_USER: AgBER/Cs6Y9Jeio71DpJt1R7D9Q7gEmcpZRR6hQ7xd0ugjulCSHSufddnt+paQOl0d+Kk+m2mnWIpDgLPdPfsNLS4RLzZQ/9N0+mdM3WBdauDNp8uVyBum+kR1naXmNeVhRQx9+hQgT+aK909E2hnEdK7e73EWQ3MH+NZXqqB4AmOQLak5mIeW8ITY5yDe0gxkLAhR1O1Wb4W++tT2HgmQz1YRo+5pX4dWPGHL8vZAwY9lvV+B8RAookBJeaDI8jYHOulyN0jPFygW0NdL1JgnTZjPRqdtIIeGEHHKGjUs1kTBSNkjkbNTGqpSQGgT/jkXYGGMlHOB4AgEcKJc4J2IM4rDt7hz4Z94iup1J3/zbfpFYExp47ZsXHiUDcdv090EDYbogxYT16aS4ZtC2a+Tn0q9YEY8tKIjYUZgS/fYAysJ7dmIUO6/4nKJjxWIZS/FKRxj/9SQcVEO8AJX4nqcJ3WQujbfhK+rNeKzb+7xRrVnbXrl2UmFjQVT0qj4jjW8payunxdsB6oGOrmkfpjA3Qtu063GhJn5y4ZetdDLiClIFnT1zO03O+oDmBF/t3V4Dc9rPCkI8ItZiqZDJ+5xPWws2TmVLETiRqjySFNkjFkCeyRPl0BIXNhyC1Zf14LtfyWAWx1Z7/d5/eecb7GERVT2yrJyNcrNfdgVhLDv1v+UYuxv33kq8OEjGxvibkEqeceOjX/KU8s3MT+unncR9St6XOvOnsfA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque

