apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgAxj1nesaFKOnmfQhJXggJRWDScgaLbArwqA/wDJbirkQwSIGA0ckUowr+fK7l+1rFm9NWCcmitcdoHPb2S+VYTRiTstEN2h6teWsijf7gBeJgi1xS+iIfZhyj+xZa8UN4dyz8HvZW244XgrE0JwthA/El4uBTra1f/kUPFCXCDQkOx0DX3pCRBAsq2xjfHYI3CSSCNMvKEa5y3osAuiCjQjlmREiUt2YnQdvO/TWy/seDDVok33ZP+XA/s7CCrCYwHQAWbFb9Wg4xIX0JPcJadPG4BF2Rl94gYb6xC0WAvORhlvEDLthe7SpgcFwnkCNpKFORpQ3dYAN1fgRf2xkBAvqKB620+mjFN9O03NQPN2OKWzYCmvM2Tcb+/rXpY39KKnlkzRquIQgK45zLtztGBt6aea3E91eaQXHW46b119AcNt2QaQ22ldBSt5UfSxgOLoeBkRYaaLtOHCml4WnXIytOWABnCKRVWNXNkOZxmOPXER1PLKA3hhwqCea5SfVrfhnGsq9n99vKMDd6MTH48XV2cNhMvFzscvwEo1F7iQS1S1tq2HynsOHNk/nd7tcSRI19PO1ot8OBFG3O+1TKUgZqyLvnC6IOyTjinAvkdk/7DMTeXN4BqAyWVEWUMXhw2LtwgrlHqhMfoXEgabSqxVfQgIy0nSrH4sQ9/4teVeFrW9JEGd8VKHZck3eZy5GaOh495tCyy/ru6tSrLv5yL
    GF_SMTP_USER: AgCapX13LGmM9DcYvErUUjp761y8gXcRNe6ZG+kKvNBxcXSCP/QWGA5N0Ot/dBHEr3jI8/kbitt+LVtcuyYe4HRtOSj1EW4kq2A+a/xt7FpJIE8gk/YqsaPPFVfoMPOmS2sNbBawNaMVZCdAc7pdFRadaZU7h85JrR6Tc8DHsb1eNoDHbYNxo0ylBNl3Dplv4hd66vLyL2n1bIz1Gc6FVKNGcpEpoJvKwhyIcqAYA8C0BtJqCa6N49aqVCnbUwwRNoRLVO7YY3EiONAmb1M8ASJzxXQLqJ4pHt9BLI6zKrHa2AvSNyFxMHRQsrOVklFWTcPzvoEdPPqoE3YQXshisBNili9uYUDfbUQErnbSp6KIU61b18U6Wfw8yJj4QOg6TzrrgskPJViYu5BvCQNxCJ+xHz8WlVJ3NIW7jPvhlCIOpsigZbCZNszQw9LePnQsfhk8IvuJ7ymagexeGItuQkOPrW5y8QC7/ztZD8sWROLjUJ6qhSs4mZ+NNRjmMOACf5YhWfSSQ8oMVfRy2NRDCeHFRHy/+DwXVi0t65brYeksvj+kMKJhksFDgToYBRVoWBN1tl4CpLGb3yEPO13RC9FJWnC4FASyCMJmrTzaPx2zx7NswVdySljXTrzvuXGAj4a5x8C2u9g5NJ1OLrs1yfHtii0pEdi8OUg4LfaMHFuEVtUZ1GNF42X3lHSdfqh0GnThRWEGNmQNMUTGoXMMd6CZLEZDdC1FmA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque

