apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgAevv2rR5cYsmeNACjC2yuhPV6OOUHetygA4uFnUb0mgebX5R8lfG5dIAQiCSAEPVVD25KYM/P6ASfhJjpSPzg1O9iQpOpS0VqxMGUtaG3VBI4QK8qWtil6X1IiAxLTat80+s0D1xJP5xZa9RvJRq4UMfTPn8Fy4/3tbHXQetWQ+x1lavd8EGDu/rWFVZ+WWAj964Z8zJbK5oaI2v06sfXVBVTp9RikzJEMnnswby85CEpfN4GXLwNxMGafqA7C6Th9c7Xsl9yFqZFN/lasYuE/Mtl6VVVlvzzh53+25SYu7AOLGL3XVbJ4xWVWOszu39QcTr2GFFRHkwfDuLsR7YrnI9P3tapgoalEpN2eKlSok2f1KwgySbRuNzNgGPRVwuPldpXNJqD7DVj5i4wwA4fQee7S6cMI2e3pvANn0YFcaG0HJbgFXGx4sftUqOeZOIgaI8+RFJOol7oKqQrx2Bcw/yWIVwmd1lbLduGCFCQf+EEoyVehw5zwyeBsnnrU2M9dJoY2DP4DRIHEJJX9AZ2grKp+3UYkzm78sdDIwexTLaOjtjsWwrTHxF1eEvIylQoAze1aMXRQvT7WDELHDL7nXDMiWj2xVrAckFLgES2u4kCSICMCKpIH/rJns8/B2yv6TTwvNQU3TKCf9TtrpTHwr+P928j+Or3FlFO/aSVDmeBVPAcyrNdKY4uY84uM87CDxogvCvsCnUozTAdNBKTC
    GF_SMTP_USER: AgA5KEJ1e/MemaLqeubPyadnnXmsdpW1fQ0miPpm9Gu57x6V7kcTP5UPcO0EmL0Rx7RRLYSINrsuQmyscAEabFap9bkfkoB5VQP4T7GGSTufL4Nk1FlWO0Bg8foJFksWS+u/m6N0gHC/96tdjUD/PEi6Z3QTU4VmtYKX/n79w79f92wHZ6eNS+jS6FP0RdtGiH+SFKULL9xtodCl60FnY+VrZ/n5QEySiTGFA8H0QMtXh0SmYlhBEzI3ezBQj0zH8CppqPYke+12i0p9KtVtS3Pgb9WWcsYqzyZDnigZkhW1n9A23id0rXUGxRs7CsFLKCKb8jvkMEGN2fgApqV6JfV4dVjauYuJwhdlQj7sKQj+Gm/Xil3/8LJOB1KMwu0/n9Tu2ap4hBn5F7xdYu4B0vtlBKea7SwMRncwqXV7UkhuIB6Vz3FiAgvLfnQXltBIKvNw+/QVsJJ48y/jnl/MCrNZbGi6VVd136PtAnlJALLMad2eaiQdmNiGDagqCCG1nVRakLJhZrqJnGKXydNvXx4GVVDoab4kMs1kXr4ShfE0CFZhMEB35njzav/In1SVhJ8teQOlMmboRSM1Z2pcaY8HMWWRlNuA7yukGMRiDi8eA9vxyFrx5L2cdEk3upDI/SWVOsSlF2frY0X2fr9AP7rv9ecLcOr3q3BnUAltAmWzkPVM3Kjwm0pDW/itUPRnXg1DvvxziGATAX2/MKdn0YuCL/rSK94w4Q==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque

