apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgBPieRfNisEM4+kfWr243RIkzK3DZyzNrDfewyWewQTPRCnTQenVYbLKr5qP6Qxn9f/5IxZ5o7HDLjVz5CwxCL4mHW0GuW+6yWwawd3jMYyAe9mMvx83b4STtDmqyryHKV72ThLfGfHoiD6xy6rOwiGHeIkprzkFEkcNTIIejnWG6xM+Eth3p47F/KzKNbHRKr+kv+CdvLVvYoZuQjioY6/opAUlMn3+q6eZx7JL9r5ZM4fdwGxOiJYF3Zljokt7VZOkQfWMHZIuEUXGX7SDl5JJHxn2MUO/ccwkEKkv3JLOdpztgZ/y4RUvcHGHeG/iDyZ9GARarDMbcvnTupxJ3Kz+eyj5si87prjAI5AS+yZ8mSXppP433EmgHj0Stt9Oj5Ce2Crbrda/i7QQurRtH0AeCGR4KSQBbk/F4h4buVF1FKSojM39sfA8ZhDLj07vY1MlBlG9UImBKX2F+FCGUPY4gzcD+sOdU204Dw7XMXrlb0unMJOKxib/pJ9FRZhgYVW08xpRBCcdafVjioguUPw1Rn5ADkc9zun1JUQMmmObWYYV/YLiKEOkJJ+lxmXF/hqLnNSEdDV06bwDVQW/Km5yp7CxesVUDsppjnvs99PNj1XzWNfVG/6BuVeASsQv9WKHaM9Zu6+rZ3afq+v2ot4hP4vlRbp5S7RPl8u9ee5MBZzhJrjFO5z69MvjMHUTXlj1rXE6YH3ToCPG0Srpxvy
    GF_SMTP_USER: AgCJEJj4FiBZ4pkjjNE+DovMtPACXYj0KvLH9eEYiw8bZhRm/DJw0QjcsufWEi92tav2mMHsLwSRvMtBOIKWorMyLfEf4asFHHT5MalekHDxx0B0k0tpzhjBRq48RbfeAUwK4s7Cwas4qmt6rBEd2c5BmKmN4mFaojpAnwt8alumx9zs80o6qgOHoLUfKKkYZQ/XboswQDUtPJ2I2PVVsR6ZaWMJ7OLuGWgrAo3ILn0OPoXPpEeZ77OftrALt6rTRKI1G2NvJ7/JANJqzDJ9sLcxcrgW0+2NB8hGpA5P+HdBuvDzl66WWCLjUkALrCcqiQRYe9cpyd+7FFOUEzdGh1dXTLCFftiAZzHR05fu2MjlG/Sl/f+4Icm5NuPhrDWg4LBQJ/oZJqULvYdEK1w2Hc/j2LLDUsSSlH7ixu/XfrzXEcLyEHLgXVxj29/1bnJjmkYN/K82uDG63DzfPB+YfHWyQpYwv2PO6SD2VyhCcY2bOVl9zq3a/XrvILcGJS2BXaWJ7mSLfw1lr8NywPba4k+L8xaofNfwEs93GSNpg6sqRVDSIwsH08pO736bpJKbmi2spxE2nbAD8wF+j9/z0VfpkrlYKinOBTIAdYEe22evDa9ZMU2zuOl7T/8EK23vvdekp4prVSFTkNzQA7jG6+Di5yLq7G3NabetywbImamVrPeV8gLoE5mv7HSlUx2MawNe/qu4hKfC6pMqI4AS1fPSTfNyxn3wQQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque

