---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgDqDfdUVEWk9MOO+UTTna2nOP3A2ml1OH6lo/waSjGkPpVmyj+EWqqEpKM4/HP6W2VteXzpwwCXnO14urWeZ/vmCJRv0GExtexPzQXHOIOwPbQFGW5NfxryJF5ckEhbBXnj6IHgyiC6o+aXJLJaAzvaVbq/NY1XvEcLlS96ZDZ1F0huFVKNiUqb4e5KX7FWXhxGCzr4ymveSDmQSSTpBZHh1Na1UogH59XbCq8EJ4GZ4jATB5gdVaAliBtq64pLIxqcuKKw2HuPVjwOQGayam7Fnz79vmJVXPyYQjlICh143viNF20CbuTxM2MQq6iefkJVsB7l1j98CUnD1GCfjVV85Ime0Qibp9nbO2NhuywVQQbwWAWqwxChZxsp98bvGmgYFl1FI6pk/3oW0wQorrzqq+3wChoQ4AtkPzZ+26ChgUYnpTkvJnAhmmOi8qi1c9CNpXCcRORVTxuk4pyI2c1SsbufwKJlWSPuzQprDS94kSWpwAH0m0NwrZ1ISB99bGngdvkDfmz1KVLvuFJHKYeXoSHfZNina1Aj80Q6GJI561GedwlmbD3dORd25fzewfiykjqKDrxbjXSAJVwnBjYkleXqhx7uNm2+Q55Mtxhq8auF8hkxMVRn+7z88M+omGAb/sy4RS933+OlTlvMasHGKIFlTRjvpc3QdxSV8eIRtoE6U6BxgMl2yxA+yY4MfOfR53B99fZElCShHmG5viJm
    GF_SMTP_USER: AgC6cPyfDArqrYgc0Xei5EG5x4lnrTo0WMA9cQ3HJx6h8/uzvIQnXNMemdQbq4o+B6UE2yD3TpjjCzgT6zeitwFH+fXuiaVPguWE69zKa3NtOaTFNXmSTCF0TjJYIcofmKGDHSvdVfZZk6XYivqj1JyPEi6/+X/6MeeD0Kp60IwPQXPTRmjxG71Hk5pgw03Dt81AeXpjBiG7tfWhyqnKaNB9GKtHrVWeyv0N+PJkZhXx4qcPpsOouW2vLOz3I+Y2o5Cl/QHPRjwTbGFXVa2Zvb3MkKm8KSp7OP+mxsSqfdJzKK0BGQcdLEXGg01Or+7o1valwTuQIilOFvu9xR/N+Oe/z+O3s2JfrMNA4RSpS2jo4ZvI6bQcu7tVGGCbHZQFTc/s/EStc8grEmAfI509xQovCANy7mngPaJllfuvPYMXLFjD/6Mmb8oak8FFL6lxqNX0PNM8fRx1nkhP4NtCouYJm1Gxqk0fURpT114GOwJJ6OYWI5bygJudRXVIsRqOomlkU+jt+sp8lUNDvwaL/FJgsdHQUg2f2gzy4mLU6XBirszsM3XzDEWzLBx1+HYJH3R+xePXxd6+JrOVqKSY0LoKAHlXPuKJnJu+H10URRZEH3YksT98J4KkGTOgDRe1JsCnOwgxrNL3jC048yyuDnn23kmWzRmB0w3i8/vo2LlXD1vavKbGVG4KeRtIonib+N+DE70HYqYMy5B1Oq/UP0Y8LnfZroYSQA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque
