apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgARKYikgT1qdLY+ZZM51UojSbrZEpgDq3uDB6nyKXHQKQxgiO+Emg4CSPmfhuWASFJtdobWV2723HTfSfG00EaqgRO3BIyB7gFLMLkzqXRDEJMlsShD+9ufz9bl3YRJNggBEF3raIkIMPBQjxvPx/XeUJHF74APi3EKEHVTvMHJsfkjwaHQYSfWIZIi7UsbqGazhk4Tc6zSXjGpC7chfH15WGJyNJCX+e5OdsLT3snVDI0njU5keYkeVqVeEt3lnOj6B4QTV95iyXMYXPJ+UtATYQpP891U764qaaVcwey0GfPw7Ddn9yZrw2tCBjjcd70sYA+GI+l1OSGBi26AaqvgWzvtDPUxBEguLtocyLaA++XoqOnl1ao6hlwqka+i+qpY6XG9KMNjgyJDdSxWHOxmtC7CHzFHPNV39Ox39Vtp8Pt/dYf/UBgNCddhZdegYFnbY0cGs0CwiBVggdEyl+O8oK+KV9+Wu9tbOLUvx2taoCOvfgww9VADjPx/+CLAUUhGG6W+QAG3Als7rx0WK6hgaucWnLhMkWtinY6wm7WHV65V5ufFjuseV7hGQe+sVPY8JMHsReST4lQ3bHqE8OOAs/m7nzmW/WvCCzIwFR5I92xUGwUn+/raXg+QjbdCNhVnLjwT8eF7nqSwIDS1Wv9i+PjjabFAfGPm87lzTjUy+yE2CM51IULVcqKsq/44R6YP+FnCxqtdWXvKImjDYVwE
    GF_SMTP_USER: AgABbbIUJC4TGOlr5NePJUitWA4gm9HGSzNWSBJROBT5Rg4ynFEKmvZBGqsYxs8YjECqYIh8Nd5XUPbW90Sg8OWpMzx3ccy/UzJmLDGiUTbvfyqdC/Qb4Gqbd65+duOdhFDtjKBdfsJCyW+aOzYvoAcMsqphxKp7yKVM/JWB9Nr8waG9JL457osznUQ2K5OCDj9TDswDl1NXh1oNZk8Q8e1iY3upiIu8csNweLy4grGitThAjf1tYtGYN0/vxTcJOImwgzSGN2/SYQcP/NwpXmKHBtAKgVUk7g/QvdARfcxU2uQcBtbdAsghhVUsKCUy8Bjb+viWKz7ll9i0pLpGEp7WRFkxIx7sQ8vt2dZTgahV2z0SvUpN5/d6zGkfh7w5idc76NF9iqqxTsXgpcjvQT8s4aeSQiM8nfA6BoUmzF7SZzKzPjy/GUQw3TD53BwWyFbD9KW/rNulZ4lS+MsGR/62gHBtsW5ej70gHKBeP9y5FUUitGyi4RbUFhywRa7M/VdeI/SC3z7SVodnIQBmZWa2UbFeTgKjONxQwm/1v0r+c/+hpV7CueoA4RBwsjP91S8QRhHfZfMOvKUZ0K7m82L+4RmGyDGXLWggXGabUtioI0FHTUb2tXwamPyxcnzBiiBlPCsAuG8oB4Ds5yc6vcKIRxliPonwduNXNtn2fY+swiXYjCsQe4ySaMMWEUVsXKQ5x5I+onl1vtOJLUcecfulaQ2iNqltDQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque

