apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgB+rcXG3+D76Wc49JLHc0F0ky6y1HXW84Gy+R3+ripgBWCtOEmrwUk+lSv94Pf83sB3QRwRuav8HbaJ8zkkxZ59HBS89E/zXJTKX/XTXrigkDQXfDk7jlAtAu2B7ZGLqOeWKxIbasSwLszw9N+02chkCrYovQNHoU07qaIYhwUKdppluHR8P/Xwl/m4bGr5rs6h+leegBXCQno1QGUx8U0d+MoMjYcn+TnskOn3ZKIxfP6bCnnCU+1ZxtZ5lowjWIaafcAkgF4Vo+K687ZI7aa7CrmdneWp0DOE7G9r2QA0Dkbz3Sh3/rMNKATCui0VST+DTFrjvH37wTu7Qp29UYyybgAJW7uc84lLRIxFzSuShLgpqOTEFMSfLq4eZ91ggCL7KfSNwYzh0uW8K6hVF0NwNo8wFkrOSXOcNpTih/N5gj/LGafw4TlwDYRTMCzElfv22uc8ZxXkcoBXTzjzeE2gAlVBjrv6rmVzt9FglGuJ9W0k6etpelUIMUDG8QiM7s6x0tASf59eqw1K7g+TyZ1jCZr07H7w4bzS04rAhc6ChZlAb0LpvpSQvdPI8ZRYlzvbQVEJs0im4DwL3f/gZXDwvImPJ9hJacQXXu1wEieUlRhTEWQ3QOJp7iiYSqX4l0XmEmDm3e+zLI5iRklFzOfc501hO8WLUbHVq0v5XAchPUeaxsJNv+fjz8zBzOQ3d3A9VUsI/7jnd01ctMvZ47sY
    GF_SMTP_USER: AgAYfKfCZYwYdqvJ01C3kX6ylnPvZzP1bWTMD01agA0IpRxsptmE1wB0yzPaFO/IiEByDPBGar9WhQJbypePujTsvQ2VPCSWhystK0FPaRxQK3Y1Ku7s07WZJcdbTbXU74OVcFw+XoI5pcsVOEoFFhVdSFfEVnly/cykeOH+OOlyHNyMWYNU6/NbC/cnjx1U+aGCsWPEp3EWhVhW1EjZy7YT68t9QjsI0v+lXRO0EaioaRuXJgnD+zRnMH7jI1ovQltExOcYH2h0x/y+/UiqCH/tgDxR6mfNa2E+Ot67GM7tYFTD7kIw2qgb2X4IVF1vyxmsZqVmwecCTf8LPIEnuYFTyyYyj4HlOffRqt4WM08WkaGxmipfRlZQIVBW3WgLaGtiqqZN2CseZbykFao9e66Y1ydsGhBMJBLjHG/ldKJ55BxbTJUzHSzFl16LQbaqXcoW2w2BkHvMnAe+d9CyUh/L5hlLYyNxVX7wt1J8KEd+e3Uksv0TSDFlTowdcSTJMgujkcgu4nizjucG2yC2sZFLQQ6/fTgbxeUwOqg0kVhMcz1NTHhbz6tiKlT+3/JpJNvQaXYJEkWWCgTqJjmWIKVR1vP/cwmXs30QMjlYV6bwDC1t4L7Q1hyQQHtYP7uczk4dernmYikC5wRrfjLQE+rbQKP4b85BcNkS4oRBzAtbcQNmcMldZx2iIokxdeNQdlCF0bJzO2ZgZR51ZXNJEMcC27Ak88pAaQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque

