---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgBxHBVUbG32eqGP+D5GC9FkWX7/eVghk7OtfTLVm3UPkGTzYMyj7IkN/WQrtuEaWVgA4AHvqWj9kIpT5a8lWx96d2Y433FFPI6YFfLHb/6t8Qkau50lANHjJkCeqIHKSul/huCNs3LC1+SMIJbCpPHRpqFyrsWQ8OPe6CH32k0HC6zSgd2BG9apoA4ECPwf7TDGuLbXOcOd7zX4vBGXW9CqqrzUPL63Vb3WgW+BmWumhthOU2Sf4TvqFjfHYSld/FK0FELtRH3C94zfmh75vNluCSoSbyF3S2sawnrMgzgYITZ7ikN8KMMwqRQAxulZmbvCR6k+pcimTYhJtbvc7ZCSGQvWeqDtt5ttIzUCO4BlJsxtGwq3FAGt8SwqQS0ecJOsNWDGzQ2VML3MSrwCvedV+jVo5fkJDfzsA9wNsH71OjTGu54fNqwbCzVg56KZu27rRNLo8CWa42ln/IAqhJmQZLFz9Fdpc3SO9ygu54isA2YuS/74UMvQKw4f3VuSPazhIPFo/1ZgtBLg5UvcCExx+/7kXUT7jdR2UzCTWBtUZlqR87wccAvWob7eEwZv4KHtu3r52fxA2I5HTE7xONj3WcpEb+Y5hECoVbiP5JoBkdHpQ9uhBtX9N+0k309Nl/MJFH8EIyGSbjgwXZO2c+tzyhvVbGtWzT/eV82kJ1f6iBDJ9uOUlyFagjPDOuLYR2Hooo12x9UsRGhLnQes7fPH
    GF_SMTP_USER: AgBpbmPOszLwczaVb9v3EoQfw47MorvMC9cV/v1siXW9atiY14+lvjACLftquHQqguPkDSFyo9IXdc9ENIW6fd+IPYv9TRbOMYZl5UYTrIFL27myN0hu2JyT7xAEGEp6NUVJSzd6Fxcw1CYIUOdKFYJvROGCVYhjgoOQD0hVF5VLib+0UXkpRilnjJ5Oyh6bbE896bgvjr7FL78Rm4l+uBTDnuL22sikF/tLqo6wFF6ErO6b8Q67me17Q5kY2b2cQWbgVhZSjZnrhPHubL5hEvT3/fF1gSXxgHZ/P/C6YdvK8ZQiz/RytrjIMr4fbKLaQExvzEnMCkkXk6XqxDjy+2yhOfCSiiKE8y1AtCxZXaGMwGNIbflNvpfAIo+gUt5WqMFHxjPASTppOZM/S/OXC7v8EYQbGXLuBScDznqDzQMdkVmW0YHYNMBxSuCBEZqpz6bTBZx+U6xwUxNDOHg849mIHMN4X9ReUFBpKhZy79A1G/V5qyvxV+deB8WBhXO9/fbIzLeoexTtBDy6Jl+z1Ht0DF/kA7AxMyBdrtdWy1OpNUFOb+9dAoA87EM0SPAK6o24J8GAV8SyKtt06U8wqcuwhO4VhJ/ucXdj8tgY3jJtBCz9+e3e0GCY75jRX9v0EZo3DM0ogIyXxyhG/pMMNQWwDdBeVY7Z2MqPIza2wp39zovX2+LQ1D+dfDr5OgE2j5tI4VfF+t02AX/k4USIMsi9BOVgsDsjkg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque
