prometheusOperator:
  admissionWebhooks:
    certManager:
      enabled: true

grafana:
  adminPassword: admin
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local
      access: proxy
      isDefault: false
