grafana:
  testFramework:
    enabled: false
  persistence:
    enabled: false
    existingClaim: server
    subPath: grafana
  adminPassword: admin
  smtp:
    existingSecret: grafana
    userKey: GF_SMTP_USER
    passwordKey: GF_SMTP_PASSWORD
  env:
    GF_AUTH_ANONYMOUS_ENABLED: "true"
    GF_SMTP_ENABLED: "true"
    GF_SMTP_HOST: smtp.gmail.com:587
    GF_SMTP_FROM_ADDRESS: grafana@mchill.io
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: traefik
        static_configs:
          - targets:
            - traefik-clusterip.traefik-external.svc.cluster.local.:9000
