kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarr-uhd
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: sonarr
          image: ghcr.io/linuxserver/sonarr:3.0.9
          ports:
            - name: ingress
              containerPort: 8989
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: sonarr-uhd
              mountPath: /config
            - name: media
              mountPath: /tv-uhd
              subPath: tv-uhd
            - name: media
              mountPath: /trash
              subPath: trash
            - name: media
              mountPath: /data
              subPath: transmission
      volumes:
        - name: sonarr-uhd
          persistentVolumeClaim:
            claimName: sonarr-uhd
        - name: media
          persistentVolumeClaim:
            claimName: media
