apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: synology
  namespace: server
spec:
  encryptedData:
    password: AgAY3gHE/+Ze7MOZ3/zmR3ogvb8fWMo4lfJl5azNlZTuk6Jg3tT7oBtf4JXSCYllbae1vFy3ITltCGGTb+UEOVngyFQyn7yD7UvcF6HD/R/7eqgQZc76r52JRz2LfmhM6nnasB6ofv28sMU1VhZARj76H1H0FE8NoNjsv+yUuCyjz9dBAImqmq8OPlSaszt8f7gH7+ymrTSTmp3LhIv3HCd9p1T2Dx+OrhrZyUVYoDXxWvdkyvY+eDobZHqptwqwoMXKifLak1Y944uHpBZy5I5otaFvIcZIU5lkk0T8KR9OkWzpTOtzngwxLNASI0gtbo4ZxzBrkxj06hmFGXpibuYPyIiYUJseZA2/9/f3bOS/m7faxJ83Cb1SoLbZ/cnDieAuRzIQZY6CSeokkQ70dOcRhOng/w132BjmmKqQmQIMRAmzwY5JZ2stEVE21sy/9EMSa2aMmBHck/pre32fx22dvCGUFGMatn9uVonaGRCzEyOFwA+4VntuE4cqdbQ7POR3d0xU5v+Kw/lnYyefeSl/2f/LUuOl2P7Vw4E/g01K53/kq1pm+FjWfYI1LZkvkSCcrgK1yUJ8mGaCFMs2seDsr+CD0wib/k525Vh829+qL1XcJj/bTOYRy9w2Vyu8ps72eC5r9t68rhYX6+tQjts9Gb59xnnRsUmKFhQAU9sD/TQQGpkDdZBoiFl2V8bbAhD/rP5ZrSz9n7CGrPayjS/s25ujYoew7SYekcoB3m/ihg==
    username: AgC2dQJ/rwBFLoeU+F7JXy4fbcGH1hwqS0N8qSLTyH+u5yL80xmPoxiVgISzZUTlbAkoOMpQCl1+TRjySlH0WB+T5fO5Hc6Pv7PVLGJAjNCcFnkBTLmWh2zHrpShYg1YC0kX+h6J4mPL3Z8Pi+qBR/RqH3p3S8mri2LDeJHe9r+HcA9Tqn8HzG7vEy9l4tlkgBdxjR1OylR/pE9q3TZvnS0UoZsGIBTSfTW2eddrPpwOGLbzGNN2Z0lI1Ruc7SlIFX+7y2bhpGvVztswA8cnT53ho1PTZQPnMtl+0fWq3+TLoAY/ggadc8lyReMF3kYpFV8hsz8zNrSDPSOfR2UWoU7vuXLjzajExlrfEUfswQDCwTm71v47MLsGV9UmOP607FgLqWmV0ZmGxkDxKF4XXl6j/lELnNr2CH5Pol9g6l4iJ9xwMDqFQav+kAtJLWFVV01IwOnABV1j9+6yDTBjcwBjO3iGnQSegr54jYqQXv5KL2KVc3ZboLJjX2s8xGZeC+A7fZX1PxQQUC4urrvu7Cned/rC5Hso1cvLCizp8BO1VRgFniiy2hSJ6MmlxtP3JPoNFfzJmv3m5g2yjeETNNXWMhvshW1TXeCtxlVNBfxec+OxFBeVQP0IFHRdHkeToEOt/71rwRjL2fekL3NaC07vO6LcyFWZk0LCf+++Q16E7X71EQuly5F8vPBMefhv4G/9FjwshFxvZy8E
  template:
    metadata:
      creationTimestamp: null
      name: synology
      namespace: server
    type: Opaque
