---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: synology
  namespace: server
spec:
  encryptedData:
    password: AgAvD9thN3BEmmnVaksEQNKBa50RYFYqWscESIx6akWCtMZEvASLFzZfIooKh7biQ6aZxt86PPZ09zADKW1/e/JffYIlAOZZKYtKPR+gsrr4s8W0ug2ZNSHQtK3cH1ZkLqs6FhFZ8Wj3wVWnLir0o5gMvZoi7Wj7j2eUE+HEw6PiH5WCU2HRuMi4bYhJunv+OXbaHJCLHfbR8kj7YurufHspHcDAO+1O21mHKyXwfehQM7XR6uXbJ/7DUaizBbPaZYYCS5GXr00dcreeO6WH8z3PgOydwQKGt2Pr2IIsweKyvAkIYx7zvk1vmXcMsw7wsChsDSc+pmTJMV4VcXlrEzqCBmJmwNlOFGTWy7/BYnVPDtOMqrIl5EPzUUQsvACsrKflmqwaN/ZHdXHOa52CvQ8cb7odJFfjIt5V0It5FTkBDLWW9hYuqgt4WmXr6/Y3QQHjjs4fPnXRYPkqHeohfw727tdFhpmUBoHrdXNZIsuvf/cKfz9R/7C8axeaP7WTxLbRDEFEBhlUjRI1tSySmi430Eub3OtXa5OPVSi/ktE05ZTbh2WewR+zg0cvmmKewmAf5ClAaDLygHjKEGA2s+7aHsTKgqB9BI8Kkgenftt6YaOHVoP3TrBwXHUxJrwHTJ7dFba/Pu8FufI8xXWgJ4W3ztvwaQwf4uUkAMLG7DNjw98WVHHn+RWpU/CwtuHMDwpdE22dv17Ne+TB/jt5UTjmVh5tns9dMfYK9PNPfztK4g==
    username: AgAS1Bah4KzzHg8aEpWHFOZGNazt24CT9w8/6Z15mo21SglNCHXFKWl37za0T/exJBQxWJrovtU8dbNslsnn0ofRLRPS2K7ZpFADE4bvl9vfZOlG9dUERmL57s3bYKHej+Z4CwU/LZYH7JBUoSdgnmAM/anBE1IWWvobozD19V8lf/u3TNbNPqrMMLFKqPlkanfgE8eslKT2sH1id6v6ITsH45ebF0cWh/IfM5n63GQhMOBmmlrpsiX2DmpWt2bmVltVedmmct7E8bMSV/LRdkD5IhJ8UyKIKMOuZWTxkZEPScUE5pei5JHjXp0pdJRGOwH3op4qLGNwQfp4fEswaxGXny0B6sNlmV8BbBrbxL9sfZVX67OM/Ip/eT7UQHTVhSz/q8dyszbMuEDty+kgbcU1x2ibcf8WSQjzV4/EADPaV1ajGM1/cxeszeMZ17Xbqh4U4isxeFvKnbOOFGpotOknPWft9hCUOjoF3s57PdAKMtPGN+Trb9vm2XEIbWANM4ercEnQBBb7gASFmzikFW+TTdflppQ05u6jwQ4LrrbnYNkebzNsYTOZalNheqjCQDhcu6RtNoW+qvmMDzFjB1OEZ+sW21PRvWr+jt8lFuy5vAubX6URseEx/jKfxT94zA8fGMB+OnEv9/FPP923fzZ1LNo6GEHzfUz48BwxV9h9XZS5xgi0uAy/2NlNBjSQPTWMF1yyNNjn95pJ
  template:
    metadata:
      creationTimestamp: null
      name: synology
      namespace: server
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: remote-synology
  namespace: server
spec:
  encryptedData:
    password: AgCYjT5JamWo9t1swO8HGHFwCrT50Jd+7fJY1D+oaLvJk3PWaxHFfLMZo2Livip56JcfEnVOqsvh5pk5KhSohnMDEBAFWWlf6vEKfrL7USzwn78k3vp9mmf7zJCUAUfQOTObGpnmfGo8as5PrIh98VeTiTcTvVuyof2AQyjumGU3mqPlTUXc1kbKoQXt8odGa6+sTzndRLBDuxAe1fQrHehUs+Xk8tAkQnDwX0vhDNZWMAMbZ1p2wC5Yb2edDiwaLK9rqopSyBcLTvN4Eb/WUXtb3Ng7vm4jDf/ADnVeYZcUCb0fV1VjOEOM1+wfKTHsODCe6DD110hryn8TJWy0DJ1htTBkzJl1ctuV1igjiIpx+Tsa0BtLAK9aGuy15KJZhgqfSVSbe1AKab1NeslwO84Q9KK2cvpMoIpOprA2bCrY38LIUgXs6ewth3Pv9OMiPv0moJtZmKoJrFwlgrwJk+fEkMfknhX103xU5ktjBmVK3izObC05PLdSKmuzCtmAoN54l9jiDW0XBm10IJvlw1baMvY9HyF9MCuptvGTMaIX3YQt03fdL6N1w9I10c/3AbI/GdFzruF1Eo0wB7HbtLFjkX30c7b2F3TlHkqPyo5BLWyl/ed1P+D4V5XOaViF3lIR1prByVCqEPD+DIGTRUOD3NKGH+g/uTBIbb8YGbr+/19YX9AfOCd1NP3Nsy+Kol01R1y9lMO/qxK2a1bOXOTqgfN8qWWScRZi8GxYevemeQ==
    username: AgCPln+SMVcbilpDMk2wqvRTD0pS2ip0uPgOrzzsVZSBaSAwTnWEW4xKJTRFKxh/P1uV0s2D1kWrF8BfzvIXyMR6FRLccZjWG9kq5NgY1YqqIg1j3pDmcFask2H6SjVDIEwHxRr3Udwf5NBYJ7/gAQUegd7t6q1c9Q48xpTUQBaNJlp4pp+O5mSFY1wL/mAObLyIu+LD1fslA94umF0IurchizvpEg5SoM1GceNnfKSswg6hYx72w3bhb1vXVlJx2BnojEU6uMLDBoxZxc+2RxVOBWrQkN13bdAFHyja8aAmmlA7BjH6DSUu5oDtyt/yuYi6FjpQFZwhzKFSZNQDpqVeKx7FWFHwheAElufetjnmK6YY/6PN1frKKLlH8kl68W7/1bUkLTrILyIL2K44QO16v3auYLqsiqrfxXsobFlIpo6kdPvxlL1a2eOexHNJRQZu/vRj850U0mrlPMp5AwYMGWkRIbeHib1lzZ420LrypUWz7UDB+k+4QELapmvN6vvfNELyfBQ4ep9CRtfKLszF9T7vqFluP2CI8ne3m9IV1aUQ0dlToCrqyt0kUvwLDErxkr4Hc0gPvfUi37++wz6CKjLqbD1tfI19DhPhv5i3RKKosEtO13eCbfiApwvh5D75hYVYaaLzNjqjNR2s0k493x2mtVMGU3qOT7XsOchApKPaMGURIiUxeupfjVVXt5bi70Uo0l+eoYAF
  template:
    metadata:
      creationTimestamp: null
      name: remote-synology
      namespace: server
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr
  namespace: server
spec:
  encryptedData:
    .dockerconfigjson: AgAeVLWuuNOV9kRoAQ7TSH+jD8S1T+8GN66l+DAnkxyVb9R/bc4hgnZH+VwyU42+n9aX4qoqIAJis/Yn8yOaxQ0fJ0mGB85t86JeTQcXTQpQCpD8vVeyNm+W6kwPo+N+JNEkBmc8gEQ9Liw+EOU48I8YUZJ43DcfyxwGDavB+OqIowleUKjfV5B0IA/Mg22seH75LAraa30G3FRyuo/cAGTKRVY1Nolk9DTAAy40KBoqSeIOKpzmug/NTFz84NbJMpk5J2/XDvoO2lNnJTES4Owkt0MZrfkDYPHayo2YNbHZM7Vu6L0jcQ9XhGwJd9FKzfv+V+2418n6Pa7esufMTWaK5XWVzkOFYbdRkBPnP4ICi834V2+sgM3i5XoM7KWVKyBFFhEVXfqLwhTklm9VM0VTdY5+tV0lf3Tkq1GGDn7FIECMumGY1M1v1aqAIfRSmlj1x07TnI7KgFiowy29AXchvSbt5C4rpQIQbBdSsqvkhDjzQe1UkENTgAwvzDUDgknbQ86qC39TzN3y4IE2EupsoJJwZcQaspj/G7axqDXvRdj8fFNKBP7Q4z5C9BsTDk5nViZxZKoNgaj6cpOUK/t9i+xQrT707gkll84jVH5Lic2NDQtQ1kyjYgW4M2aAG8RnvBEp+L7YkCQBPkk0KKVY7bJr98WjCE2FYmo7f1X6/+kFVovI1xIDR0t2N2rwVOcHYJKnPcKgbcFX+r5F3LvXFk7Z3Nv2m4+v87zRiz30WedeagEfmTFOuTMk5d1SWL2qUzCdNnP4ujG02JjKwl+zLclLaHBRvPS7gt4i8VHxBJSbINpFhHFOc+ZS5a4kjG31lAqJDE/kbVWEOAh+L11wqtqfd5yzdR4g/OubUYJ+zsldIqo3GkpjvuC91LZvUhZg6oMiEPvE1GPLtuIMd3eDxYLefDOW6/unMyB2nbBVluGlsVHmut0+v15k+XbwqUGVj6GbnItFTEzD6a+SHrs5U7VcV7U=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr
      namespace: server
    type: kubernetes.io/dockerconfigjson
