apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinymediamanager
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      securityContext:
        fsGroup: 1000
      containers:
        - name: tinymediamanager
          image: tinymediamanager/tinymediamanager:5.0.4
          ports:
            - name: ingress
              containerPort: 4000
          env:
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: tinymediamanager
              mountPath: /data
            - name: media
              mountPath: /media/movies
              subPath: libraries/movies/sd
            - name: media
              mountPath: /media/tvshows
              subPath: libraries/tv/sd
      volumes:
        - name: tinymediamanager
          persistentVolumeClaim:
            claimName: tinymediamanager
        - name: media
          persistentVolumeClaim:
            claimName: media
