apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - deployment.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: nut-exporter
      service:
        port: 9995
      ingress:
        enabled: false
