kind: Deployment
apiVersion: apps/v1
metadata:
  name: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: plex
          image: ghcr.io/linuxserver/plex:1.41.5
          ports:
            - name: ingress
              containerPort: 32400
            - name: gdm-1
              containerPort: 32410
              protocol: UDP
            - name: gdm-2
              containerPort: 32412
              protocol: UDP
            - name: gdm-3
              containerPort: 32413
              protocol: UDP
            - name: gdm-4
              containerPort: 32414
              protocol: UDP
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: ADVERTISE_IP
              value: http://192.168.1.82:32400,https://plex.mchill.io
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 1
              memory: 2Gi
          volumeMounts:
            - name: plex
              mountPath: /config
            - name: applications
              mountPath: /transcode
              subPath: plex
            - name: libraries
              mountPath: /data/movies
              subPath: movies/sd
            - name: libraries
              mountPath: /data/movies-uhd
              subPath: movies/uhd
            - name: libraries
              mountPath: /data/movies-requested
              subPath: movies/requested
            - name: libraries
              mountPath: /data/extras
              subPath: extras/sd
            - name: libraries
              mountPath: /data/tv
              subPath: tv/sd
            - name: libraries
              mountPath: /data/tv-uhd
              subPath: tv/uhd
            - name: libraries
              mountPath: /data/tv-requested
              subPath: tv/requested
            - name: libraries
              mountPath: /data/music
              subPath: music
            - name: libraries
              mountPath: /data/youtube
              subPath: youtube
      volumes:
        - name: plex
          persistentVolumeClaim:
            claimName: plex
        - name: applications
          persistentVolumeClaim:
            claimName: applications
        - name: libraries
          persistentVolumeClaim:
            claimName: libraries
