kind: Deployment
apiVersion: apps/v1
metadata:
  name: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      nodeName: matthews-laptop
      containers:
        - name: plex
          image: ghcr.io/linuxserver/plex:1.28.1
          ports:
            - name: plex
              containerPort: 32400
            - name: gdm-1
              containerPort: 32410
              protocol: UDP
            - name: gdm-2
              containerPort: 32412
              protocol: UDP
            - name: gdm-3
              containerPort: 32413
              protocol: UDP
            - name: gdm-4
              containerPort: 32414
              protocol: UDP
          env:
            - name: TZ
              value: America/New_York
            - name: ADVERTISE_IP
              value: http://192.168.1.246:32400,https://plex.mchill.io
          resources:
            limits:
              cpu: 4
              memory: 2Gi
            requests:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            - name: server
              mountPath: /config
              subPath: plex
            - name: media
              mountPath: /data/movies
              subPath: Movies
            - name: media
              mountPath: /data/movies-uhd
              subPath: Movies-UHD
            - name: media
              mountPath: /data/tv
              subPath: TV
            - name: media
              mountPath: /data/tv-uhd
              subPath: TV-UHD
      volumes:
        - name: server
          persistentVolumeClaim:
            claimName: server
        - name: media
          persistentVolumeClaim:
            claimName: media
