namespace: server
resources:
  - deployment.yaml
  - service.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: plex
      routes:
        - match: Host("plex.mchill.io")
          disableForwardAuth: true
  - name: persistence
    valuesInline:
      app: plex
      size: 16Gi
