apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - deployment.yaml
  - service.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: plex
      ingress:
        routes:
          - match: Host("plex.mchill.io")
            disableForwardAuth: true
  - name: persistence
    valuesInline:
      app: plex
      size: 16Gi
