apiVersion: v1
kind: Service
metadata:
  name: plex-lb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.232
spec:
  type: LoadBalancer
  ports:
    - name: ingress
      port: 32400
      targetPort: ingress
---
apiVersion: v1
kind: Service
metadata:
  name: plex-local
spec:
  type: NodePort
  ports:
    - name: ingress
      port: 32400
      targetPort: ingress
      nodePort: 32400
    - name: gdm-1
      port: 32410
      targetPort: gdm-1
      nodePort: 32410
      protocol: UDP
    - name: gdm-2
      port: 32412
      targetPort: gdm-2
      nodePort: 32412
      protocol: UDP
    - name: gdm-3
      port: 32413
      targetPort: gdm-3
      nodePort: 32413
      protocol: UDP
    - name: gdm-4
      port: 32414
      targetPort: gdm-4
      nodePort: 32414
      protocol: UDP
