apiVersion: batch/v1
kind: CronJob
metadata:
  name: tubearchivist
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          securityContext:
            fsGroup: 1000
          restartPolicy: OnFailure
          containers:
            - name: tubearchivist
              image: python:3.13.2-alpine
              command:
                - /bin/sh
                - -c
                - |
                  apk add git;
                  git clone https://github.com/RoninTech/ta-helper.git;
                  pip install setuptools apprise python-dotenv html2text;
                  mkdir -p /youtube/symlinks/tmp;
                  cd /youtube/symlinks/tmp;
                  python /ta-helper/ta-helper.py;
                  rm -rf /youtube/symlinks/tmp;
              env:
                - name: TZ
                  value: America/New_York
                - name: LOGLEVEL
                  value: INFO
                - name: TA_SERVER
                  value: http://tubearchivist.server.svc.cluster.local
                - name: TA_CACHE
                  value: ""
                - name: TA_MEDIA_FOLDER
                  value: ../../tubearchivist
                - name: TARGET_FOLDER
                  value: /youtube/symlinks
                - name: NOTIFICATIONS_ENABLED
                  value: "False"
                - name: GENERATE_NFO
                  value: "True"
                - name: QUICK
                  value: "False"
                - name: CLEANUP_DELETED_VIDEOS
                  value: "True"
              envFrom:
                - secretRef:
                    name: tubearchivist
              volumeMounts:
                - name: libraries
                  mountPath: /youtube
                  subPath: youtube
              resources:
                limits:
                  memory: 128Mi
                requests:
                  cpu: 0.1
                  memory: 128Mi
          volumes:
            - name: libraries
              persistentVolumeClaim:
                claimName: libraries
