apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - cron-workflow.yaml
  - deployment.yaml
  - sealed-secret.yaml
helmGlobals:
  chartHome: ../../helm/charts
helmCharts:
  - name: ingress
    valuesInline:
      app: tubearchivist
      ingress:
        routes:
          - match: Host("tube.mchill.io")
            disableForwardAuth: true
  - name: persistence
    valuesInline:
      app: tubearchivist
      size: 128Mi
