namespace: server
resources:
  - cron-job.yaml
  - deployment.yaml
  - sealed-secret.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: tubearchivist
      routes:
        - match: Host("tube.mchill.io")
          disableForwardAuth: true
  - name: persistence
    valuesInline:
      app: tubearchivist
      size: 128Mi
