---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tubearchivist
  namespace: server
spec:
  encryptedData:
    ELASTIC_PASSWORD: AgC8e8dPFLVTfd4Q2ErsaUb8fHptuc8IHHinAaZPJQyF4/tWnhWgs4gK4oQIZDZSR+FfolDcIECdsKoxmbnLtUvBc3V+878ZLstC44QRJwaxSMlkdLXfVNcLCt+mabZPCp9s2txZjWV1VAUqb6sxj+632WOcPNXyTHHm+bPygjehe9O16LFNGWhFtXhXHh7jfknisNU4Sr+YkkKVL/TNbzoZ9N9zod64tBjY2r0ODFNXriYCDXqcDy4wXXt2gfCA82iuvTkN9pC1BNynsU+VfVzolzaKxJ/AzeviBeMMe4IMk8/faS8dEeYHUv9BusZki0r6Jejrq7HXcwvQi7/re1zt2fC5/AH7TJ2TvMtKTZGL2WxRlWg64mlKNEKsULIz8JlVlGkuJONuRR5hGJ4XiSISiO9xwrCQbCKyztYhk1hQ4k/FzWl+Q/Gtm5yZJyeXi8AtR8Sg8pBSDrWKY6pZf+XV04X/FSMuXcDyK0K88n5f+5Zz62ErK053Wg3LNaNJnhHsTIX8/km9GIZzmCXLDTb26UwTe26AG9RV5H3UyphYKwGNNrW9tbcT1yHxv+YrJISEdgVE2hxfdjioYsjgvFrVzjus7hYRMmu/dBl+JgdD+UA/lw2jDrscdDmDA0AYfRG+jP7fn7cIx3+z/8Nlyn/PQ5+PW8JRkPf4DrmRkQuK93Sh53C05YYTIXoATY+k7YJQftzYzLYDfRSfTiDWoCVrr/PXpw3A0KJMFH3wn/Z2wA==
    TA_TOKEN: AgBu1T0MaAJjiVpedsgSSDUWFRr6kQ/PNy9xWLMK6C0cISKEJayogOex7epYtVBaYVMa4qTm26xSjxMRZ4FrTzcWuWAqk5B9sFOhJtXTuc4Pkud6Mi1i/+O6UhYc3pXAu+o6L/KDBBcNq0NeJ0i5KyUiUDC/r5en3O60Ky3oVljkVdDMgCE7PbP+Hq9uEI444A2W1eWOwucey2oyT4KcP8vrx4CuFaRvuKp2+vgH5qSBAbJlndETx9BNbKkTtAN/kmtO5MI2sLboDOeGcHrKhNyxsxk0aMv9Kz5mbub7hH6hDexzMWwgCHECCpFToxgdYb8HAfk+wG7dF1vNjVGzB6pJ1xVN88/b36OZkotmZky0n9NXa8EImFW/vPD4Mgpm/PUPtpJMPGnTiEShTREPVqYMjlbA6vxWo2o0YUC8DzxFksgu85IKaHmgg0YxK4mV1ePpRCybpDhYZlnLcP46NQk/PE0qpLO12aW60UTqRlmEa9/MgKAIeo1PfvyV+OOlvbOO1FdPC7xoW2/C1emV/x529nmYm5vrhdpsF9f4Y+7OXOTy8Bi3/I2pByLJ7ZDwYSTPMfaa86sVbS9EkDLtV1f+t3gGOcK+oTspwu83dSHp42hUodNIIxDg9vjQM2WqKdPq1LJ3LHQsAz5g2Vb8wCbXsSeTd5iuPMPTAEun7TxYoOGSJaSBUb/ubkZVj2iDT7CwjGwXQVC7aAZdtnXQOE6UTwbO4O3nXhpLbtHXU/gzAh7T7bINrjk6
  template:
    metadata:
      name: tubearchivist
      namespace: server
    type: Opaque
