---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tubearchivist
  namespace: server
spec:
  encryptedData:
    ELASTIC_PASSWORD: AgByRX5Zcz2XPKualieCdo4fzXVC8z6StGEWvMEqvrOZoT4YTTpZ90zBeBXbgRASvHYinfZrenl2kHJAB35PV1DZs64FMKdHpn8Fs7CfOvTzHW2YaS83F1zCl2DNhV3W529OByZeFp9T8N7fkvrqNSyXcs3NUaxThXb9VnZC0cktUpAaxQ0V1lSTkLTZnUMcJ8C8JexLU1wNEVctCrolnTybU3txAh1Y1qnbW0FfMJoVygHsicKk8n1fOhEumdSvOUpDchks4VGduyCf/kI4UeVo4u2VkbiQufeO6gFaNQVySva9GKryEEQ50iQcwoEVwBXxblc89FD93kkNQYuC3Uq9vI13eJBzDI5ZV9maY9uVUYH9s1AjeE/fkOvV+Az+7a+7Uf96XHRfWoabs6ruLbh+1JWmNRwgTvmh9ucktMuR4w388BarIF9//aQmmzuA81trLz+58hioFWjIZz2+V1LmSy1o2sdfkhdGFS6w/A9a4uYgiZma06B6+xVruOc4CX5VagzBovXmdl9Gl/0V7i8GLl0GLKRiZdXW3RzMRZJxNqOUGADFwk3XV6S5cSWecqxVBc5fzWVkdN/foRa4Otglo9+e0wt4zCBEjcyB11ieP9Bpo7gueoP0wEB7Ukyp9dqDLymKgC1DdVrVRqO6n5VQPWNyxPQXWMf+Aqnf/PwMta2VVaWAcAleZFFNqp0GUGxZ5UhQftSvDJ4TNAgvFrMNMd3QA61/KexDP3veE+miDA==
    TA_TOKEN: AgBx4KS1MfX0aguR8Oc5eDcHTZjBTwewYTbm2pYuTQlmnWLKnUl2i5pflVKIo2CTlMI43/qaLzZXoDMx4h2T3h8cz5nV/rMonTCNW6RcTlZ5R4NQ2cumFuVDk+ekTU+WfbbajOb84+eLF9lfIsyi0KYFpYGmuIgHm7dt7D24uC/bUJVOcXYuOtfl/0WKCrElZgJ6rDikV5Sao5KsRFn/i9c6xPi96KVPBtoWMjrI7AEGIbHBVX6B9rnjVDjIZc7Kv+k5hjYE4KhY8rgrZlgMvtGPLfj/hKeIole64HYnef5ZLarb8QyOWo316NfnlFSoz8SI+cL2wq+Oppq/9zM9wljnxsKDBsSIEauPS7kdsA592uGK4xXOPRm9z6fBCBgXCkjB6VUqtdARf949gcppf1zDhTIIva3lXNJ7alJOaKo04MnP04WHFwsRGAmT2TRSkmMfCKO8zSL3xNZyFGHINWdn3TBwN5vcE1TLSie/VjGo0unGkhj7Nz4bjJHKg2+Ca5Sxzus7OFHQ2/PIKUwDDhQJMP+BodInYJQqQdji2fcsAdLYInvLAHyu6ilo1H76CPx0ax63kr3RVLHybQzHk2daYlwh+lCrFY+S0fFzoQMMdVs9psRj4AUHomrdXWXzAWIZiW4jeJ1w4TI9lumMpv/8tCGSsRgNcNPguMWA0oj7o7kKf8tjdFkNXPDCJGWjBnsvNbSMxBRpga2pj3UXC819+x8QHVCajeYgZDTDJOQ/CUeAiDCp3Q9u
  template:
    metadata:
      name: tubearchivist
      namespace: server
    type: Opaque
