apiVersion: batch/v1
kind: CronJob
metadata:
  name: $(VOLUME)-backup
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 3600
      template:
        metadata:
          labels:
            source: cronjob
        spec:
          restartPolicy: Never
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - $(VOLUME)
          containers:
            - name: backup
              image: alpine:3.23
              securityContext:
                privileged: true
              command:
                - /bin/sh
                - -cex
              args:
                - |
                  apk add --no-cache openssh-client util-linux-misc;
                  ssh-keyscan -H 192.168.1.30 >> /root/.ssh/known_hosts;
                  ssh mchill@192.168.1.30 -o BatchMode=yes "sudo /home/mchill/backup.sh ${VOLUME}";
                # - |
                #   apk add --no-cache openssh-client util-linux-misc;
                #   ssh-keyscan -H 192.168.1.30 >> /root/.ssh/known_hosts;
                #   fsfreeze -f /backup/$(VOLUME);
                #   ssh mchill@192.168.1.30 -o BatchMode=yes "sudo /home/mchill/trim.sh ${VOLUME}" || true;
                #   fsfreeze -u /backup/$(VOLUME);
                #   ssh mchill@192.168.1.30 -o BatchMode=yes "sudo /home/mchill/backup.sh ${VOLUME}";
              env:
                - name: TZ
                  value: America/New_York
                - name: VOLUME
                  value: $(VOLUME)
              volumeMounts:
                - name: ssh
                  readOnly: true
                  mountPath: /root/.ssh/id_rsa
                  subPath: id_rsa
                - name: data
                  readOnly: true
                  mountPath: /backup/$(VOLUME)
          volumes:
            - name: ssh
              secret:
                secretName: beelink1
                defaultMode: 0600
            - name: data
              persistentVolumeClaim:
                claimName: $(VOLUME)
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 128Mi
