namespace: server
resources:
  # - cron-job.yaml
  - pv.yaml
  - pvc.yaml
configurations:
  - configurations.yaml
vars:
  - name: VOLUME
    objref:
      apiVersion: v1
      kind: PersistentVolume
      name: $(VOLUME)
    fieldref:
      fieldpath: metadata.labels.app
