# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp
      chart: headlamp
      targetRevision: 0.43.0
      helm:
        releaseName: headlamp
        values: |
          config:
            inCluster: false
            extraArgs:
              - "-kubeconfig=/etc/headlamp/kubeconfig"
          volumes:
            - name: kubeconfig
              configMap:
                name: headlamp-kubeconfig
          volumeMounts:
            - name: kubeconfig
              mountPath: /etc/headlamp/kubeconfig
              subPath: kubeconfig.yaml
              readOnly: true
    - repoURL: https://github.com/mchill/home.git
      targetRevision: HEAD
      path: k8s/sources/headlamp
    - repoURL: https://github.com/mchill/home.git
      targetRevision: HEAD
      path: k8s/helm/charts/ingress
      helm:
        releaseName: headlamp
        values: |
          app: headlamp
          ingress:
            routes:
              - match: Host(`headlamp.mchill.io`)
          service:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: server
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
