apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy.yaml
  - argocd.yaml
  - audiobookshelf.yaml
  - bazarr.yaml
  - ceph.yaml
  - dawarich.yaml
  - ddns.yaml
  - errors.yaml
  - flaresolverr.yaml
  - homeassistant.yaml
  - homer.yaml
  - jitsi.yaml
  - kometa.yaml
  - kube-vip.yaml
  - kubernetes-dashboard.yaml
  - kvm.yaml
  - loki.yaml
  - mealie.yaml
  - minecraft.yaml
  - minio.yaml
  - nas.yaml
  - netbox.yaml
  - ombi.yaml
  - pdu.yaml
  - peanut.yaml
  - pihole.yaml
  - plex.yaml
  - podcast-dl.yaml
  - prometheus.yaml
  - prowlarr.yaml
  - proxmox.yaml
  - qbittorrent.yaml
  - radarr-uhd.yaml
  - radarr.yaml
  - rclone.yaml
  - romm.yaml
  - sonarr-uhd.yaml
  - sonarr.yaml
  - stardew.yaml
  - static.yaml
  - syncthing.yaml
  - tautulli.yaml
  - tubearchivist.yaml
  - unifi.yaml
  - yamtrack.yaml
