# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://grafana-community.github.io/helm-charts
    chart: loki
    targetRevision: 17.1.7
    helm:
      values: |
        deploymentMode: Monolithic
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
            path_prefix: /tmp/loki
          storage:
            type: filesystem
            filesystem:
              chunks_directory: /tmp/loki/chunks
              rules_directory: /tmp/loki/rules
          useTestSchema: true
        singleBinary:
          replicas: 1
          persistence:
            enabled: false
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        resultsCache:
          enabled: false
        chunksCache:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
