# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nas
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/mchill/home.git
    targetRevision: HEAD
    path: k8s/helm/charts/ingress
    helm:
      values: |
        app: nas
        endpoint:
          ip: 192.168.1.10
          port: 5000
        ingress:
          routes:
            - match: Host(`nas.mchill.io`)
  destination:
    server: https://kubernetes.default.svc
    namespace: server
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
