namespace: server
resources:
  - deployment.yaml
configMapGenerator:
  - name: homer
    files:
      - config.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: homer
      routes:
        - match: Host("mchill.io")
          disableForwardAuth: true
  - name: persistence
    valuesInline:
      app: homer
      size: 128Mi
