apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  selector:
    matchLabels:
      app: qbittorrent
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      securityContext:
        fsGroup: 1000
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: "1"
          - name: net.ipv6.conf.all.disable_ipv6
            value: "1"
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 1.1.1.1
      containers:
        - name: qbittorrent
          image: ghcr.io/hotio/qbittorrent:release-5.2.0
          command: ["/bin/bash", "-c"]
          args:
            - |
              POD_NET=$(hostname -i | awk -F. '{print $1"."$2"."$3".0/24"}')
              export VPN_LAN_NETWORK=$(for i in $(seq 0 255); do echo "10.42.$i.0/24"; done | grep -v $POD_NET | tr '\n' ',' | sed 's/,$//')
              exec /init
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - name: ingress
              containerPort: 8080
          env:
            - name: TZ
              value: America/New_York
            - name: VPN_ENABLED
              value: "true"
            - name: VPN_CONF
              value: wg0
            - name: PRIVOXY_ENABLED
              value: "false"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
          envFrom:
            - secretRef:
                name: qbittorrent
          volumeMounts:
            - name: qbittorrent
              mountPath: /config
              subPath: config
            - name: applications
              mountPath: /data
              subPath: qbittorrent
      volumes:
        - name: qbittorrent
          persistentVolumeClaim:
            claimName: qbittorrent
        - name: applications
          persistentVolumeClaim:
            claimName: applications
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 10m
          memory: 2Gi
