kind: Deployment
apiVersion: apps/v1
metadata:
  name: qbittorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: "1"
          - name: net.ipv6.conf.all.disable_ipv6
            value: "1"
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 1.1.1.1
      containers:
        - name: qbittorrent
          image: hotio/qbittorrent:release-4.6.7
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - name: ingress
              containerPort: 8080
          env:
            - name: TZ
              value: America/New_York
            - name: VPN_ENABLED
              value: "true"
            - name: VPN_LAN_NETWORK
              value: 10.0.0.0/8
            - name: VPN_CONF
              value: wg0
            - name: PRIVOXY_ENABLED
              value: "false"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
          envFrom:
            - secretRef:
                name: qbittorrent
          volumeMounts:
            - name: qbittorrent
              mountPath: /config
              subPath: config
            - name: applications
              mountPath: /data
              subPath: qbittorrent
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 10m
              memory: 2Gi
      volumes:
        - name: qbittorrent
          persistentVolumeClaim:
            claimName: qbittorrent
        - name: applications
          persistentVolumeClaim:
            claimName: applications
