namespace: server
resources:
  - deployment.yaml
  - sealed-secret.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: qbittorrent
      routes:
        - match: Host("qbittorrent.mchill.io")
  - name: persistence
    valuesInline:
      app: qbittorrent
      size: 128Mi
