---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent
  namespace: server
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgCl1mEMnKgCqfTgayI2L7NiExzn+SdpEUUDzyIKmiGQKJAJ4KatQdMSpADOmNKgrfsugNklOFSevUVDFSv8FRU6gw8kSrzVnMUzK6CGZqNsvKsRz9lDB8FZV6SilPKtEPI36kj2hBk+p6m25EZflyYvhVX6MvOrGHdhmdU1mlo48kXzjHqIUTqtUrv4mNXqAcyyQzujpu9abm398yr8VIBrn7zU3jZyZOB3GdxqeouVVIeIoysHtshbqNDBOww8BeTv2SlgqQjSW9aIXB0qcb5ZnnFqFAKXc71+RjhN6c835nDTltopKbjlWq478R+hSsVMv2TP0+3LgpIfUAu3RGhOPhMw+qkxrgQBQ8YFTwW7P4lPsI611AvXa05+ppFbsCcyzxZP9u3ksDIoKnCce6IA/4NqP2CWl52W3yZZy76Ij0Q6Lz/TETjRd5cvo2z0gqvOCCWv4GsRzq6AYnUySowKJ3MY+G/PqnwGZQD4ZkZQBrIj3F+JHeluO/4XZe3UuoC65P8l+PpLGS/5+z5t+0TOPUPiubQw1TXHmEg6IFI6uzCvmViVHP1hTQ5t2Tn4sBEWohMccAe2Yeb25yfaHe9piwoenXhKW+FAZfj7Cnndpbg2DpTDcAJsLh13G/uW7MPs9+kUUjV9v+MhHduu/sO2zkVhSZAsPyZr3wI5Wsy+/lcS84+12mv9lI8OKyvdSOg0G0Fe8K4ltb3akObokHmC
    OPENVPN_USERNAME: AgCc2YJNVaPWmaUzKtGVlJzt6wF8nBsPZADiueNRnCz4qkTa+BRxA+wEGC2+CWTI+dYraCTbU5Sakm5NROS/4Y/UNjfTPJQRw+LqBuqBhypjK7W0CaPzI2B3L5xjdFF1alNW7vU/EIF3DSOrNuoEs1aCExe/bsjGN1qzPceUD5lBf0AW765O5UcgLtV68GlBdVGiBejodhYoezwQVYWWrFD42phG9BwOJhN8Qp0QzdNXsNEt0UKPwHIOqTBfApTphoeXNQH0pQVxSu+zmtc/421S3Ze20FTiUVmfOEwUXdSVZBpB9dxBcGwguLd6ibhQWyFAkx/mBOHS9SNP8Zp7AXvmJOA7gB6yT81vj1lEPt4iufr36qsEiK5q45yv7K1lNxafbkzhuBl/r0MNWrxZe9hgbh9qbPIttVFNh902AziTgfyQEJGuaA0Wh2HxDupOHq/pfJI1koTUOpDofXnyfXghzp90T9Pv7cB+vQvODzpHWbLwlA1YFpcCm/Mv5plrMWMl6o9QWVifjaG+D4iE0zpD5EyJZiCXNe8Cv9vjmk1hnTxexZ+CK+PAsqXWEZ8+GWYkpOcjEuPLaJPEAUMmpjXIV5tzJOygB5AQXpVb/H4MwKtWKMUVy31fESTROOdlq8sVhRrF9uvcG6OAfIo2KzfSjlFVI0RPnKNtff6kU+ItkTsdk6XtB4KA09uoS0rP0v09zGzF0MngTP1Su1qWZ2Up
  template:
    metadata:
      name: qbittorrent
      namespace: server
    type: Opaque
