---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent
  namespace: server
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgCiTFPsR2m/ihsKWdS+CEZKIhLiNpjfCFnUUycM9xBl1H/PiuxMwhnKKuLNLqHhof3blZLWhn/iOXDlAGDgFiOD0qQiIryR3SwxgzeA3G4qSMLp2re1Si7ns0iS3ZMuhEfFPq4h0XQuYnxk3LkEA4s8SAFINpIFogaYC1OZvjRtfjIpn8wf+GoedPqbiWLtLoHH4L8mRvYvIVsTqXTqRx3R1W7x1R9qJZ6wYtcxdv58lY6pqwe2VU+cgx6lRx2djOvI1pujkijwRyMXnsMH3WR/4YQW4Uz6pNim5lTNas8cajuxQlwpjs0tHcYqmZAHjNEdm+wRXUsNgv25R8CrRQ+TF4ph4JV39RMzIR10tnjix0mb0S+wcYa08zf31nDbdNzm57RODpHhoCrqCXGAGM2im8eolN7lyaA8Y8UGFox3IgNQ5R8uK1DSxXSQw8zMydf4xVtoYt3OLdqdSPaAOaSiedJaeEVLcuTWPh7chFA1l9sgS86SNqHrIZE1PE0u+18jZ0zCu4uA9IR6BSVVUzYF+t6OdoZHNEiwv9zM7AON311CVR7EqZJ2J4wwAcE2tQKeiIvsJfuUdl5L5US7ZGqu1fpTR95ZDrEqENZKY1bKLYiGdpt87+vP/jV0HNzst/XcYR5TKIwXrSldZnbUT9XIVMzZVWdWnYrVBIz5id73t1YEhDmfAYg+aS3VwktRMEQjDz/dsCkaFha2gzSCM+Ou
    OPENVPN_USERNAME: AgCGEZefSkuP4oqn6TuztLi8i1NvUoTQKe6BRBriuZnVMWANm3NMRhfPtIUTfllXJ2Z35g9RMx+dGKu7vl3w+tvdXlhez0qKA4Of4+yz/IHeN607tm+FI/6KiWMjQL/avzqYDPzVkhbpJeIQNtN5ZJnhe1m7hrSt7BddWVYfrfNieabqL2OLO5z/yTKHNQAhy+o6tcBzFcDvnH+808AEiWzoCoShEf2UqTeuZWkrybDOcR4LVID0T6ItGhnP1mBrqGClzuR6Dl/qtT6OBeSw1v4MQhPQYfKvWxiw4Y0fxo5gfi9cub2e+xhvQxthY0YQVNpprKKUkDWl+hPY9CdqWA6gGEaXq8nhrV9h9pdWCg/ncfAyedqedxVpimijqLufgMdVok/SwtNAJAkZx45OXf8LBBbZ19V3mGBmjy8Mz0IzhJnPrThvxUNDtNSjT489lmuoukbCYaFXkwhCvPQN1TYoKmLndqM8VFd8Jux0aNZNNiRWVzaXNvrEPb9Cn42G80CwJ3mshg5WjYRMSJOCDpnCF23EJbXHWXYJP99GcCg7v9MN1acNo00EqNwONaF1vF/Pi0o5VuuJryEHKSrkGnijv2BBejKwTTNtwZNsh81B0rbpDh+JyqrqiYReOtreuDpMlG0tI/FzdbHsSgvBTIgD3JPza119U8PUmdKzEP1UWCr2VVotVGdYOSyGwY9kKWG1CmfkYlG3jPCD7GLnOGgv
  template:
    metadata:
      name: qbittorrent
      namespace: server
    type: Opaque
