---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone
  namespace: server
spec:
  encryptedData:
    RCLONE_CONFIG_GDRIVE_CLIENT_ID: AgAQMF1lV+gFbU3xmtReymzsbsLlBUYC8K9xaVhPh1EGMEAybHRs/nhkOHtF+aSneyTDtEm01P/RmkZSjwjabY7aLqvibbtXi5jaPcc8vRRiyXWqRXCSEPuWXv2TIjvoz1nTc/ZwRmJTYvMUNjgrrWmLVfklRxXUzv2WcSVBvrBMjOCB/LAvrc+ZN0TFrJySK4CrJJLHIvlGsC10tWocopF0QI608X6JjWJKyfhMeQxIa14F5Jne93nbpFeouk0ccq9moaoNjHqvMmd/fBmmyLm35v327NcEsrYQx3LgTOHcUwGj2BjqyTZ4uDY/K74kjU3q/ZdkahjdGefXX/0iSHVP2tsDl50Gx6ZY84DJKlRuFHUomJ9PAbxDGQeS0skxrHr/G9kJ6OwLsTxHeVMR0Oo1h2hVWS6BaL3TRFoOryo++3PYX8ALKocbk5whDT3nfL1F16gLoKiIBYmPbjsfn9EcdL7TitSXj3+Z8eEDtSVTsXFA2I+iqqCf0mQPzg7LYi6fJYlpDK4Ssa9QGCZXXzrvBRpAsfgfh9PW8/hnysS7I67sEjc85U0l69kWEJufn8MMEmB2o+YZfQB8ejLVvmQaTyPQw53FkH4491PBMayfMYV8WywCfjrE4lpTH2wGHt764eRomFRFqWWFaQIqjhkibb07sicZhiP+swxiCkTc6GCMxJtDcTUwxeM8faypznXDhU8S9xacGjxN2zMDQ1VUWpoTbuk1XKGMbBx3+j7fhqDRzWfzR8V2FPN2LD6vWlKtY3hkkPZOWEtm5d5vjHBgkff93Qi2VPc=
    RCLONE_CONFIG_GDRIVE_CLIENT_SECRET: AgB56ShmTIbsnQrDYAXGP668BUWV1Hl+EF2+SN04Xd+8GgcmWNtlgVzhW3OpLlSOT10Sj/tlPIiEnECL3sZaXp4gHMS+ueQstnE2e2KQNzAfNYShVovkM9qlJshZOSqVY+E4/Vt6mEA6o1DA4Pr1xrOinhinfG0t5P7mg+8hbFJZvch16KQgy38aZubTIFKOQqf6TnVlL4aG++BMkbiYb9nlwW/gFmqkXDGloe0oc/427gO3FM6gI9I7DDunKjFOyLXrguEnIAy5BRUC2DYeFIsQ4u5V8mwNdL0hc/ijiGMq0wDfSsvksoEDcZ5XeTh3RrmLd+6tKFENRo1Xo6XUlLUF6Q7d/9t8tzNEh82F1+EmfigIKxJX1y7/dP/VcjCWu32AO0/BPTnUSdQ/TmDhFs5mvgfqdYO/UFucgHx9+gxFON67ozpvnNTisvojJk/zk/IXjGMBMHoJhZX0BdU6Z+fA1nAx2TCUa28EgRIju9XqD5PHnQ4tgrVOkXkaC2RHKNSa5wzJ/MkG404GmoYfTXDR6NfAyF/pVqIrjW5D7bjznMT7Bbsycx9PaxjB88pwpCm8FqTVQDfDtkISOZaV2a3Z4hIJFWN58w821dJNj7TrfLfQQ9nWsTncCevVZaif0CNbITrhXw0MmaPwmNaz6VLVG5jRNRWOl0XlJ/k22UlZl578h7jYa/ZTfprPnkXGsHu0kNg7dNhqhN7krCIDHkbFPdkARoy7xfwsvEtv8ok5GKQF9Q==
  template:
    metadata:
      name: rclone
      namespace: server
    type: Opaque
