http:
  services:
    ceph:
      loadBalancer:
        sticky:
          cookie:
            name: ceph
            secure: true
            httpOnly: true
        healthCheck:
          interval: 5s
          timeout: 1s
        servers:
          - url: http://beelink1.mchill.lan:8080
          - url: http://beelink2.mchill.lan:8080
          - url: http://beelink3.mchill.lan:8080
