kind: Deployment
apiVersion: apps/v1
metadata:
  name: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: prowlarr
          image: ghcr.io/linuxserver/prowlarr:1.29.0-develop
          ports:
            - name: ingress
              containerPort: 9696
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: prowlarr
              mountPath: /config
      volumes:
        - name: prowlarr
          persistentVolumeClaim:
            claimName: prowlarr
