kind: Deployment
apiVersion: apps/v1
metadata:
  name: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: prowlarr
          image: ghcr.io/linuxserver/prowlarr:0.4.3-develop
          ports:
            - name: prowlarr
              containerPort: 9696
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: server
              mountPath: /config
              subPath: prowlarr
      volumes:
        - name: server
          persistentVolumeClaim:
            claimName: server
