namespace: server
resources:
  - deployment.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: prowlarr
      ingress:
        routes:
          - match: Host("prowlarr.mchill.io")
  - name: persistence
    valuesInline:
      app: prowlarr
      size: 256Mi
