namespace: server
resources:
  - deployment.yaml
  - service.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: tautulli
      routes:
        - match: Host("tautulli.mchill.io")
  - name: persistence
    valuesInline:
      app: tautulli
      size: 1Gi
