apiVersion: apps/v1
kind: Deployment
metadata:
  name: peanut
spec:
  selector:
    matchLabels:
      app: peanut
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: peanut
    spec:
      containers:
        - name: peanut
          image: brandawg93/peanut:6.0.0
          ports:
            - name: ingress
              containerPort: 8080
          env:
            - name: TZ
              value: America/New_York
            - name: AUTH_DISABLED
              value: "true"
            - name: DISABLE_CONFIG_FILE
              value: "true"
            - name: NUT_SERVERS
              value: '[{"HOST":"192.168.1.10","PORT":3493}]'
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 256Mi
