---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: peanut
  namespace: server
spec:
  encryptedData:
    UPS_PASSWORD: AgB71XpfjXFBHBZ1xlMZRfkSfHRJWs+hkP7+1r4uh4zzdGJNJgy6bwX9FGtDMamLgeza6pXfVFKQmjAUcy7HgPcRw+HzU93uyx6fcJ1fwe9FeOYX3PIuy95q+YMKlCScPOqbP6N0rAidG7f5u8wuXg2dABOUA4r0Bh4OGXt6snabSzaslhtlKPDQp+mrlvkGOcbvRTOIN0cEQFDfDKT2HJMJnlPQ65Y1bs2NJMS+vcMjPTk457PNe7oHJ6erBeWR/+pIatm5h7lypXkOTchVRVWg+yLcFJrMrb+uxRZ4dp+GAm7K2j3baUn+G+/CzVPYmDztX6z9HVqoEAWuN6n9X2+cClB7zX3Q7dqCcohcA2t1D1JLQ34bRths7fA/Azc9hffG0nixZAcBuCbHZG8GCGmmqtYZa5BDH/HzW485F3WgYtyv9cKx06T3uoPc5c/5V2w/94bvqPy+4Sr/j/RgGVF2XV2iL0DInYhwpFchWOBqjGmZaqwJptpC8J3naSFHdkoj7hEmNjfN1RwzqZSv7osPcuoEYREbTDd6Id1CZFv+ufw4KaMH/CdohFoWLyNE+IRjW8Wpfo3yTKsGnx2kE67H18yitC26Vn08OsIgR2wMpqlr0wDq2GzOJ8UvEjeldwWYT6GKtqdMsHKD57ZwGCVRnILL0jMinQHmGrfaDMKwBlyFSmQ60CkcyapjxEQ9N0W4YvZ7efg=
    UPS_USER: AgBIQzcq3W43XtR0vR2GoDSWL3op7odds7QHUhz1RExW7WxOxpL+Y3n5Tj9wbGGJzkcP9eSwFl/aN1ORYDizcOoxT8u/WmLR74CQYZONWomEUMlxI/NsWWK60PCnL29BVSovJbHjHIrY+h09tQkhiOeem0Boguga3K6Ub74NTkEikWSQ7dciJGM8j8PWJDmi+eWZv0uCsg1Q9URxfk7rTrEvwiC1W3eadKxuJH2MF9r+d+I3e+h3PdP2rTJ+yWdKn8dMcbjyxelxzQ8kpZAbyeXOtxgTrwqFNITWJYB2stJkr9AQu2mfpYBQYwqOIwH+7EmsNKvfvj4SxYA1JVWak8z6uebNQK/amNb4xNYGPL1jqXtvAKyApSu961rDYjytl2RKBdiQw7e7XhgLD1zO/biydbZYxlj3m7BdPzVbvyCCC/rwfbVYeWybLceqaiAP1/EQF0jiI7IM5VJ6sIz+aMqCalCkvfWz5AdCaaSdv+Ok5WtC4tyu3udzisR1avCvT3bch1Rz/h6gmE+yF6n9ZboghvvU5ntDBxSMFEs3R4slaYM39PkMPohu1HnIc7q4xwg8Pv1m1PojMyzy2RNJslCGiu8dAtXiI7GqZGxkCDZw+ArGbnbpaWrDOKnjbrtfJaRy3A5RFToRZMJuZalzpIZk71XsESJ5YPbw6DZWqR/6XIrmgy05xeyeRXcwCaklVkpp7jbjc4DB
  template:
    metadata:
      name: peanut
      namespace: server
    type: Opaque
