---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stardew
  namespace: server
spec:
  encryptedData:
    VNC_PASSWORD: AgAr+5D/uEl1rAtaW9KYccKlRmCqAHFj4Lt4GECWKkNWm2hA/EPC1O7bW1zV2dhJe9U+iFV6hh7I/42UphrWVHu3ACh8CT80kY+g8VJqkmpWv53qrcUJv2s35Gh1UITnp8hVI8ywVvWTkD8I2znsIuQXi4/jUh3TAadFgZCND7MwZnRMYweVb2eaf5IN5tENfq6YeT2yWE5kUgYEW0F5khcWTX2z0qxiqWxPO4NXeA9GKnxCpfddcgLM0UAPkFs333W49MeGVqrOAmgW/33wYnGtpk5WtrDlyyov3YJqy1qpPWyUzMro8pjH7PeSFexDFIuV5Ap5ikNFSjlHkZthfk7H+79j3GDIzIOEnEykZ5my8VwR/MXam4jttR+t7nfYb+2IdCzbHukKK5gDFshFjoybqBxVvAG+ycQUfb7srzhYyNlqi2gjC6DofE5UGtclZpey57JJ8Yf6ztFoA1470lTwn2HbreNQOp8NoYSqwdQm61JCoJtrgrB6Jy4FJroL2v/O1H7xuedPCW5mqIFY/wpF7J9+r9kwh8daEVF9BNDo+j2gAoeVmg8FAWvb2EnII5oB8/GrNN9ZdbWNOQTbU9IOY1sEsvqX4J9a4Pq1gYNXdDO42KhlHdLMLnkiwi5Wc8pkjedZnP2ZZkRdlzIa4szlFFn9fVp3p0Iuowd+jG1gThJGKVtWmUDdizSO7quTqkGTH6B5jCP1C5dU2e0GrgnDwyLaoRHH335KTDprkpkbAoo=
  template:
    metadata:
      name: stardew
      namespace: server
    type: Opaque
