apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
spec:
  selector:
    matchLabels:
      app: immich
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: immich
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
      containers:
        - name: immich
          image: ghcr.io/immich-app/immich-server:v3.1.0
          ports:
            - name: ingress
              containerPort: 2283
          env:
            - name: TZ
              value: America/New_York
            - name: DB_HOSTNAME
              value: localhost
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE_NAME
              value: immich
            - name: DB_USERNAME
              value: immich
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: DB_PASSWORD
            - name: REDIS_HOSTNAME
              value: localhost
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://localhost:3003
            - name: IMMICH_ALLOW_SETUP
              value: "true"
            - name: CPU_CORES
              value: "1"
          volumeMounts:
            - name: photos
              mountPath: /data
              subPath: immich
            - name: immich-bulk
              mountPath: /data/encoded-video
              subPath: encoded-video
            - name: immich
              mountPath: /data/thumbs
              subPath: thumbs
            - name: immich
              mountPath: /data/profile
              subPath: profile
            - name: immich
              mountPath: /data/backups
              subPath: backups
            - name: photos
              readOnly: true
              mountPath: /mnt/media/external
              subPath: external
          resources:
            limits:
              gpu.intel.com/i915: 1
            requests:
              gpu.intel.com/i915: 1
        - name: machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v3.1.0-openvino
          env:
            - name: TZ
              value: America/New_York
            - name: MACHINE_LEARNING_OPENVINO_PRECISION
              value: FP16
            - name: MACHINE_LEARNING_HTTP_KEEPALIVE_TIMEOUT_S
              value: "60"
          volumeMounts:
            - name: immich
              mountPath: /cache
              subPath: model-cache
          resources:
            limits:
              gpu.intel.com/i915: 1
            requests:
              gpu.intel.com/i915: 1
        - name: db
          image: ghcr.io/immich-app/postgres:17-vectorchord0.4.3-pgvectors0.3.0
          env:
            - name: TZ
              value: America/New_York
            - name: POSTGRES_DB
              value: immich
            - name: POSTGRES_USER
              value: immich
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: DB_PASSWORD
            - name: POSTGRES_INITDB_ARGS
              value: --data-checksums
          volumeMounts:
            - name: immich
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: shm
              mountPath: /dev/shm
        - name: redis
          image: valkey/valkey:9.1.1-alpine
          env:
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: immich
              mountPath: /data
              subPath: redis
      volumes:
        - name: immich
          persistentVolumeClaim:
            claimName: immich
        - name: immich-bulk
          persistentVolumeClaim:
            claimName: immich-bulk
        - name: photos
          persistentVolumeClaim:
            claimName: photos
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
      resources:
        limits:
          cpu: 1
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 4Gi
