---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich
  namespace: server
spec:
  encryptedData:
    DB_PASSWORD: AgBwdpUb6seWo7oidYQ33HxWkQINLzlAO/7vf4To/ngU6D6W3vTyLUp8WvktzzV2fIekYYjk+DE+cGi5Et+151THY3J/BmXeOz/83SxX26B1Xijvgqz3neKEykhKPIXYm7t7tWpgZAee88KtXM1yQXtLYUBE2p/JKwoLL8b8wkUuPJzGORmaj0iMD4er+tOtoA1b3sUkJRewzcH2Yxwnd08GOcstxxVtz2JciJInTge2rRPOiSis7NMlIOh9fDaSnO9AN0+jSgIKsE4IQRveMa94bvpg5maLFplBMjISVJrHPtHiYU6z4C8i+Db0TSOFmtuHmv9OxXySOSZkG3B7Jlbi+SL1ZXZdXDnEbWEc2kthcMPp3/Mileoqf6VqMZyVuWIHAEZDgw4CswM8Hf515qvi2jY00Aj5ri0AQ6r1s8LnLsLh1ZQUJN6Kmx0l4hxaA5tfl7NO8fX9Vw8gskhUt8E5fotv8TzD1+ZnXyOS6YY+oZSJBlFbHMnEJw+wM9o4JEfGRe7p9QtiLHgeq3MOyDXutmMWSyKpgrS7qk8mNxLBr2p2VooWIJtaont/D/x/OP0jUWxo8RzorhKSMSOmYPkKIczcCfnfpStvgHOoIl+T3jNd6mMusVpir3aBZAHWCr17hVAj5UPV2cRENmKtC1eY6bzMpHoasm3o5YkQISiK/JvpG5l/c7bnYctRqVKBcNKf5pV5QanBKdXstR8dYxiM53A6I9Dtqk7QK+I0tD26Jg==
  template:
    metadata:
      name: immich
      namespace: server
    type: Opaque
