---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich
  namespace: server
spec:
  encryptedData:
    DB_PASSWORD: AgAznoD/nFAzByPe4SI6oE7nkkpdISlot6zGkVNjF/od/HKf0RPZfnfmU6p4F5BeI0e8RT92WdDquVQQ9ZSO5naZG+QYs8m+YDh+e8DQJvcv4zqcUQnDAdp93Q4bnoUJm+j6PfYmxHRFoz4Rw7JAX4/ZgzuphxeFkHY7QVHWPPpHFKGXeAU8hwxQp9xLifQuFPKL3Zc+EFZ6uBIitPTIaHCGcsuP+xcH6zoliemOiHWP/sgG6xT41yUW+kP+gBt2iljj5ZbXj3m9zEkiCrn2Kc3huHTCTpA3UM8KoUXsWGdC/P/+/6V3F/SqCXox9a3CbdnkDQANVgwd8wC0tQ9zo6xkFG/pnX518SQkYwj/fV+EATwppWrvGi+1HnF4ADEqixJwKUy49sjwLWXDTX+E8HYWDJrYVUtyq2pPTwsO9g/HQdcrg9ypybzIEvzztsf8jXXs4RbsfXv357+vlHt5CTGCIQodPPGa7j82W2gaeT5RfyMHnVasZeeFrMx+gwsfzwv3vM+jIO9QC+r6QmJezzCrLzYcamUct3c3sGvHkjxEgZYzd7KzOrXYoGSSpu8L8RAbb2RTvPsP6umttMUhzVr26yy6JZ83F0oKRKWdITisIIosCFPrgHyECrOepWy8qwXN6YF9kIKDEDtMYOHLZ2HkKIigu0QApTG1AuOX0/7upwBw6fKJ7fcH8WS6rPXlxS55YA6o8vAjBYD+NQ0hQYP/H5sjFq807P19h4Lcx5XI7g==
  template:
    metadata:
      name: immich
      namespace: server
    type: Opaque
