namespace: server
transformers:
  - label-transformer.yaml
resources:
  - ../../overlays/ingress
  - endpoint.yaml
  - middleware.yaml
patches:
  - target:
      kind: IngressRoute
    patch: |-
      - op: add
        path: /spec/routes/0/middlewares/-
        value:
          name: pihole
