apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - endpoint.yaml
  - middleware.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: pihole
      service:
        disableSelector: true
      ingress:
        routes:
          - match: Host("pihole.mchill.io")
          - match: Host("pihole.mchill.io") && Path("/")
            middlewares:
              - name: pihole
