apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-meta-manager
  namespace: server
spec:
  encryptedData:
    PLEX_TOKEN: AgBDnPUG8GnwBG6FTRsjkOukdD7W2QOMS0ZiWv7Ubey8rtJdjhSd3yrZFMdITbX6LTjSwHJHHa0DBM9hekyHi/TGid9M1k2N1E6daq5YecdMkWaiROul1Qo+2jYLyC3/kRQ110V7nKL9Pv41qVvmjd8CClHkCkBgAHH4ZCJOa7RRdhVC2h5XZjnlawkTRp8ZtvWNUGXihIm8pcC/fyxWWEY0n+6TzCuhkkzUS+whJ2cLw2ySZ2RVTRzbzd9n3YUzOgoYWVwYaTp/CbP3F4B3Ab7FCLn7vDf7wE1iGy5OXWKErDzpKIp5dA5doXe+e48Jc4C1oPJS4+bgSzvYKMFTzGjR4o/1eaXz3a7kIEzfc3bwFX+7y8wLaMj9JJNOoS9IaD/rgMcrFnLVI4bd5fYRZKz/NcODqvCoLzH+iBrmXy3oZZVWRZAv/BApevPrv7FChAlwicC1BSWdIy/mXo9drYJgirx6WneGY4vd58bUFDiQlG2KV7eSKpsJUFHMRN7XbmL59lk49aTRRtxbfDFzGk6G+g28mJqNnKznq+ykTH1vDV9zkEzuwPqIznXawdd1SWCc0JnbvV+AZ/GwZxrcsdA0HLAn7/FGimiMoFxjROTmtL9sGV1i7j/OsoC+3ZxOVRsp3Loc8YCv5YF+tGcB7sP9gxtnw46UH+w8J2ovQ+WtrwOtefA7a7KoKu492J5TeVJ1/LydNCfjkVHhLoE8s8mJ9azxtg==
    TMDB_API_KEY: AgBDVgWWW6pajsksLj5bse2XycOqr/W8IvDFYA+MZGV8WRSQxaKVYkGcp0uHpRmMQaPQ0LLOt31+1dxijtLtf2tQdojJ2ATTFz2Yz8TJZ3wGWOfBvN/wUkTP2ZBypz+tKymWLBcr6QM/sgUpdB/t0yqx8SdKaW8Vg3xTaora9ZqdWLo4y2lZ9Um5nEdZuxP3VWBIKJbb+1Z0c9QmNUrzNBINrv/RDIzTmOvv/zr7xgT5pusgAlgNEo4EFyidggmWnZnn0bkkfD90BZDnapJZT10QYIZcvUcZ8UWHu8hPhugX/RL9lKB6nRq6eLpeK708vro6Ix23ugKHSanUezTk/mmm3cDeWYK+bEwJ77GnV9oxGlZe0BVkue3FhW8slhqmXoelOs+7L/Oa1SMvtybwkMiCdLDBgZWm9vMmSub/86szA3Nm22wxGpLzkEtB4OX5DQiqix4OPz3g8PcYmA2rPKNuu0VZEbAYD63YsXCLWlXwz1k7Fnzrdb1awNhHHakTziNeoV/bMs9CIQ/lkvDkrFBqLXOJmpnKj5N9XAOiD9UBELy/c13hKsCMvC6/AIbigthTMzO3L3y1qAKIvXJP0J8HmzpLdSvrTi6QbrDIer8iLL52DX8f2RrtDxP1DqvQaSHqqZkhCqilZAbkJviMA8QLiT/zSENTha1WkkDVnEk0ocCJcdxVsrC6J4UfkWz0veynCWYWzn/CZSEawC/ZIu35IsdAuI0BXIGoRQNwAtgLNg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: plex-meta-manager
      namespace: server
    type: Opaque

