namespace: server
resources:
  - deployment.yaml
  - endpoint.yaml
  - service.yaml
configMapGenerator:
  - name: unifi
    files:
      - proxy.js
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: unifi
      service:
        disableSelector: true
      ingress:
        routes:
          - match: Host("unifi.mchill.io")
            service:
              scheme: https
          - match: Host("unifi.mchill.io") && Path("/proxy/network/v2/api/site/default/topology")
            service:
              name: unifi-proxy
              scheme: https
              port: 3000
