namespace: server
transformers:
  - label-transformer.yaml
resources:
  - ../../overlays/ingress
  - deployment.yaml
  - endpoint.yaml
  - service.yaml
configMapGenerator:
  - name: unifi
    files:
      - proxy.js
patches:
  - target:
      kind: IngressRoute
    patch: |-
      - op: replace
        path: /spec/routes/0/services/0/scheme
        value: https
      - op: add
        path: /spec/routes/-
        value:
          match: Host("$(SUBDOMAIN).mchill.io") && Path("/proxy/network/v2/api/site/default/topology")
          kind: Rule
          services:
            - name: unifi-proxy
              port: 3000
          middlewares:
            - name: forward-auth
              namespace: traefik-internal
