namespace: server
resources:
  - deployment.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: radarr-uhd
      ingress:
        routes:
          - match: Host("radarr-uhd.mchill.io")
  - name: persistence
    valuesInline:
      app: radarr-uhd
      size: 2Gi
