---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synology-credentials
  namespace: server
spec:
  encryptedData:
    password: AgAE2SuDszKJS8q6Eag9FeNMrpkXVvvL9K09CI736YAOKS7m18UDcHoK9d5o0a7AsyJV71a+7tl116iI+uZinU0ZbMQXb+4YGW0cCQkzldWfu5t5ICnw42rGCMQAGiqA+esbdDSnicrDcN5w/mLZi3KomjeSacM8qT+wwAF2IrGPvC2Fb/c7q5MCQ9EQ9IiVzgzvwajR7HBuTY736RwC0IP3NS9bjEBqIDx9UfXDZy1XBQ7glaOaCNiux8W/OBB9C2lnuteF516Xu6ddGbuOaLsGxDaGhrwc1XBzLt7RqEZ5MXLLDutEQnp5DrCqoM71wJbVEwgqJxiFHDxu4Wb8gaxz7x1tnTeowwuQZdvlm2WQxvuFD5q0ltDhuTXWSxqW0vdI/h4i8mKIiE/EJWMlJ2l0CghZiKdTT5LcLTN6QUq6EA/IZGySGGT0VcNiffZeDnM79VH/rusK1mLL6YBZkeli7+KFHHM21T2tSDAJI/TkmVFtKgmxFxOAz7jkF/1fVtzsjskpvbXTMd664elxfO1Fyx/dz1hWQ2ZA1uxjHdz1orB3o5j4dum5FhjBPsI/JdWrU+FcRJjsX/P9RpCsJCrBwfu0VXgWNGgYv01j/14rAGNb2rdeqKQ0LyKRqm+NVutjhDfJlPYMFLaAMUxiXlPg29+DYepk0Z3LZnBDLuw787akVCCO/eZcfyC3anyXQNPhqRHURERxTw+zqlkj6LLBsDXDnkIylSjEUH61ontQpw==
    username: AgAzy2pjpEV8EK1bwPtQB/t7k2YCqjEx6YY1GvAQv21wwqWt8BzWJxmKKD3IjFmylXuQg46h/v3ps/FwulLkcJFhHOyigSY/1NboCo/WGPMixFti18QJBaC7i/GqylHTaohcJglyi8/LVAAZ2Pnc14ISvO29kFCS/8ggLDv/26CmJZtjH0Z3EXu+c8v1Kj9dbP7XJF6VBfeJbzsAWDPL06ObYFlvloQiMX5m9IQh8+Yf/hFcLRTHtmzYZvl4dF/wrvPoyHEjiZw1U8pVKJVUXwfEuBQlZ/QUrPDjZ8iZJQ8C9eMCB58I5wjIbP+ZpD14eQMK/XlEyCTfyb958AF0/T6YIrgNT86hSDkOKE/PvADw2Gcdz9mVeF8Jpm93hj7yAvTbLYVibFcJiA7PXHMU8V6tPK9l0RiDsMwUAA3s+G4NEsDb5U6JIv/83JXHXbVHhQzdBQ1GGY1+3KS09nRMHBsEk6SmSqemZS0G0EgCyAzGRVYdstlyqhpU+zVENnm3nL+OpRL/5ob+oxgwEJcxZ49jXeCH8LWzYh0hkztWsQgoHKEOjMqkXN5Qc1R7nQlMFfnpFhWu6YaSgYlPpCh9jSjdHQnY+fAr5P0UZg8X4Sq6jKCM/UJTt0aZXknxdGLVo2ViqpwXTHQyM2ge/+7xF/Rl+8fP/Yp8GeV38jZ2XDI/h061YnkwvuJ/45lHzSkP4OjS7B4JQOPigKpa
  template:
    metadata:
      name: synology-credentials
      namespace: server
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ceph-credentials
  namespace: server
spec:
  encryptedData:
    userID: AgClaihTOWBgxv5GXa1CUbUk9+wezLNnpYqVDTO+NMXshh6j8reCl1gEA80EkNhSKXqBPekDMI8l4jGJuNQ4AWT2Z3j2othnc9P8VMfUhnHrbWieFdVAcpvQOA2DgXackQwyyKD1CviVS7MF9qL3VzsG9UBpvuTKTI3QKtyeJpaTvZ1mPK460whO2Hy5auBtNdGEtiFQpceUrKMXBKUqM/J9lSueNjnBuXAdSvE4ljN7DWJwo/ZojW17vBUIixnBWHFcqexjEUm96DsQ1exJ3QRbamxfWS7Misaimd9PfWSQ0INDaesvP7kQ0wPX+jyepVn+SUdw00S5xfHUi/V2/Sa1gunPM8zFuMEQEfFnIuUy2kVEDwRxBJftE96BoVMJiwnobPKtDHQ3Wzt+SYjt9xCyiJRQoc3VcqL6CXkm/G2J7qhZQtx4pjPCRSUoNL4fqPpgUgCE+jTe2Y2pL/6fLexsKb0RvxpTBP7Md5tICVa30j/8vI0zYwk0XBiOOP4TuCGF3E6AEeDbqzkglfQtkTWdyriOsZoBhLsGgNaL4hC5ABhvBbnewGujMul/RoAJbaVZ2DqNXbzlf66QOxWk60kPm9BA2wQmgWBSj/6fvGGXq4sRbFYxq9b5YiLSNVtmtuiQNgYtHJRdfWMwaZzJLy1vv+tY/pgA4HButZ/6eAUlefN+ZU7aEV/6XVH/OgHoUxJmoaM=
    userKey: AgATXAGoTX7q7K9o3pfsym7PILaj4gVpqo7BhDRidMYWbE0BLJN74M9cybKXzBL9t5EwFaIzz6iTfPPKpghG6uX0uufP423/rW1lxDVeFWVzu2nBv2xjsD/sJ81eJxYxiWtb26sif2NrUlFfnRnbO2UP+ytueS69i1PsuGOO6CZHnEoLdOzJ83L0RNgXW53GqyCbtIR3F5YAEzXdPeqz2bVE8UAngXBkr03fwDIERiSSO0uguW2/YP/ajcwnWFl398bSXzltlp1SKjsjAMOIRuimqsGkIhwbmyrlL9M13H1JsmSVMrePvEAPDZjE7DcvdVBS6OqzYGe9E3qN3IcPOjj+2s1KopouRNdLjU3huCOXZCLAkvA73aNcnUbiDvAu8kiUflwmqn5jskJmUzN+LRkT8nB9/FkSQP2g9HpPhejFxrqHPxKpoTiWXzVil2YU3gLRQ2GOReRZ+J6zUMgQJKl91qndVUSwREBZdsgsI0qVWFpn3cLW6uihnQ4mw2e8YQMMBbenfHXnxAqFafw1o2sWQ3eDg3qhq9TZGQEH5CXuRNMmfGOfNq8kxPFecrTrzD7CJYrUsZozsSMTWcmOmm4ZAdx5YLQKa8atmXk/GJxiE5wttIsMDoLGNa+A5cAUhPd9IvX9uTJd6RVdnxGo5PwBZ+hGllcfFCt+2iFKNzcbZs2ODRigzi3swot9atIfZyDXvFQJdtZbYzLtYfT9JRyijv0JQQTvpIOqkZPRtcrNpMEk6r4l6r6v
  template:
    metadata:
      name: ceph-credentials
      namespace: server
