namespace: server
resources:
  - deployment.yaml
  - sealed-secret.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: dawarich
      routes:
        - match: Host("dawarich.mchill.io")
  - name: persistence
    valuesInline:
      app: dawarich
      size: 8Gi
