apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - deployment.yaml
  - sealed-secret.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: dawarich
      ingress:
        routes:
          - match: Host("dawarich.mchill.io")
  - name: persistence
    valuesInline:
      app: dawarich
      size: 8Gi
