---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dawarich
  namespace: server
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBC7e02/26VWTALIVQjprjTkHBhY9wDfrJLiD5v0zOD7YLWXk00+NiIHZqkThfXH6FyB05p/5EetVouGHH5QVA1154jm5e2mlGW5oQdnpKfcZIdUnTXacJIhrmz5tGfiZVDBTNGPmOAspeEDowjjjdZb72lpnPaPaFW/TpGv18s4/9poyNO8mNK+XPHHlw8SFyCRddv1ObohXMj4uBSQzwuRE3m0SewAgrz3//yGGnopi6+d3YWwoVtWUBwwoB0A0M1cUBa6nrig0Xvg3ojRZp2F7Crmuhp3Q4Qoxy0XOzYd3KYWfoVSAa9Rfng/v/7cTmQNl8Kt/FBX+oBf+q8VPOMXLs1+QXCPh3wTzeMMqtcauwy9RFVtkx7dDT1OjggzHrIkjp40W3ZgXSIphkf+n3QaToB0uTkRdyv9Tyoz6Q8yhC6Qu37/wdiCueuxKFbCcBzpRd8xWDyDVLoVzZL6ZTn0tMs7sX2GZaF7Qhi+zY015k0FMP6uP3vb3sAQyLggV1WNcekWWFwQH2ZoFEHLZZagnHOhSUlE0eW0PCaE7OnaqYxPeE/yV0B4VqPumsnnVog/pVb2hh39uRa+/kCz62y7h4NIItDDFiDu7hvnGM9ylaTWbA47uQdC302b9erCsE6EjQmUCQt0C3irKWhZcp+ezOHDTiUwz/lU4OKOA2bIef6QOCuZDmyKnyu8Fj/8SWLiRD51V6i0cY2WTnlABfy/mWJ1TiDBh7UXdBMv7NIOA==
  template:
    metadata:
      name: dawarich
      namespace: server
    type: Opaque
