---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dawarich
  namespace: server
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAxqG9BtcwsSlWinGqWJcrXXcmC3FSDCplcWlPrggQW2OlawD5z7l4VUcMwnfN4LnmWI6zoF6r6rUj1fLS4qJAQiR/8NzdwWBRQLogxBAbkeihapYtIwQFjwWFBn4T/i5RCEa9SNsbnBDIsfhgwGLmfTO2AyIVum2SUQFtMpF+rc7W/ry172DQ9upW+0WuUxOIosTR13RBn5wraztz8dAmC4dVQCV2aoEqGGxVIVbEYbCTA8VJxgunOsZD6g3npMWfEv4dV3OB/U+8dH6DAebyWPE7s2xk7wA/nLOiKew9afMGr4fXVu6dNg37gj4Ij38ZPlkc9xyh+DPJLYmtM9h547OylABVZgQFbMgled8FurCrx2jDAT+up7jhuWI7iD7CuTt2dxvorhn8p5/TNv3lizTDy0X1sMr1EnBF4ycDRk7AnNtHIoE+lzMLzgX+iSjNP+a60XsfZnCkKgM10hv7ONYkFPzxoQH0YYFybi9WEXYfciHnWZUvO15OtzEghQIm+u+E2ESn9ncAiYd2DYh8lGnR3RRZkOG5//cNTZk3SJPYKaxeXyFq+ZYG1CmRpFfdbNal6y19oRXI0YnxNRQ4nKiKjl2u+SQ+8+oEHiMDUadsDYxlsBpwSanwzJ/Au6iWtZftKKJTNpntSW3VskqZDzdbVHuUJ50dXdScXCS03wHSqJsxazNfgfeG1UrTVLRe4vKKFq5TAxuyOaqTONbn4SX05qgpHapPABFC0d7El0w==
  template:
    metadata:
      creationTimestamp: null
      name: dawarich
      namespace: server
    type: Opaque
