---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dawarich
  namespace: server
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC3fMrbnhmHx7c0AOZYSReY1hKijouXiYtP6/iuiEKL5dmkCTEyd5N5rWbVqo5FhgI3j7JqQ15qFZWqoSUfsMwiHRSBQaJOIrGfCkndXyr9I3aUX7sYppPiySbYG/F7m+JtYHtdayFS7fPqyPNqpqOLSfSGpjgehMkerjp00UPm+hBt0P88Yn3YF+ydQIFSMBBHbf5E8hR2VIVjn+t3KVqSf5gVsu9jJXHAaaC0wr9kpjcS3uaOmeF/LHg0pU/wGMNGtQVRbmLNmt3H6HDTZ4hVq3J1KlVx1G9KhZyyuYWw7+VbIOIMVJoa9mjxEnC+NXr7lINgMjF06YU0PNIB0DFyzHk/17mwdMM36zkh3iuZWCqNti97XuKc3aFd+T6hrvERaUSSE9QS93RZynIqkLPe6sK8/uVsGeAzZhyAHmPRGx0UilI8rlRd0ZLfVuyXbBM4i9QCKga4Elw7d/yJlBFTIKFDffq9IUCYbmaYKkhytFyoKMQaFx9Reu1Ui6QRSP1wyETwtcidwb2Gs5EZIpboW0Ak/IcHPsr07L/BBCiAhRp/nsn0eQ9CQJ1TauRFiQDXFKxURXhoTNLnAEirWK+jGlFHhsY//DM8aUeF9kDf2B1GBE5jEymEo8lcjIQWF1iziya8coom3Pzw28imscQOZ/DX8+nwx7l5l6AHZT1+yjGgMDCT1Tt3TdALsIVVDY7jEQvyAfPnX8QZXWeFzb3Z+LCGp+5MW/G44H3vSqKnrw==
  template:
    metadata:
      name: dawarich
      namespace: server
    type: Opaque
