---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dawarich
  namespace: server
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC5vf/jJMisn7k6d5oqnzIT0TM0JYVPKotkNveRp7EhW1gWReGQ03uiMWEnSrQ6JzIVBtJam28TFJjs3AmtPGaObEtRyrRZLAEYPCJS9bbbRhDm01vBLtxruTZRoChQ6kTuy4tjyveCM4keDE1JnVmqLonjvGByNrZGZ28JE7GUKlq9J2mjXtBH6zAlWhijQamjyBJU2Y4f02JsTjjLFfXIoRrtQVcTAcM6KJgw7prON2l8teC3Cv4YAXSNkLrySfFgvHf4HS4EuEtyQsu2quuPF8uYJBw7KlNAVLKbk48GNriQl6bTKO/2MxQXk1IktBRd5gG1M0ctRjwt6SwC2+7SRJ7tZh8ElQfe39XCsiU4e9maoUiejzx/kc8fIqhbH/xsYyXFL3g7nvaZRVgZP/9bYyB/lTPRfWxYGzGfMc48qWNEpnx6g91NI59UChIVNVxdK2VFlPBnO0rjN8kl9bjveGgbV8fNpqdMpUlCVL1A6IUUDj5RSbpd7o57Zou3JTRp2xSnVIiLvkkcNUpLDPkQBNd7QtCzd7ADvVcMwmaIHv2i8O3/BROdHos8fpmPX52DjJG6VGtQpRW02G60AAdndoHb8niLsZFXYGkigoaBE5qykuwbJ93AJtmU1Tpiy0SBzIkUSMYXQCBdAPQOIDhc3oAB4xz4Q6ugJKfBrce6czaAiyHoE1rW7KRtP5RVNYJdb2vtARXu2wKacQtW1ubvHHXufHZ5m3TYSQJKNx3fZA==
  template:
    metadata:
      creationTimestamp: null
      name: dawarich
      namespace: server
    type: Opaque
