#!/bin/bash

kubectl kustomize audiobookshelf && echo "---"
kubectl kustomize bazarr && echo "---"
# kubectl kustomize dawarich && echo "---"
kubectl kustomize ddns && echo "---"
kubectl kustomize errors && echo "---"
kubectl kustomize flaresolverr && echo "---"
kubectl kustomize homeassistant && echo "---"
kubectl kustomize homer && echo "---"
kubectl kustomize jitsi && echo "---"
kubectl kustomize kometa && echo "---"
kubectl kustomize kubernetes-dashboard && echo "---"
kubectl kustomize mealie && echo "---"
kubectl kustomize minecraft && echo "---"
kubectl kustomize nut-exporter && echo "---"
kubectl kustomize ombi && echo "---"
kubectl kustomize peanut && echo "---"
# kubectl kustomize photon && echo "---"
kubectl kustomize plex && echo "---"
kubectl kustomize podcast-dl && echo "---"
kubectl kustomize prowlarr && echo "---"
kubectl kustomize qbittorrent && echo "---"
kubectl kustomize radarr && echo "---"
kubectl kustomize radarr-uhd && echo "---"
kubectl kustomize rclone && echo "---"
kubectl kustomize romm && echo "---"
kubectl kustomize sonarr && echo "---"
kubectl kustomize sonarr-uhd && echo "---"
kubectl kustomize stardew && echo "---"
kubectl kustomize static && echo "---"
kubectl kustomize syncthing && echo "---"
kubectl kustomize tautulli && echo "---"
# kubectl kustomize tdarr && echo "---"
kubectl kustomize tubearchivist && echo "---"
kubectl kustomize yamtrack && echo "---"
