apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-external
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("longhorn.mchill.io")
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
      middlewares:
        - name: forward-auth
          namespace: traefik-external
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-internal
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("longhorn.mchill.lan")
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
      middlewares:
        - name: basic-auth
          namespace: traefik-internal
