kind: Deployment
apiVersion: apps/v1
metadata:
  name: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: plex
          image: ghcr.io/linuxserver/plex:1.41.3
          ports:
            - name: ingress
              containerPort: 32400
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: plex
              mountPath: /config
              subPath: config
            - name: plex
              mountPath: /transcode
              subPath: transcode
            - name: libraries
              mountPath: /data/movies
              subPath: movies/sd
            - name: libraries
              mountPath: /data/movies-requested
              subPath: movies/requested
            - name: libraries
              mountPath: /data/tv
              subPath: tv/sd
            - name: libraries
              mountPath: /data/tv-requested
              subPath: tv/requested
          resources:
            limits:
              cpu: 3
              memory: 2Gi
            requests:
              cpu: 1
              memory: 512Mi
      volumes:
        - name: plex
          hostPath:
            type: Directory
            path: /home/mchill/k8s/plex
        - name: libraries
          persistentVolumeClaim:
            claimName: libraries
