kind: Deployment
apiVersion: apps/v1
metadata:
  name: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 911
      containers:
        - name: plex
          image: ghcr.io/linuxserver/plex:1.41.3
          ports:
            - name: ingress
              containerPort: 32400
            - name: gdm-1
              containerPort: 32410
              protocol: UDP
            - name: gdm-2
              containerPort: 32412
              protocol: UDP
            - name: gdm-3
              containerPort: 32413
              protocol: UDP
            - name: gdm-4
              containerPort: 32414
              protocol: UDP
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: plex
              mountPath: /config
            - name: applications
              mountPath: /transcode
              subPath: plex
            - name: libraries
              mountPath: /data/movies
              subPath: movies/sd
            - name: libraries
              mountPath: /data/movies-requested
              subPath: movies/requested
            - name: libraries
              mountPath: /data/tv
              subPath: tv/sd
            - name: libraries
              mountPath: /data/tv-requested
              subPath: tv/requested
      volumes:
        - name: plex
          hostPath:
            type: Directory
            path: /home/mchill/k8s/plex
        - name: applications
          persistentVolumeClaim:
            claimName: applications
        - name: libraries
          persistentVolumeClaim:
            claimName: libraries
