namespace: server
resources:
  - endpoint.yaml
helmGlobals:
  chartHome: ../../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: remote-unifi
      addSelector: false
      routes:
        - match: Host("unifi.remote.mchill.io")
          scheme: https
