apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - endpoint.yaml
helmGlobals:
  chartHome: ../../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: remote-unifi
      service:
        disableSelector: true
      ingress:
        routes:
          - match: Host("unifi.remote.mchill.io")
            service:
              scheme: https
