namespace: server
transformers:
  - label-transformer.yaml
resources:
  - ../../../overlays/ingress
  - endpoint.yaml
patches:
  - target:
      kind: IngressRoute
    patch: |-
      - op: replace
        path: /spec/routes/0/services/0/scheme
        value: https
