- name: Configure Proxmox
  become: true
  block:
    - name: Remove enterprise repositories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/pve-enterprise.sources
        - /etc/apt/sources.list.d/ceph.sources

    - name: Add PVE no-subscription repository
      ansible.builtin.deb822_repository:
        name: pve-no-subscription
        types: deb
        uris: http://download.proxmox.com/debian/pve
        suites: "{{ ansible_facts.distribution_release }}"
        components: pve-no-subscription
        signed_by: /usr/share/keyrings/proxmox-archive-keyring.gpg
        state: present

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
