apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: radarr
          image: ghcr.io/linuxserver/radarr:5.28.0
          ports:
            - name: ingress
              containerPort: 7878
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: MAX_NAME
              value: "140"
          volumeMounts:
            - name: radarr
              mountPath: /config
            - name: media
              mountPath: /movies
              subPath: movies/sd
            - name: media
              mountPath: /movies-requested
              subPath: movies/requested
            - name: scratch
              mountPath: /trash
              subPath: radarr
            - name: scratch
              mountPath: /data
              subPath: qbittorrent
      volumes:
        - name: radarr
          persistentVolumeClaim:
            claimName: radarr
        - name: scratch
          persistentVolumeClaim:
            claimName: scratch
        - name: media
          persistentVolumeClaim:
            claimName: media
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
