apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: radarr
          image: ghcr.io/linuxserver/radarr:5.28.0
          ports:
            - name: ingress
              containerPort: 7878
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: MAX_NAME
              value: "140"
          volumeMounts:
            - name: radarr
              mountPath: /config
            - name: movies
              mountPath: /movies
              subPath: sd
            - name: movies
              mountPath: /movies-requested
              subPath: requested
            - name: radarr-trash
              mountPath: /trash
            - name: qbittorrent-bulk
              mountPath: /data
      volumes:
        - name: radarr
          persistentVolumeClaim:
            claimName: radarr
        - name: radarr-trash
          persistentVolumeClaim:
            claimName: radarr-trash
        - name: qbittorrent-bulk
          persistentVolumeClaim:
            claimName: qbittorrent-bulk
        - name: movies
          persistentVolumeClaim:
            claimName: movies
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
