---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-manager-webhook-tokens
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBYtgaL+airnKi+y+Z8GOuyqEDDYlS3Klk/xvXCoTjLdCGB+R6zY4dwyJhCwJZjX1BNYV34ns8iOt46I5yTdRu5ZnAKVFhlQ+9WE2XbBekzAm+M5O5Q2d3JGTsSdmGWsMaBOEVhwuYZPH9cgLRfUthMUms+cDV2jpauy1PE5tMvOGGoHqOs30eLKPzURSqNMRRBvfC1jfJJFScWb+fgMR3AwaSdtR9pBIgsYiWhndlPYdrmEVq1a4ZcCh21qVnVK2911NVEKOJqodIEqUhKAxcUDbsdawUUwmhP61P+Pda+4kTb+MAoxL6wKFkv0gXI1RnyxYn8lubRFP1SH7z+FT71rJWFdtq48ZEsxENArmAdguz1A3BV6CcBtWqbGs22S2emgFgr1D/OZ0wa4gGOIWIfvS31915j0SYB4Gfhv+Q3mF5F2EABbuLz1xi0Yg1/IYOkO9II5IQ3m9BNY+RYRtqIiQpYEcvlkxmRsAKJAe3u3JyQVM4inxhRRK2Y/uNWbSRWaeK46MFHeghKSdRgnnt59Umko/SY0g9EqDZ722vtXzmVL6jhrHOf3kPStv+SKo7MGFIvRs0ssT1M/3t4EUx8nOz/yE9QPS4x6/8VxY0L9y/xtBe84h3UfDTJf0b/lNLyiER5lO/HP9e46qVXNQPJiCNnpd6JkhYZ1XirF8j0RY92bzGrysx+WWzAdMIMbtGxzIt0R+XHNZkVIblygMYh21hfuw8JS47x9xhbpIzwFJc+0R+gHWD0
  template:
    metadata:
      name: cert-manager-webhook-tokens
      namespace: cert-manager
    type: Opaque
