kind: Deployment
apiVersion: apps/v1
metadata:
  name: jellyfin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: jellyfin
          image: linuxserver/jellyfin:10.10.7
          ports:
            - name: ingress
              containerPort: 8096
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: JELLYFIN_PublishedServerUrl
              value: https://jellyfin.mchill.io
          volumeMounts:
            - name: jellyfin
              mountPath: /config
              subPath: config
            - name: jellyfin
              mountPath: /cache
              subPath: cache
            - name: applications
              mountPath: /transcode
              subPath: jellyfin
            - name: libraries
              mountPath: /data/movies/sd
              subPath: movies/sd
            - name: libraries
              mountPath: /data/tv/sd
              subPath: tv/sd
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: jellyfin
          persistentVolumeClaim:
            claimName: jellyfin
        - name: applications
          persistentVolumeClaim:
            claimName: applications
        - name: libraries
          persistentVolumeClaim:
            claimName: libraries
