apiVersion: v1
kind: Service
metadata:
  name: jellyfin-lb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.87
spec:
  type: LoadBalancer
  ports:
    - name: ingress
      port: 8096
      targetPort: ingress
