apiVersion: batch/v1
kind: CronJob
metadata:
  name: plex-meta-manager-posters
spec:
  schedule: '@daily'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          securityContext:
            fsGroup: 1000
          restartPolicy: OnFailure
          initContainers:
            - name: render-config
              image: bash:5.2.26
              args:
                - -c
                - |
                  apk add --no-cache gettext rsync
                  envsubst < /config_src/config.yaml > /posters/config/config.yml
                  bash /config/sync.sh
              envFrom:
                - secretRef:
                    name: plex-meta-manager
              volumeMounts:
                - name: plex-meta-manager
                  mountPath: /config
                  subPath: posters
                - name: media
                  mountPath: /data
                  subPath: libraries
                - name: config
                  mountPath: /config_src/config.yaml
                  subPath: config.yaml
                - name: config
                  mountPath: /config/sync.sh
                  subPath: sync.sh
          containers:
            - name: plex-meta-manager
              image: meisnate12/plex-meta-manager:v1.21.0
              args:
                - --run
                - --read-only-config
              env:
                - name: TZ
                  value: America/New_York
              volumeMounts:
                - name: plex-meta-manager
                  mountPath: /config
                  subPath: posters
                - name: media
                  mountPath: /data
                  subPath: libraries
                - name: config
                  mountPath: /config/movies.yml
                  subPath: movies.yml
                - name: config
                  mountPath: /config/extras.yml
                  subPath: extras.yml
                - name: config
                  mountPath: /config/tv.yml
                  subPath: tv.yml
          volumes:
            - name: plex-meta-manager
              persistentVolumeClaim:
                claimName: plex-meta-manager
            - name: media
              persistentVolumeClaim:
                claimName: media
            - name: config
              configMap:
                name: plex-meta-manager-posters
