namespace: server
commonLabels:
  app: minecraft-mattcraft
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
- name: minecraft-mattcraft
  files:
    - ops.json
    - whitelist.json
