kind: Deployment
apiVersion: apps/v1
metadata:
  name: ddns
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ddns
          image: qmcgaw/ddns-updater:v2.4.1
          ports:
            - name: ingress
              containerPort: 8000
          env:
            - name: TZ
              value: America/New_York
            - name: CONFIG
              valueFrom:
                secretKeyRef:
                  name: ddns
                  key: config.json
          volumeMounts:
            - name: ddns
              mountPath: /updater/data
      volumes:
        - name: ddns
          persistentVolumeClaim:
            claimName: ddns
