apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - deployment.yaml
  - sealed-secret.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: ddns
      ingress:
        routes:
          - match: Host("ddns.mchill.io")
  - name: persistence
    valuesInline:
      app: ddns
      size: 128Mi
