apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns
  namespace: server
spec:
  encryptedData:
    config.json: AgA3wmSgj0zgrJbuhe86qa3OQkLejz5SzbJ7JAbfWDFxLKdxcVaTfVMZkiEs4/Nz39OwWWKO+Ou8KbZCWitRju7zeS8L2nXNWo5d+PRyJy8VvWA/0e9VSXM88T9vLueJHeENkK4TNb2QIa7WhFMjnRnZBU6KoFMQzQMhrXDwNEtP35eTTA6MTQsLexS1LTVlh/Pwur0rtlzwltwDjZm7msnSwHM8reW8ro0oFv5/qn5C14eRFXfq/dGUXjONxDn0Qps0ahkcHFxmfW45ftqfm5M39WyNJ0uUB2kzCCkbVst+/MSrYzudjRLQLQ409+D3Qdr0yH9MAP+U4VwFM/sjZYiaJMyMA4CL2/EqhfqF/qOoFXY2YhSLTqkatQAmztZgtmkdV9TfeSd+KZTw/x9nRPxPQo+Lj31efyfcdDSFB9J4yuUPMtZTO7M9Krn/6v5dOqVPc2VT+sUyyGOdjlMQaj1VPA9HrLYlfRT59aBbITVx6jIycirWhC9BW+KYM58Mg9mFonIdxSs3l2NyewOxW2+kl/E2tRDvOribI37fVPuhbDmxNxEzwxYc8rmveDecJzNcnVPNP8HXvByfHxkQ8ocDhFc4YdxtsLX/o1+nBuj6aQykZGyN2GQc74hVANV2VLIM7RJ2o1hZylhx0Z8W0HLjQ8sHv4Uh6jlDBdB3ckDzI2DA7izHePL3s6FmabaIRRIdc19BduJOvcYpjE0L/A4N39V9wfNXqOFY6QmaYwWgtomUrlKdKOWzElkdmlyi6wDgKeUjJxO22ddDqvFmC4u1xGhotPXzbM9UXYCD8sL6+bRxBSKKsPUXtsfm+p34lVKwiuQPg6B/pQvo+5WAvWEIScCvfxa425S4wQ6Zth0BEX51Q1Y2sQAfqKx+pREWz2xOmS5RZdfB30ti8BvU8mA2/gj1QGuLZYro+NgdYWiGHwCpjPssyAw0snXqmxb2eBKMlhAMGVZ2123zXVdPmS9Z1YTGuWYE7r9tMRmdiKlwqtukjMGXa4ab9/sC0PoPkobJJlMx6qf6iFevMR+MUHX7T8MFfMu+6MaWt4sliGxdv7q06WvsRZGJ+LfbRh34FmRjVdWmX6SwiBI4G8tgsAmAnv3/H76CQtdNTpKByPl+UjA+XRMDrcQ+1lTlI9ZH+5buN9U8mZpViwN2ulVRW+JJiYzexUpnZS1G8E1wMPb7/wkuLbx3no8DBm8IL9yC/DZrMQlGxi1rTuzei+s3UYoP/37AbIEh9572ylM2kB9vK2m29kb0r68BHYH8X3sx6Ozv2rL0i1w+ezBYLZjMggfnAOnK7WJ8D2V64v6Nq5SXrTziyI+MqkFHjjU9wa65mFha5JQoNK2hYZDtHiDGH+cgnOtp31JucW1lmQr0AWOM58Ml9CDZ6sQU6UtEyOeAo0rPpZjGzF6b1Sb4GitGfIKzM3p/XlxzVpFVeFOs4XmzuDiuLgi2G4Xc2Up1vcOhNSBiGOSWLHnbDNlAT93Ruk8KQe1NlK8dAML1GWy3JfEyiKNbd5hd6gMD78mo3rj3IgynLJ21SKKxNuLYqomDkhxnzc3LWFEi3svHPVaNiLblMmbSm0FOM6j9L7ERX50bdmP5IKZ/jZINwS4fDiyGAr69qfRLSGxoiHUuWquWzvOpG19b6xecJKoJObb1MXIQd04oVIiKXR0crlcEFlK20ciHbyOWNRmtN1IOSxhK/6gSa8ouN7HNeQe2aUMLPrU+Eju1c8wupDLNqtL9IvsPLs/lqi2K723LKRwPY7TfbtI59Lx2TfShmi/o+CnR+eP1SUp5eXxtPptr9VzVJk2xEZYcVzaWvxdwqXPI334+Z/hX173Ldw3lpg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ddns
      namespace: server
    type: Opaque

