namespace: server
resources:
  - deployment.yaml
  - service.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: radarr
      routes:
        - match: Host("radarr.mchill.io")
  - name: persistence
    valuesInline:
      app: radarr
      size: 2Gi
