kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: errors
spec:
  template:
    spec:
      containers:
        - name: errors
          image: nginx:1.27.4
          ports:
            - name: ingress
              containerPort: 80
          env:
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: errors
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: errors
              mountPath: /usr/share/nginx/html/401.html
              subPath: 401.html
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 0.1
              memory: 128Mi
      volumes:
        - name: errors
          configMap:
            name: errors
