namespace: server
resources:
  - daemon-set.yaml
configMapGenerator:
  - name: errors
    files:
      - index.html
      - 401.html
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: errors
      routes:
        - match: HostRegexp(`{host:.+}`)
          disableForwardAuth: true
          priority: 1
