# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-workflows
      targetRevision: 1.0.16
      helm:
        releaseName: argo
        values: |
          server:
            authModes:
              - server
          controller:
            parallelism: 10
    - repoURL: https://github.com/mchill/home.git
      targetRevision: HEAD
      path: k8s/sources/argo
    - repoURL: https://github.com/mchill/home.git
      targetRevision: HEAD
      path: k8s/helm/charts/ingress
      helm:
        releaseName: argo
        values: |
          app: argo
          service:
            enabled: false
          ingress:
            routes:
              - match: Host(`argo.mchill.io`)
                service:
                  name: argo-argo-workflows-server
                  port: 2746
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
