# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/mchill/home.git
      targetRevision: HEAD
      path: k8s/sources/democratic-csi
    - repoURL: https://democratic-csi.github.io/charts/
      chart: democratic-csi
      targetRevision: 0.15.1
      helm:
        values: |
          csiDriver:
            name: org.democratic-csi.iscsi
          storageClasses:
            - name: truenas-iscsi
              defaultClass: false
              reclaimPolicy: Retain
              volumeBindingMode: Immediate
              allowVolumeExpansion: true
              mountOptions:
                - discard
              parameters:
                fsType: ext4
                csi.storage.k8s.io/node-stage-secret-name: truenas-chap
                csi.storage.k8s.io/node-stage-secret-namespace: democratic-csi
          controller:
            externalSnapshotter:
              enabled: false
            driver:
              image:
                tag: v1.9.5
              extraEnv:
                - name: TRUENAS_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: truenas-api
                      key: TRUENAS_API_KEY
          node:
            driver:
              image:
                tag: v1.9.5
              extraEnv:
                - name: TRUENAS_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: truenas-api
                      key: TRUENAS_API_KEY
          driver:
            config:
              driver: freenas-api-iscsi
              httpConnection:
                protocol: http
                host: truenas.mchill.lan
                port: 80
                apiKey: "${TRUENAS_API_KEY}"
                allowInsecure: true
              zfs:
                datasetParentName: ssdpool/replicated/secure/k8s
                detachedSnapshotsDatasetParentName: ssdpool/replicated/secure/k8s-snaps
                zvolCompression:
                zvolDedup:
                zvolEnableReservation: false
                zvolBlocksize:
              iscsi:
                targetPortal: "truenas.mchill.lan:3260"
                targetPortals: []
                interface:
                nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
                targetGroups:
                  - targetGroupPortalGroup: 1
                    targetGroupInitiatorGroup: 1
                    targetGroupAuthType: CHAP
                    targetGroupAuthGroup: 1
                extentInsecureTpc: true
                extentXenCompat: false
                extentDisablePhysicalBlocksize: true
                extentBlocksize: 512
                extentRpm: "SSD"
                extentAvailThreshold: 0
              _private:
                csi:
                  volume:
                    idTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
