apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argo.yaml
  - ceph-csi-rbd.yaml
  - cert-manager.yaml
  - csi-driver-smb.yaml
  - intel-device-plugins.yaml
  - metallb.yaml
  - shared.yaml
  - traefik.yaml
