# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://helm.traefik.io/traefik
      chart: traefik
      targetRevision: 41.4.0
      helm:
        values: |
          deployment:
            kind: DaemonSet
            additionalVolumes:
              - name: dynamic-config
                emptyDir: {}
            additionalContainers:
              - name: traefik-forward-auth
                image: r1cebank/traefik-forward-auth:multiarch
                ports:
                  - name: auth
                    containerPort: 4181
                env:
                  - name: CONFIG
                    value: /config
                  - name: COOKIE_DOMAIN
                    value: mchill.io
                  - name: AUTH_HOST
                    value: auth.mchill.io
                  - name: WHITELIST
                    value: matthewchill7@gmail.com
                  - name: HTTP_PROXY
                    value: http://pihole.mchill.lan:8888
                  - name: HTTPS_PROXY
                    value: http://pihole.mchill.lan:8888
                  - name: NO_PROXY
                    value: localhost,127.0.0.1
                  - name: SECRET
                    valueFrom:
                      secretKeyRef:
                        name: traefik
                        key: SECRET
                  - name: PROVIDERS_GOOGLE_CLIENT_ID
                    valueFrom:
                      secretKeyRef:
                        name: traefik
                        key: PROVIDERS_GOOGLE_CLIENT_ID
                  - name: PROVIDERS_GOOGLE_CLIENT_SECRET
                    valueFrom:
                      secretKeyRef:
                        name: traefik
                        key: PROVIDERS_GOOGLE_CLIENT_SECRET
              - name: dynamic-config
                image: ghcr.io/kiwigrid/k8s-sidecar:2.8.1
                env:
                  - name: LABEL
                    value: traefik-dynamic-config
                  - name: LABEL_VALUE
                    value: "true"
                  - name: FOLDER
                    value: /etc/traefik/dynamic
                  - name: RESOURCE
                    value: configmap
                  - name: NAMESPACE
                    value: ALL
                volumeMounts:
                  - name: dynamic-config
                    mountPath: /etc/traefik/dynamic
          additionalVolumeMounts:
            - name: dynamic-config
              mountPath: /etc/traefik/dynamic
          accessLog:
            enabled: true
          additionalArguments:
            - --entryPoints.websecure.transport.respondingTimeouts.readTimeout=600
            - --serversTransport.insecureSkipVerify=true
            - --providers.file.directory=/etc/traefik/dynamic
            - --providers.file.watch=true
          api:
            insecure: true
          ports:
            web:
              http:
                redirections:
                  entryPoint:
                    to: websecure
                    scheme: https
          service:
            annotations:
              metallb.universe.tf/loadBalancerIPs: 192.168.1.90
          providers:
            kubernetesCRD:
              enabled: true
              allowCrossNamespace: true
              allowExternalNameServices: true
    - repoURL: https://github.com/mchill/home.git
      targetRevision: HEAD
      path: k8s/sources/traefik
    - repoURL: https://github.com/mchill/home.git
      targetRevision: HEAD
      path: k8s/helm/charts/ingress
      helm:
        values: |
          app: traefik
          service:
            enabled: false
          ingress:
            routes:
              - match: Host(`traefik.mchill.io`)
                service:
                  kind: TraefikService
                  name: api@internal
              - match: Host(`auth.mchill.io`)
                service:
                  name: traefik-clusterip
                  port: 4181
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
