namespace: server
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: minecraft
    files:
      - ops.json
      - whitelist.json
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: persistence
    valuesInline:
      app: minecraft
      size: 4Gi
