apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - deployment.yaml
configMapGenerator:
  - name: minecraft
    files:
      - ops.json
      - whitelist.json
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: minecraft
      ingress:
        enabled: false
      loadBalancer:
        ip: 192.168.1.92
        port: 25565
  - name: persistence
    valuesInline:
      app: minecraft
      size: 4Gi
