namespace: server
resources:
  - deployment.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: tdarr
      ingress:
        routes:
          - match: Host("tdarr.mchill.io")
  - name: persistence
    valuesInline:
      app: tdarr
      size: 2Gi
