namespace: server
resources:
  - deployment.yaml
  - service.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: sonarr
      routes:
        - match: Host("sonarr.mchill.io")
  - name: persistence
    valuesInline:
      app: sonarr
      size: 1Gi
