apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - deployment.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: sonarr
      ingress:
        routes:
          - match: Host("sonarr.mchill.io")
      loadBalancer:
        ip: 192.168.1.85
        port: 80
  - name: persistence
    valuesInline:
      app: sonarr
      size: 1Gi
