---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: server
spec:
  encryptedData:
    .dockerconfigjson: AgCxRvsSuIVKmMUO1qNX3MyqgzhMFkG7L2GrD+jOyM7LXF8LmGflEL1c0H6F3CqlZcpPPc1+eZkuzwUsFXLQSIFRqTr0k8fFBfOglG4ADkOgh3ag/9OirqWCn4qRzeQ5Yw1Y69tvPTv6xpPe+K/qQOsqy/L+oT+/kjBbgN3mhhY/g0qO8neLUcQxGizaYfS+uW8qyYnwzp1F66+zR/hQjGulfHA5AqmkL1fAD1XqfLn0wxcMg7gYNoSlrQ2TvBC91iEtpq2S7FsUrFY70sUNUsvpSJqjf+p4+oMeC5eGYzML+/nTqf87GTASxt2mHo898ecMzB0QzwkITGWO8KogiDnUbLQgWe3fkRvcRrHlFydxGRHSgyl5N7Ns4/TK6kM+gvYF8Sqpn5a/sIc0Hlj3+KTvZ4zwQ32341XixXfqblZPNzsDGVSVLkdmcJAFwkLHWdvbQoqHT4OLfI5KOIT3ZifsFpFwMEf1oR3VXKP1NNTE1+ge1paXihJUIResmZVHRVIFBpBa6ontEfUIjRPfzCIiH1+asMh4q9eVYMNZyJLo4ajcSidy8Kdl/cTNN+sRDY+5EKlWfYXQbIyN86yKFBDQs4P65TtJDKEkQD14psgQcnfzh8S/leqfaG0K4vXEjWNK6Nj7TcBUOyUD7B/G5GtplTO0qnbQE3HQwyHCl695sGCM9soFS3l7zRHvQNP5YRaboRnl+h1R+aDL8UcBspg8q7T+YwE+bYkVSkAPF92atyaziVREEEpzMw0ZiPo+rMkyi0fsb1/dyfO8b0E2ovxcQ8hgUAfs2XOiVvW+qkKkx2ftTzWj3El4LF7dcipAR5tDj0QBG3o7jHDrNkE/oMziZQDBMSTwuFUtjSf707E9+IsIhf+MQH+/cw1Ouc4d83zKCyqdZasYMu1kJ4zE1haRmBdhk/+iwM+8t+z2N4nYaHlO7Z2ZHLGS+vRvzsWjv16/L1VklCloOidd3ohasHRGB+dhxgA=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: server
    type: kubernetes.io/dockerconfigjson
