apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: minio
      endpoint:
        ip: 192.168.1.10
        port: 9001
      ingress:
        routes:
          - match: Host("minio.mchill.io")
