namespace: server
resources:
  - endpoint.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: minio
      addSelector: false
      routes:
        - match: Host("minio.mchill.io")
