apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - endpoint.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: minio
      service:
        disableSelector: true
      ingress:
        routes:
          - match: Host("minio.mchill.io")
