apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configMapGenerator:
  - name: grafana-dashboards
    files:
      - jobs.json
      - volumes.json
      - zvols.json
    options:
      labels:
        grafana_dashboard: "1"
