---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone
  namespace: server
spec:
  encryptedData:
    RCLONE_CONFIG_GDRIVE_CLIENT_ID: AgBG+DP/zCLes6dXlf3+n2CJOIAmrPdzI2yQyCRtTnK/1Yj2OBQeu19AGZ4UdGBQXk6u+5CeBdfQDzkkm8Ys+HbXU/sfHUhqXpe8sFT7vvra1z1tLUGuS5i4F6b7AghQeSHXpzsoCpvksu4LSdNq6/WflyV41hI3a3Wreuq6roOWO/rAwutm/wkwwDkhcPacCjMsp+1wfQ6HioG2Jy9vwRagQNeEx4HKcJ/hcqFpAQrQKUzxJLH3brL2luiUDS4Q3uXUq4PFBoEQZYGqlpHR2/aGURAyu+Ejjp+nCUI6k0MUUbqMmBdlhMKC1Mzh9Zlz1N/SGIHNMmpa2V7JPda/zxW9gwgWJqsSVqPpUeWxp/CX5Spq/+mWUb/zurtFc7F4n/Q4WoCTtV/EAuB9612uBsg9cNe2gP9KZ8pKcs6V1TZZ0VVkGefABLwOTOhMUgW5DVqcB5n/VCWq5hSsmMBpT4/v0YnfuIMviM6GXiwg7/vRZXKYi3MnMgruA2MNScqDgKn9Pax+VI5AO96kr9n1c0cT3ZpnrwSYtI72+IfaiRJr4eAWES5Eg7tKruOXzQ6iV5xVBUmSPiWXdfajvlTE3HqU3rGqe0wi/uX1NkpDVcLkA1nvgA5p+7Q1aaJaypTaEbU3M3mMEZHYnuijnupwfsxGsVIzQzwdpkoSvBLZyDFF9tLEC+UT2MLwM8rHBLJKAXD2GNVbxhufZ93nRDpk0JfCbSIhNdWxwrMprfc6v8FVmpVhgoBwYt9nxb0r+Al3mjn6znA8SYhz00dhT58vZ9MotbDuDRFOfRQ=
    RCLONE_CONFIG_GDRIVE_CLIENT_SECRET: AgApkwmvZG7N3DGj8I6TqGA6qiB05hMlL9Ljo9S9YyF/F4W/zg9/BEGOGTxuq4DUufl+pewQT0iJ+Qv3CytxTbZ+R/FwJ59mOmUw/u9y+mcsOJO60g50AenYNX3RIe8qtFTYpOrgkMXGIvDJpOxDt5WlFJ7UksJqMMw+AQiUJNCosS4ukDuwVBJDQl5lzQdfAjeBY71uGMcBZMw7be2JCsLwfUzMPdG2dWU14zD0BUwbC0De0lr6CMxQaFpiCKveHvp7FYaVyDQueWCdtvgE391WZOZB05eOTG63ov0bbryKBszpwa4E5iQ6e4UGN4Tmm0YZu53LLOsqX56fRd9DWvIkq84xU7BjQ3dO28A07bGAwj8ezN9fGv2nh3/fV99SiT4G2wmpAXYDwsPkjQivuW8G9tOVUbbWZ6dh2fp/w69IYM5JLLUXRryqwPB9JAGr0wG+utncxMVyy4Hd5mRzrvxzWp8zKsxNEqYkb3c1Ogs7WqzSdvcziu4tFbIKbii2GD4xp+GfUBnUS8n/oIdoLi/sDheL4PcNPUdh5jcXZ4bHcywZNcjjz68g4f70bktBH38sdDqxwHkwff0owCEG9oXVx2HTw/JDthxjA491Q9AdIZHYPhtx6gmAUykirweVD6XTte3qP/NPHwK4b+k9UewP/KwQ9NE+hHTTX+uStuyVhtx3ZPehhI576WiGCW4xbsnBZEOUTIBWvthpnK4gEVl3m9ZZZJ2vO69FexLbXMeETc9xtQ==
  template:
    metadata:
      name: rclone
      namespace: server
    type: Opaque
