---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone
  namespace: server
spec:
  encryptedData:
    RCLONE_CONFIG_GDRIVE_CLIENT_ID: AgCLanTpiSIvX+RtDHrCEXPl4uVuueJURQkXILSrUZbJ3k8WdlK92zcge8R2cloJswnD5EBqQiZjHpDQJCobvEOSaxVyasiWKy3dYHbUNtlar+NV9LR0Fiqh9zbITscMtUD2UNhzZrKgzEkfLyc+PXa0JOd0ykM3A28O6yBbM+xIhdLQcWf9g+7qEMx+TLyYhS74DoTq3MLS39ZX8FjbaqaxVfmxMzn3lnXWtDFJHBckjqWNgnrJMg9SuAV5RrkOLaHwAk6HkwtEUCrnRVv1v5AlIZEOrnyuHK7zS8UAJq1bm0wjW3YgreUlPs+WnK1htO1nZdexevLc5EON39jb6EHnHWkKDW7Fds0Ggs2zUwPYEl+XXk5hPgwBjQrPwQkoqng2ipKw406bl5QeNx4L/3sCP7z3qZ37tOUEygSU40iB36pKltQMo/jsnnIea8gAcS3p+qb4cZ2hq/05X3p1dYQgOwbnvlBc7QQuQZNRlwQKJkIKiyQCCGOOduSl1OewQmBaDNSWVpnMThGy8BLSxlvvRUx3D9g9yMx4stZiYbH5IgPUyAI3xvQBJnBN5RaB8RNMYntISnHep6CoxawqO847odAu4hYai0o/nPtiAyh6+xeGywK1wbBvPB0e/UhbVh37+IG77dmUCa/3byKnoxOhmAdqgzB7FeJ5NPktweV92DDhnb/7kRt6OypzO3v60IUbN2k/RiDKSVNVOuq0jc/8H15wbRa/xpX+nZA/tcQmTN/b8vtFN/lcuuQY7+IGSkRXWUwKV4VGUDSlMJB+VzEl2iJx58fT4Zk=
    RCLONE_CONFIG_GDRIVE_CLIENT_SECRET: AgBzpyyxV6aTGnntRdnbrcLTc7u4e0G0XxBWBNw92hgsf6QaH1D1a8obPCAeK84xsk0iBo12LS4qUs0UXi090MDhMn2/DIrdI0Cqz4KOWCGKzNYgNjpx795ZsZ1WKOs5tFpNGCTTWxT3R/Z03L5B3VbXv4HUpmG6zZSn7qgYE6xM0tbLvZd8Tr6vozMjKSGXGbXPx29Ha+y2g6W7XvW92LSgl0YoL2Jq4aLBYh54r6Ro/BSGVIyQ2FFxWn56T8lkXVl3e3u9AuitCsNHFO0IlsWhBK1+/7YFcxS/5eWofc8aZCN8buytiKJJKDScemir/hj1L60o+aZ242JIZd9QJS5RdZ0Hq3Vpwyr9uAVVARi+vPBnp74o1uUHZKjU86xCtpWI7IF73SHK6IkW6f3EG7aw2E/9HY6pNz32iQmDF2cJCYLoMw25BbXHBRiStZikyZW1kMvqYThVhrC1reBtGAClWW9WjrCkrujVUE9v61Ymz8XepHQNsBML0zzMoD1daU61EeZaCbbeBEjoUqjIqRy0SBQbHpLpPp68p06pjaJC8TycVI39H98U3Zy1df7Pon6rtYi9Y8UYVKhjGOoFRJxeKqm+fXu9EJjtZeSVQxd4Tf5Bf0c241a6TvHI1l+9k/VCHACPhV8Dat8D/DyP5IfxG/gzamWni3kgd0XZqA712gj7fVkESpOmJnLWsdkeu64dwg8ktU18VrOsrC8yP9RADmrIkzSroTlr8OUcV+U9vEMgkQ==
  template:
    metadata:
      name: rclone
      namespace: server
    type: Opaque
