---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeassistant-webhook
  namespace: server
spec:
  encryptedData:
    HOMEASSISTANT_WEBHOOK: AgCzxC9R0w68R8Wmnl0vTD+OYztVOZiCmtOijLfuc1CIg3xQhkL9C65FS3r0bDNM2n2J6j80S2hMviMEbVOxVAS6EI/GD3jMtQKTOIrojdHceUEbxlnMqfofi+8H+jbVLf3/FPWP6j9AIc7tSGCJ+KL9N5Px0Cxk5ieQ47kbpFT2ckRJyht2KVSgqZ9EGgOHsWg9jT7ElZdrIHtkHuhsoiRyA2AFXlK5qZkrnPqSlpayFRCVs/14f8CvAI/l9t4FASxVCrW0+0bVehpZA/27BBRk970rcnnGfVf0eXC+utgGA/Q+IOY5mKZzn4SZvTOfRdRNmW1R37xUE4amD55Y2qhVaoOcP29vDtUh4cjFzMACdlDAzBcHh0mGnahjXWNogBNB07sEcdhAhxiPSAg+EXYrSzvW94q0379+XmKfUNXK4ek8DgPefI46tXjdIN3D2A91YA4lin9HHCyCqn3Ce4pOE6XJEmQRfMMFlVMifoavlho/rhQYSRlIeldp8vR0YvVUrIxEp4nlQoyOaXD6wMcizXacefWZNQ8e1sqQd3yyC27u5Orv+0LHqWhRSP3nVRxa2ZkQArH02JNYW1lgQTH8B8LX2kZP1uc+IHAWorbN5OokIUDTMDGKFnzo7+ZTTevKUMcKMpiL7yQ8++MO3g+szK9iRtIr3Db899Z8Hj4uCAvzc4VGgFpKDlf1Htq01u6HWWVH5z5/Ojvt8xMtIflXfVVHMPQx1WsAFlzH3Hl50N6gw+jCZS3e9c17oFbncBV7p9KN7FEJFQw0vfM=
  template:
    metadata:
      name: homeassistant-webhook
      namespace: server
    type: Opaque
