libraries:
  Movies:
    metadata_path:
      - file: config/movies.yml
  Shared Movies:
    metadata_path:
      - file: config/movies.yml
  TV Shows:
    metadata_path:
      - file: config/tv.yml
  Shared TV Shows:
    metadata_path:
      - file: config/tv.yml
settings:
  asset_directory: /config/assets
  create_asset_folders: true
  sync_mode: sync
  minimum_items: 2
  default_collection_order: release
  tvdb_language: eng
  verify_ssl: true
plex:
  url: http://plex.server.svc.cluster.local.:32400
  token: $PLEX_TOKEN
tmdb:
  apikey: $TMDB_API_KEY
  language: en
