collections:
  Marvel Collection:
    plex_search:
      type: movies
      any:
        title.is:
          - "Iron Man"
          - "The Incredible Hulk"
          - "Iron Man 2"
          - "Thor"
          - "Captain America: The First Avenger"
          - "The Avengers"
          - "Iron Man 3"
          - "Thor: The Dark World"
          - "Captain America: The Winter Soldier"
          - "Guardians of the Galaxy"
          - "Avengers: Age of Ultron"
          - "Ant-Man"
          - "Captain America: Civil War"
          - "Doctor Strange"
          - "Guardians of the Galaxy Vol. 2"
          - "Spider-Man: Homecoming"
          - "Thor: Ragnarok"
          - "Black Panther"
          - "Avengers: Infinity War"
          - "Ant-Man and the Wasp"
          - "Captain Marvel"
          - "Avengers: Endgame"
          - "Spider-Man: Far From Home"
          - "Black Widow"
          - "Shang-Chi and the Legend of the Ten Rings"
          - "Eternals"
          - "Spider-Man: No Way Home"
          - "Doctor Strange in the Multiverse of Madness"
          - "Thor: Love and Thunder"
          - "Black Panther: Wakanda Forever"
          - "Ant-Man and the Wasp: Quantumania"
          - "Guardians of the Galaxy Vol. 3"
          - "The Marvels"
  Pixar Collection:
    plex_search:
      type: movies
      any:
        title.is:
          - "Toy Story"
          - "A Bug's Life"
          - "Toy Story 2"
          - "Finding Nemo"
          - "The Incredibles"
          - "Cars"
          - "Ratatouille"
          - "WALL·E"
          - "Up"
          - "Toy Story 3"
          - "Cars 2"
          - "Brave"
          - "Monsters University"
          - "Inside Out"
          - "The Good Dinosaur"
          - "Finding Dory"
          - "Cars 3"
          - "Coco"
          - "Incredibles 2"
          - "Toy Story 4"
          - "Onward"
          - "Soul"
          - "Luca"
          - "Turning Red"
          - "Lightyear"
        title:
          - "Monsters Inc."
  Scooby-Doo Animated Collection:
    plex_search:
      type: movies
      all:
        title: "Scooby"
        title.isnot:
          - "Scooby-Doo"
          - "Scooby-Doo 2: Monsters Unleashed"
