namespace: server
transformers:
  - label-transformer.yaml
resources:
  - ../../overlays/ingress
  - endpoint.yaml
patches:
  - target:
      kind: Service
    patch: |-
      - op: add
        path: /spec/ports/-
        value:
          name: ssh
          port: 22
