{{- if eq (include "persistence.type" .) "smb" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.app }}"
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ include "persistence.size" . }}
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0775
    - file_mode=0664
    - uid=1000
    - gid=1000
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "{{ include "persistence.source" . }}##{{ .Values.app }}"
    volumeAttributes:
      source: "{{ include "persistence.source" . }}"
    nodeStageSecretRef:
      name: truenas-credentials
      namespace: server
{{- end }}
