apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.app }}"
spec:
{{- if eq (include "persistence.type" .) "smb" }}
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: "{{ .Values.app }}"
{{- else }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ include "persistence.storageClass" . }}
{{- end }}
  resources:
    requests:
      storage: {{ include "persistence.size" . }}
