apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mchill-io
spec:
  commonName: mchill.io
  secretName: mchill-io-tls
  dnsNames:
    - mchill.io
    - "*.mchill.io"
    - "*.remote.mchill.io"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
