deployment:
  kind: DaemonSet
  additionalContainers:
    - name: traefik-forward-auth
      image: r1cebank/traefik-forward-auth:multiarch
      ports:
        - name: auth
          containerPort: 4181
      env:
        - name: CONFIG
          value: /config
        - name: COOKIE_DOMAIN
          value: mchill.io
        - name: AUTH_HOST
          value: auth.mchill.io
        - name: WHITELIST
          value: matthewchill7@gmail.com
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: traefik
              key: SECRET
        - name: PROVIDERS_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: traefik
              key: PROVIDERS_GOOGLE_CLIENT_ID
        - name: PROVIDERS_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: traefik
              key: PROVIDERS_GOOGLE_CLIENT_SECRET
      volumeMounts:
        - name: traefik-forward-auth
          mountPath: /config
          subPath: traefik-forward-auth.ini
  additionalVolumes:
    - name: traefik-forward-auth
      configMap:
        name: traefik-forward-auth
ingressRoute:
  dashboard:
    enabled: false
logs:
  access:
    enabled: true
globalArguments: []
additionalArguments:
  - --api.insecure=true
  - --serversTransport.insecureSkipVerify=true
  - --metrics.prometheus
ports:
  web:
    port: 8000
    exposedPort: 80
    redirectTo:
      port: websecure
  websecure:
    port: 8443
    exposedPort: 443
    tls:
      enabled: true
service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.90
providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    ingressClass: traefik
  file:
    enabled: true
    content: |-
      http:
        services:
          ceph:
            loadBalancer:
              sticky:
                cookie:
                  name: ceph
                  secure: true
                  httpOnly: true
              healthCheck:
                interval: 5s
                timeout: 1s
              servers:
                - url: http://192.168.1.30:8080
                - url: http://192.168.1.31:8080
                - url: http://192.168.1.32:8080
