- name: Configure Proxmox Hosts
  hosts: proxmox_hosts
  roles:
    - proxmox
    - pve_cluster
    - oh_my_zsh
    - timezone
    - lvm_storage
    - nfs_storage
    - etcd_storage
    - gpu_passthrough
