- name: Uninstall k3s
  hosts: all
  tasks:
    - name: Modify killall script
      become: true
      ansible.builtin.replace:
        path: /usr/local/bin/k3s-killall.sh
        regexp: 'umount "'
        replace: 'umount -l "'

    - name: Kill services
      ansible.builtin.shell: k3s-killall.sh

    - name: Uninstall k3s
      ansible.builtin.shell: k3s-uninstall.sh || k3s-agent-uninstall.sh

    - name: Reboot to prune all orphaned processes
      become: true
      ansible.builtin.reboot:

- name: Configure master
  hosts: master
  tasks:
    - name: Create k3s directory
      become: true
      ansible.builtin.file:
        path: /etc/rancher/k3s
        state: directory
        recurse: true

    - name: Copy config file
      become: true
      ansible.builtin.template:
        src: ../templates/k3s-config.j2
        dest: /etc/rancher/k3s/config.yaml
        mode: '0644'

    - name: Install k3s
      ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=v1.28 sh -s -

    - name: Set kube context
      become: true
      ansible.builtin.shell: kubectl config set-context --current --namespace=server

    - name: Update GitHub secret
      run_once: true
      environment:
        GITHUB_TOKEN: '{{ GITHUB_TOKEN }}'
      ansible.builtin.shell: |
        sed '/server:/s/.*/    server: https:\/\/mchill.io:6443/' ~/.kube/config | tee ~/.kube/config.ext
        gh secret -R mchill/home set KUBECONFIG --body "$(base64 ~/.kube/config.ext)"

    - name: Taint node
      become: true
      ansible.builtin.shell: kubectl taint nodes raspberrypi-1 node-role.kubernetes.io/master=true:NoSchedule

- name: Configure agents
  hosts: all:!master
  tasks:
    - name: Create k3s directory
      become: true
      ansible.builtin.file:
        path: /etc/rancher/k3s
        state: directory
        recurse: true

    - name: Copy config file
      become: true
      ansible.builtin.template:
        src: ../templates/k3s-agent-config.j2
        dest: /etc/rancher/k3s/config.yaml
        mode: '0644'

    - name: Install k3s
      ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=v1.28 K3S_URL=https://{{ hostvars["raspberrypi-1"].ansible_host }}:6443 sh -
