---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud
  namespace: server
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA6nnhJsRZJHVNFb9Pimiav5uvSR01acoKMNLCid7jVudYUeFUWUtMmO67dJbFIrtmnG3uwDfPjq2hDchZNa0yHfSuLl08LPpIRWTf37DRQQimqyit0+vSIDNO7UHucp6kmZO9BD/BWG3P327+srjMrjEPkSPvlkjaDbo2yMPeIHlakD6VU02XzwPhJXMNT7q3wxbpraPs2EKgxLmdjndHNhvOd2l/AZVpi0pdroEnscUi5FKWOTlOEMquEY2W19XcYh4vToIO16e74UKGK2dPN+3NF4K127d/ZX13o4la7wyRB/hrt9ISUQ4Uk08nK7NCh4GSL3n+C/F5ymaMUgBBzGJEhG2SrbYTuhLconPp6XVDft2h9KCdxq/uWSdNDNhDMI9+nJW21y4MFEsoaX16vWkT7UHnoyBIX924vHKdA0V/EteIiLmVLi89CTdGc6ohPLlKgVU6MODh0mL76qEJ2vYNLSwekLphhDqJgPCnUeLwCDO6bFzs93lvLWI3WWZq2jpN5Ho7ipIdZdnYCW3QYCgsLW3LTR5v3QcG3+prDCm1rARFv6WtVl24gju1ySbcXgDfwgYK4xbPEv74bS7RkGRpni0h1izY6Hi+p8KAAYeS251DsS9VnlrdKV5obiryvH5G+9Cbl19vtydMzZmMO5L+0zhe7lJM0GtXszWzD470bj1ixrMBEiRLrVRTpn+v0FelKUReo2UBuagXzrrGtbqg2/WXEXw475ZU7ZU4hQQ==
  template:
    metadata:
      name: nextcloud
      namespace: server
    type: Opaque
