---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud
  namespace: server
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAfwDLZEcRf293U+g/pnV2fDhOtjvkJHiuQH4nznpk1M1ukMS5+a9ibh4zy4qvulKb5pNxFtcdmxS3+IOBsjBaOnCS4hpA6oWXGIe3oURLnfsb290Zp88q2vdNkGOhIKWn1eg5XgErzEU873aJ/TnroqfiHXdSMaKU+gsaxS7JxmFRoDgbitus5H2ty8b5tt6VskBfOpGp8dHGTYaWKL4tyUoeWFdx8W247OqLfU0oXeBa8kyhVrtrV6VaTJhInUdC4/Rj8LnF2nXpqopMNx9bvANUfh3BOhhHzUdVe4Ha1HG0fmDNRcxY3CfAtUnwQykWHafxcxSjGFT0MHIn2RMywNuteCS9BsvAb1h3w9Ei+8p7NSCsRUOkR15mckEvXd+hEZmsbb2lqEauZpolOEr0MT4ZTCrkD5yVlOOtuNw6GnqiJRTc8Pz6gqTT/l+OfjSZG0Md5P4jEr3t3yF+XcNvYCyYM64ocMqDhhtFT1xuMaiOl3R41zPQjkgu9WRqjDlDNgwOTYG+jQI0O4wUiCBZpzfD7zyOmoEGS6Syc3MRfTooNCarUgK0Mo1xcKxReTtym5iiClA+p4KAsAk447FHcTRt0n1vGSr9/vTCsMsAGRVFynR9tfrjjIjTxLtkCo8prk84H27CBvzI6IcIKBGkceSOXI0RWNYIUGvC4ne7PBlFaod2GBigWNa4f3UcwRko1CDoz/eMNENf2TRJI7d4drU7fGQi26ZqzGMdQYnbgOA==
  template:
    metadata:
      name: nextcloud
      namespace: server
    type: Opaque
