apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - deployment.yaml
  - sealed-secret.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: stardew
      ingress:
        routes:
          - match: Host("stardew.mchill.io")
            disableForwardAuth: true
      loadBalancer:
        ip: 192.168.1.86
        port: 24642
        targetPort: stardew
        protocol: UDP
  - name: persistence
    valuesInline:
      app: stardew
      size: 128Mi
