---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stardew
  namespace: server
spec:
  encryptedData:
    VNC_PASSWORD: AgDRd2zx6cwdPD5tlhnVo0P7XZi7PHeDuW8n0k2uYwoEPDfcmrwXBHx1xQMJ13X7iFqETLIhTpGbWyF7+KDUIRhqra9Wp0UjeqQZzEPe4z+4o/UDCKrUnLymU59Mlg0y0Svuweiey/oAsJY2TWVmNsk5TOLg2fiiqOnldL1x9JIrchZV/KsSg3Z7MlnKER/7tijOE1NBXuSRPTGebLu3aggzYjhqXyoHBctdrfjTSESj544kUHoR53THgsLxHLF2im6MrLg4faDKckmxwKFY7/WL1P/AGGyA0qUQoMQxM8BfuXR09YrZj8hXPDe6/IM2l3rdF+BbffUCsm7VxytbeQdg06BR4ZdWRrY+RaknpqVJ+2gPZcdcrAfYnBC5NCitp+aqCY6QWuVTbu5viuaVPB+LZ5XoxGAy9CCqgbsWQEWO2R60u2HITleex45gbfZejlUkENofo2XO8QHKuzvizRfx2atUSVB/Dp9CzhoC8eSUiDlL2+TurtC9qP8kLA0NnpdRWhrUp6Fj2d5tdIuAI7WFJItDuDtsKuuf/HCUSA7uSggAHnGIpzQnUb0V5jjFCTjgRCe0zArjHfi6FNmAoHyZOqHPHmMoPDnKDfK252ZqKLk875Zof8nqFWMQgU6SiuGoLoV8LuJM/2B/ctfVlHNeHAGHvYa7wqy/lAlkNEOc8K1PEIjIQV8OlZj+YJ//ZYVYgoKQFcOVF3NNpM6MnXCqAMjdXa2pJjNaCrGqX7MeHvk=
  template:
    metadata:
      name: stardew
      namespace: server
    type: Opaque
