---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stardew
  namespace: server
spec:
  encryptedData:
    VNC_PASSWORD: AgBAREtyDunPjtZyRG1pW5ez+o1hlwrrX3+lPzo9pXXWLymj3xSkOblVy9YVULw6jfInLTQfMtzvwxRGppWKx58ufxmoOP1qfL9LMlny8L3r+iM2dsVJgrfl/Ul01WzIKZEmyQcmqCI3LMRBSaVg3p/MrXq1UPUxG3Th4dMCAQzyJX1mdsPoxguMI6h+PlPYxQVBXuq9JiXVyQXpkaX9cNnMnL2wpK5K70YKCiXXkS6qW28U+ki0HanIdKEZiSP5jp5dAARtQ68map1rGOqpLzHhBoVcZEqW2sxPz2vzpTq/w0hPCMTvJ+8h0AZstvm7IDqxCcaPBjZxWuJi7gOw9E97GbGFZiJH/X4cTM7gc1i6aslIgB5AQrdNvOjPtUaftqLtk4t6cm8ge8xxQOGDgEnfDZO53Lx6W5ffCHqqRGAE51qur6cT1mS8sq5XkmHlxUZ9cv1BWc+FAAU7u1tVScXjOUR7Ne00F/Kcqj886B6B4outv2lQNwR5qVhqBYfE1xPzuWKj1QhrDGixXmv/4fERud7ph8lP0iKlcooe52RLHlBLiHbVWc7kPHZZEIcdJUkIdUWKPAlQBcI6IH+vhp3ouVcoBeoweu9qDv3TK/UHXpwBczmFhKDxT4wUyzjykVRG2utQ7CJ5QhnhOgWP063jokjpxYz+pefrCEqlP6U0//D7Os9NLTbjGV1rPEslTAfU+kD8Yolcuv45ENjUW4gU0Vx5mX1/ZZfQntI9cvhfGgA=
  template:
    metadata:
      name: stardew
      namespace: server
    type: Opaque
