apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  selector:
    matchLabels:
      app: bazarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: bazarr
          image: ghcr.io/linuxserver/bazarr:1.6.0
          ports:
            - name: ingress
              containerPort: 6767
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: bazarr
              mountPath: /config
            - name: shows
              mountPath: /tv
              subPath: sd
            - name: movies
              mountPath: /movies
              subPath: sd
      volumes:
        - name: bazarr
          persistentVolumeClaim:
            claimName: bazarr
        - name: shows
          persistentVolumeClaim:
            claimName: shows
        - name: movies
          persistentVolumeClaim:
            claimName: movies
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
