---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: static
  namespace: server
spec:
  encryptedData:
    users: AgDGWNG/1VbEcocdBU+YIn/LogLFTd+M4iZorxCy6ezPPwlq+LrCSBqr0S8YAKfFfR7txMG1h9EpRE4qa9NrmlKgOCNFc5f3zuzSXbEY2lAzlBKWsalvh6cIqSM90syf2lRYcgsYg/f78Jxi0DwjK3JtE21FjTtAjpz7Ch10pEIYzKMp4b63cIHWxzVonzuw8kIRVAnXupBPvI0rBbJa5o/+iOcreXU0WsBvqg8CDrjGOPc/Ws2Dk9ISzUE/pCfj5zgRl0mUR+za2kZohxfnmVTxMqZrz5UXkp3X5JLHiyipQjU8ohV57/PtJVHovaLuSEYm91xjGkgc66B9f6CbkbfhrDfIrqtToMWZ62SCmJisHLmXzfroMg4x/BGUuTUXqqUHHfMU/r00hnrn8TiWoMyOJSosvokXjr0PT/TOneEQvYcweixfogOh9sOuvfU32bO88bLKdll2IkLFDEKI/pQkCOmKotKhG6eKiPp5iSSmMNZ0n+t48TW3PSv6YGnEAivL3Glv3SVUWBoOiPc0PHba+9zpRFRlG+3yRIu44pBNNdWoGkUlQ99fR/+piXxCXghWG3lKpT/9LRH2V/drltzKZerrSagkjr0jVn/VX3V2SJkmmVvdlT9jpO4S31roJpCF8w22EXnRwSs3v2WZg1wrg/SLAfEwZVGB/K+ktxn17DyImbi2wqA0ssD5m7g8iNqIJG5QLUjQGIdUJaZ7B917LrUGL3rieVz+bzXqFkCPkX4YjHTRTjEMIuw48hI=
  template:
    metadata:
      name: static
      namespace: server
    type: Opaque
