kind: Deployment
apiVersion: apps/v1
metadata:
  name: photoprism
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: photoprism
          image: photoprism/photoprism:250707
          ports:
            - name: ingress
              containerPort: 2342
          env:
            - name: PHOTOPRISM_UID
              value: "1000"
            - name: PHOTOPRISM_GID
              value: "1000"
            - name: PHOTOPRISM_SITE_URL
              value: https://photoprism.mchill.io
            - name: PHOTOPRISM_DISABLE_TLS
              value: "true"
            - name: PHOTOPRISM_DATABASE_DRIVER
              value: mysql
            - name: PHOTOPRISM_DATABASE_SERVER
              value: localhost:3306
            - name: PHOTOPRISM_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: photoprism
                  key: MARIADB_PASSWORD
          volumeMounts:
            - name: photoprism
              mountPath: /photoprism/storage
              subPath: storage
            - name: libraries
              mountPath: /photoprism/originals
              subPath: photos
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 256Mi
        - name: db
          image: mariadb:11.8.3
          env:
            - name: MARIADB_DATABASE
              value: photoprism
            - name: MARIADB_USER
              value: photoprism
          envFrom:
            - secretRef:
                name: photoprism
          volumeMounts:
            - name: photoprism
              mountPath: /var/lib/mysql
              subPath: database
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 512Mi
      volumes:
        - name: photoprism
          persistentVolumeClaim:
            claimName: photoprism
        - name: libraries
          persistentVolumeClaim:
            claimName: libraries
