apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: photoprism
  namespace: server
spec:
  encryptedData:
    MARIADB_PASSWORD: AgBkaE6+YeXyd44MAHK2lqawGNVv7ZmM8GexdTVec4jO/+iGjHPSgs1BGIY+xhxSCB1LXXjfmdT6LtszfzCot2p4nch0szdYwdrJ2Nc90TGHN0z3vuUlBOginZgCg/SyVOruK+t5C6iVoOXWyB5xpzrJzs/wK3G2cO8acVOv778CgWq2nF4wXcIGPqZLiKZOPHcEY6BVTH8TuGIquS3zzX2hgiclr2P9/2h28JK0I6OZSlAPNOYNPqY7qeNH2vVT5FqyW6KXf5MTEyGnSeWfry0lQ3HgszqwiX+aEdMsesEADr1c6knwaFH3v4yK71zBaO4C1WwmMmONQSDw6jOXhLNPTov+wLJjIq5JI+C/0yl6dotpTuX50gITkR5h+9ZWD3KhuO2sBCkyhQI1gPtweNrQLo28HQTqISOoASa3y+ap85JP15ILt8PAwSE/AgxWWXq/wGNVURcTSNPkHZMIkJPRaaOETvnBEKR/P7YyCD7pdpp4hBxfdHoC0hcjhuzCG0mYufLJ9VcQkcW/YcuG1GSp0OUGOtxsnut0gFbdZsLkxFAGa2teC12FpZLRmmLVkyEFI9G3CQ+UpEoBicU6Rmzx1gwHMmEkgWnp/eBcin1WYORjOacyF/iiXI8ygG3ytgujyl5uSKNgDTP22zerlc0xZQqFf0W9VZDf2pLOLs27MkI5kl6Nospd7iWAWWgpJvQs+kuPyy/dzrBkpjjt6DEsmLZ5nsfInSxe4kRWywlm2A==
    MARIADB_ROOT_PASSWORD: AgAfDL/bvzStRLSsVpM7SfWGgYGu8HNP2ASGUgHcNexRDTcbVDEf1u3oyBX+EL/lMjeBjQxZm88+KI7Xvm7m34r2vSAUOn1RZBXPnauGBkEOx3oNS2mF3opDOldHAMB+fYCPLEVuuXbdlj+DCBCsK8k/u/uQfvHi0cV+329armTZ6JMcHL81vq8Q2ywyux6JJcLm8Sfc5kggV88ItPjaHnRaijj7ZrF/+Ks/SGjACL49nFWUyE6Zmo14bP5OhzXqKXaopt4MFnksp+woWN8wsHPK5Xl1DPtThEa9+5uze9LJqIQmQA4eJ+qG+oYzb+daYUJVBlkSu4kx/VSbJBz1/hGZTbGD/z3qKuByUKIwWxs4LkYc016o9vAYTSyOriGiwuBONbXprMzPye3We5aOr1nSoPCCzJrAKb5tSXeB39xhPhJVRgqk0SZitBwCQLjn0wGb8hZKpyrvf2I3fbi8pzqb/rS3ew/gI1dAnIbYhpzvs22D96eZU3kn36UK5VEt15cgaierzKOaOznUWTOkMaXJrLTor32CvXkhAUdaR1lJJ/BEPcimNPyuM13O8PmQu2tviA4ah5HUrY5NAmbZkrwj1aD3u25zEebTei1t/BG5Uhh+HndnBkZPcDymmCFcCB0fYYDoSsxnzgcWrnEXyfJgLGrTX9+qwzr2ukenwBorvK8Q0merDRxMPc9frqdeOoD+E2mTV9W7YS0lTmfxX5chHJD8HZQUcBWO5ZslltrhDA==
  template:
    metadata:
      creationTimestamp: null
      name: photoprism
      namespace: server
    type: Opaque

