apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
helmGlobals:
  chartHome: ../../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: remote-nas
      endpoint:
        ip: 192.168.121.10
        port: 5000
      ingress:
        routes:
          - match: Host("nas.remote.mchill.io")
