namespace: server
resources:
  - endpoint.yaml
helmGlobals:
  chartHome: ../../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: remote-nas
      service:
        disableSelector: true
      ingress:
        routes:
          - match: Host("nas.remote.mchill.io")
