apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: sonarr
          image: ghcr.io/linuxserver/sonarr:4.0.19
          ports:
            - name: ingress
              containerPort: 8989
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: MAX_NAME
              value: "140"
          volumeMounts:
            - name: sonarr
              mountPath: /config
            - name: shows
              mountPath: /tv
              subPath: sd
            - name: shows
              mountPath: /tv-requested
              subPath: requested
            - name: sonarr-trash
              mountPath: /trash
            - name: qbittorrent-bulk
              mountPath: /data
      volumes:
        - name: sonarr
          persistentVolumeClaim:
            claimName: sonarr
        - name: sonarr-trash
          persistentVolumeClaim:
            claimName: sonarr-trash
        - name: qbittorrent-bulk
          persistentVolumeClaim:
            claimName: qbittorrent-bulk
        - name: shows
          persistentVolumeClaim:
            claimName: shows
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
