apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: unifi
          image: lscr.io/linuxserver/unifi-network-application:8.1.127
          ports:
            - name: ingress
              containerPort: 8443
            - name: stun
              containerPort: 3478
              protocol: UDP
            - name: discovery
              containerPort: 10001
              protocol: UDP
            - name: comm
              containerPort: 8080
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: MONGO_USER
              value: unifi
            - name: MONGO_PASS
              value: unifi
            - name: MONGO_HOST
              value: localhost
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DBNAME
              value: unifi
          volumeMounts:
            - name: unifi
              mountPath: /config
              subPath: unifi
        - name: mongo
          image: mongo:4.4.18
          ports:
            - name: mongo
              containerPort: 27017
          env:
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: unifi
              mountPath: /data/db
              subPath: mongo
            - name: config
              mountPath: /docker-entrypoint-initdb.d/init-mongo.js
              subPath: init-mongo.js
      volumes:
        - name: unifi
          persistentVolumeClaim:
            claimName: unifi
        - name: config
          configMap:
            name: unifi
