namespace: server
commonLabels:
  app: unifi
  subdomain: unifi
resources:
  - ../../overlays/ingress
  - ../../overlays/persistence
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: unifi
    files:
      - init-mongo.js
patches:
  - target:
      kind: IngressRoute
    patch: |-
      - op: replace
        path: /spec/routes/0/services/0/scheme
        value: https
