apiVersion: v1
kind: Service
metadata:
  name: pihole-lb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.249
spec:
  type: LoadBalancer
  ports:
    - name: ingress
      port: 80
      targetPort: ingress
    - name: https
      port: 443
      targetPort: https
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
