apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa-permissions
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          securityContext:
            fsGroup: 1000
          restartPolicy: OnFailure
          initContainers:
            - name: render-config
              image: bash:5.2.37
              args:
                - -c
                - |
                  apk add --no-cache curl gettext
                  envsubst < /config_src/config.yaml > /config/config.yml
                  curl -X PUT "http://plex.server.svc.cluster.local.:80/library/sections/1/all?type=18&label%5B0%5D.tag.tag=Matthew&X-Plex-Token=$PLEX_TOKEN"
                  curl -X PUT "http://plex.server.svc.cluster.local.:80/library/sections/2/all?type=18&label%5B0%5D.tag.tag=Matthew&X-Plex-Token=$PLEX_TOKEN"
              envFrom:
                - secretRef:
                    name: kometa
              volumeMounts:
                - name: kometa
                  mountPath: /config
                  subPath: permissions
                - name: config
                  mountPath: /config_src/config.yaml
                  subPath: config.yaml
              resources:
                limits:
                  memory: 128Mi
                requests:
                  cpu: 0.1
                  memory: 128Mi
          containers:
            - name: kometa
              image: kometateam/kometa:v2.1.0
              args:
                - --run
                - --read-only-config
              env:
                - name: TZ
                  value: America/New_York
              volumeMounts:
                - name: kometa
                  mountPath: /config
                  subPath: permissions
                - name: config
                  mountPath: /config/movies.yml
                  subPath: movies.yml
                - name: config
                  mountPath: /config/extras.yml
                  subPath: extras.yml
                - name: config
                  mountPath: /config/tv.yml
                  subPath: tv.yml
              resources:
                limits:
                  memory: 512Mi
                requests:
                  cpu: 0.5
                  memory: 512Mi
          volumes:
            - name: kometa
              persistentVolumeClaim:
                claimName: kometa
            - name: config
              configMap:
                name: kometa-permissions
