namespace: server
commonLabels:
  app: kometa-permissions
resources:
  - cron-job.yaml
configMapGenerator:
  - name: kometa-permissions
    files:
      - config/config.yaml
      - config/movies.yml
      - config/tv.yml
