kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: transmission
          image: haugene/transmission-openvpn:4.3
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - name: ingress
              containerPort: 9091
          env:
            - name: TZ
              value: America/New_York
            - name: OPENVPN_PROVIDER
              value: MULLVAD
            - name: OPENVPN_CONFIG
              value: us_rag
            - name: OPENVPN_OPTS
              value: --mute-replay-warnings
            - name: TRANSMISSION_PEER_PORT
              value: "56002"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: LOCAL_NETWORK
              value: 10.0.0.0/8
          envFrom:
            - secretRef:
                name: transmission
          livenessProbe:
            httpGet:
              path: /transmission/web/
              port: ingress
            initialDelaySeconds: 60
            periodSeconds: 60
          volumeMounts:
            - name: transmission
              mountPath: /config/transmission-home
            - name: media
              mountPath: /data
              subPath: transmission
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.5
              memory: 512Mi
      volumes:
        - name: transmission
          persistentVolumeClaim:
            claimName: transmission
        - name: media
          persistentVolumeClaim:
            claimName: media
