apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission
  namespace: server
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgB5E7HkrRejrR7PEKnnOGoXnzeezqTQJZVhhUS3oa6H8TBwOfu58zYwEOIwOxD3DrNJD+LBtNDio/FodE5Oz/k0+U8IcMu6/MB7drP6qMKUGBIEWUs6SqXQxhysAAn8tM6+ZYkBBd321s1X39L0KEV5HapH2nimaFff9lMJRa6lj9XmbSwsvssw9Tew+wvcG1WpLX/M7G+Lngwg4i7w1upPQE4uBQQeY3mFfw0YKxM1W3WebYDP4jQLeBbL05qStUnMyCprVxc0dv0UBNijNg/43GiOwjUmvats3rE6Iv38wzs1Regpk0Nx3SNGfspmr0tyMATm3/jLu7Mjr+kNlRd2k/VnwWVpcwt7aE+QB9OrBBQ2DG2kA1PwkPWDAkUmpQ9kpTugLcY6uX7aOPZVHN8VWFtpIlgUt5O4QBbPB4cfX1LxjvqR/Zxjd8drHhn8cd/X7YHPr8MhZ7ha8KVqdeiVxJjeaTngWUuMODayVPMtuKo18B5ntX1XC8N8Encpapt6ul2tYCKe7R/vLFBT5wdv1fBS3/lRKuXXNhlojWoCoEIeLXBJxS3nC2lkiXsyvC9Hy8hanF84hI2dI/MBCkW+cjbNXq3Sj80Zcbc2/FbkNJo82GwXY7GSbypEAt3ZWF3Yja5Txh/IFpUpD8lx1rY5qVbpyvUmtqpGfG39TIjUzQU00zIn/7RQhD4WkT7pnx2OpeXVF5pyRWuUVLtVlK6q
    OPENVPN_USERNAME: AgBR0An5SSESvPZErnOaBwPPvpIxKoasQcz+qUyYt+Wl0y0RnTZ9rF6Ek3tvizzPRhxUVdNdpUxofHrjgphUmvlHERGAPVAIK3AbxtHCe4/3pcFZA6Rw9aphs9blJ2V17ytzlkXF94CVx8KB5g/Toj5Lv5iQXuSyHiPT0Ts13lJz3uj1JAufWxE2Nv3cHbaFx+4OpaRZQPHtrqa+z1sHt7h0pdENSSyVfIOHFpYvIBNEK2U4nw8GILyhyCMCYuussntyur/g5G17rrnhmCWHWF355XnzedrOZqhoxbmVBO4yE54/uRSyCK4s5TRFIQC4ErmquUbBLdmZYt1xoPBwHY/A7bXosCE5EPzBm3bBuCO0nY/BiqJOtspQyE2QP4yZX9K/8kvl+Wwvbxcur8mczcSQGNNPszBkQseMraZM7xORnWCNhyogckdWLd3vtA97XmiP+96lo2y4299iO5gaeM5WYn8DGjzNIhndj7cvfE6OitsekYxTjPTifnlFmFQja3GF0GPOpHBVW8MdNssot0kB8yIWmENm7fmcP+yXrOuDiIw1yE9ZVqfBWNjtMd1rdVPolnJikUAasrQ377FuMwIWAikyv5sw9NxsjKPS0CWr16Gwk1JPQlA6qdBNYCQOzRwBtT9zL/pbarrHn8748z0CxipRwsItQ7NpnaE+B8JC8erCrSGqw8Ndp08QXC4EJim3aaUoBkGZpYvxk+e+Grjv
  template:
    metadata:
      creationTimestamp: null
      name: transmission
      namespace: server
    type: Opaque

