namespace: server
commonLabels:
  app: kometa-posters
resources:
  - cron-job.yaml
configMapGenerator:
  - name: kometa-posters
    files:
      - config/sync.sh
      - config/config.yaml
      - config/movies.yml
      - config/extras.yml
      - config/tv.yml
