apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: ceph
      service:
        enabled: false
      ingress:
        routes:
          - match: Host("ceph.mchill.io")
            service:
              kind: TraefikService
              name: ceph@file
