namespace: server
transformers:
  - label-transformer.yaml
resources:
  - ../../overlays/ingress
patches:
  - target:
      kind: IngressRoute
    patch: |-
      - op: replace
        path: /spec/routes/0/services
        value:
          - kind: TraefikService
            name: ceph@file
