namespace: server
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: ceph
      routes:
        - match: Host("ceph.mchill.io")
patches:
  - target:
      kind: IngressRoute
    patch: |-
      - op: replace
        path: /spec/routes/0/services
        value:
          - kind: TraefikService
            name: ceph@file
