apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - deployment.yaml
  - sealed-secret.yaml
configMapGenerator:
  - name: jitsi
    literals:
      - TZ=America/New_York
      - ENABLE_AUTH=1
      - ENABLE_GUESTS=1
      - AUTH_TYPE=internal
      - PUBLIC_URL=https://jitsi.mchill.io
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_SERVER=localhost
      - XMPP_BOSH_URL_BASE=http://127.0.0.1:5280
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_GUEST_DOMAIN=guest.meet.jitsi
      - JVB_BREWERY_MUC=jvbbrewery
      - JVB_AUTH_USER=jvb
      - JVB_STUN_SERVERS=stun.l.google.com:19302, stun1.l.google.com:19302, stun2.l.google.com:19302
      - JVB_PORT=10000
      - JVB_TCP_HARVESTER_DISABLED=true
      - JICOFO_AUTH_USER=focus
      - DISABLE_HTTPS=1
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: jitsi
      ingress:
        routes:
          - match: Host("jitsi.mchill.io")
            disableForwardAuth: true
      loadBalancer:
        ip: 192.168.1.93
        port: 10000
        targetPort: jvb
        protocol: UDP
  - name: persistence
    valuesInline:
      app: jitsi
      size: 128Mi
