apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - config-map.yaml
  - deployment.yaml
  - sealed-secret.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: jitsi
      ingress:
        routes:
          - match: Host("jitsi.mchill.io")
            disableForwardAuth: true
      loadBalancer:
        ip: 192.168.1.93
        port: 10000
        targetPort: jvb
        protocol: UDP
  - name: persistence
    valuesInline:
      app: jitsi
      size: 128Mi
