apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: instrumentisto/rsync-ssh:alpine3.16
              args:
                - /bin/sh
                - -cex
                - |
                  command -v getfacl || apk add acl;
                  mkdir -p /root/.ssh;
                  ssh-keyscan -H nas >> /root/.ssh/known_hosts;
                  cd /backup;
                  getfacl -R . > permissions.facl;
                  rsync -avz -e "ssh -i /root/ssh/id_rsa" --exclude /backup/server/loki --delete-before /backup serverbackup@nas:/volume1/ServerBackup;
              env:
                - name: TZ
                  value: America/New_York
              volumeMounts:
                - name: ssh
                  mountPath: /root/ssh
                - name: server
                  readOnly: true
                  mountPath: /backup/server
          volumes:
            - name: ssh
              secret:
                secretName: backup
                defaultMode: 384
            - name: server
              persistentVolumeClaim:
                claimName: server
