namespace: argocd
helmGlobals:
  chartHome: ../../../helm/charts
helmCharts:
  - name: ingress
    valuesInline:
      app: argocd
      service:
        enabled: false
      ingress:
        routes:
          - match: Host("argocd.mchill.io")
            service:
              name: argocd-server
              scheme: https
