dex:
  enabled: false

repoServer:
  env:
    - name: HTTP_PROXY
      value: http://192.168.1.2:8888
    - name: HTTPS_PROXY
      value: http://192.168.1.2:8888
    - name: NO_PROXY
      value: localhost,127.0.0.1,.svc,.cluster.local,kubernetes.default.svc

server:
  extraArgs:
    - --disable-auth

configs:
  cm:
    kustomize.buildOptions: --enable-helm --load-restrictor LoadRestrictionsNone
    resource.exclusions: |
      - apiGroups:
        - discovery.k8s.io
        kinds:
        - EndpointSlice
      - apiGroups:
        - coordination.k8s.io
        kinds:
        - Lease
      - apiGroups:
        - authentication.k8s.io
        - authorization.k8s.io
        kinds:
        - SelfSubjectReview
        - TokenReview
        - LocalSubjectAccessReview
        - SelfSubjectAccessReview
        - SelfSubjectRulesReview
        - SubjectAccessReview
      - apiGroups:
        - certificates.k8s.io
        kinds:
        - CertificateSigningRequest
      - apiGroups:
        - cert-manager.io
        kinds:
        - CertificateRequest
