dex:
  enabled: false

repoServer:
  env:
    - name: HTTP_PROXY
      value: http://pihole.mchill.lan:8888
    - name: HTTPS_PROXY
      value: http://pihole.mchill.lan:8888
    - name: NO_PROXY
      value: localhost,127.0.0.1,.svc,.cluster.local,kubernetes.default.svc

server:
  extraArgs:
    - --disable-auth

configs:
  cm:
    kustomize.buildOptions: --enable-helm --load-restrictor LoadRestrictionsNone
