deployment:
  kind: DaemonSet
  additionalContainers:
    - name: traefik-forward-auth
      image: r1cebank/traefik-forward-auth:multiarch
      ports:
        - name: auth
          containerPort: 4181
      env:
        - name: CONFIG
          value: /config
        - name: COOKIE_DOMAIN
          value: mchill.io
        - name: AUTH_HOST
          value: auth.mchill.io
        - name: WHITELIST
          value: matthewchill7@gmail.com
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: traefik
              key: SECRET
        - name: PROVIDERS_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: traefik
              key: PROVIDERS_GOOGLE_CLIENT_ID
        - name: PROVIDERS_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: traefik
              key: PROVIDERS_GOOGLE_CLIENT_SECRET
      volumeMounts:
        - name: traefik-forward-auth
          mountPath: /config
          subPath: traefik-forward-auth.ini
  additionalVolumes:
    - name: traefik-forward-auth
      configMap:
        name: traefik-forward-auth
ingressRoute:
  dashboard:
    enabled: false
logs:
  access:
    enabled: true
globalArguments: []
additionalArguments:
  - --api.insecure=true
  - --serversTransport.insecureSkipVerify=true
  - --pilot.token=$(PILOT_TOKEN)
  - --metrics.prometheus
  - --providers.kubernetesingress.ingressClass=traefik-external
  - --providers.kubernetescrd.ingressClass=traefik-external
  - --providers.kubernetescrd.allowCrossNamespace=true
env:
  - name: PILOT_TOKEN
    valueFrom:
      secretKeyRef:
        name: traefik
        key: PILOT_TOKEN
ports:
  web:
    port: 8000
    exposedPort: 80
    redirectTo:
      port: websecure
  websecure:
    port: 8443
    exposedPort: 443
    tls:
      enabled: true
service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.240
