- name: Install oh-my-zsh
  block:
    - name: Install zsh package
      ansible.builtin.apt:
        pkg:
          - zsh

    - name: Copy .zshrc file
      ansible.builtin.copy:
        content: |
          export ZSH="{{ ansible_facts.user_dir }}/.oh-my-zsh"
          ZSH_THEME="robbyrussell"
          plugins=(git)
          source $ZSH/oh-my-zsh.sh
        dest: ~/.zshrc
        mode: "0644"

    - name: Check for existing oh-my-zsh installation
      register: oh_my_zsh
      ansible.builtin.stat:
        path: ~/.oh-my-zsh

    - name: Install oh-my-zsh
      when: not oh_my_zsh.stat.exists
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
