namespace: server
transformers:
  - label-transformer.yaml
resources:
  - ../../../overlays/ingress
  - endpoint.yaml
patches:
  - target:
      kind: IngressRoute
    patch: |-
      - op: add
        path: /spec/routes/-
        value:
          match: Host("$(SUBDOMAIN).mchill.io") && Path("/")
          kind: Rule
          services:
            - name: $(APP)
              port: 80
          middlewares:
            - name: forward-auth
              namespace: traefik
            - name: pihole
