namespace: server
resources:
  - endpoint.yaml
helmGlobals:
  chartHome: ../../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: remote-pihole
      addSelector: false
      routes:
        - match: Host("pihole.remote.mchill.io")
        - match: Host("pihole.remote.mchill.io") && Path("/")
          middlewares:
            - name: pihole
