apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
resources:
  - endpoint.yaml
helmGlobals:
  chartHome: ../../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: remote-pihole
      service:
        disableSelector: true
      ingress:
        routes:
          - match: Host("pihole.remote.mchill.io")
          - match: Host("pihole.remote.mchill.io") && Path("/")
            middlewares:
              - name: pihole
