kind: Deployment
apiVersion: apps/v1
metadata:
  name: ombi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ombi
          image: linuxserver/ombi:4.47.1
          ports:
            - name: ingress
              containerPort: 3579
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: ombi
              mountPath: /config
      volumes:
        - name: ombi
          persistentVolumeClaim:
            claimName: ombi
