apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi
spec:
  selector:
    matchLabels:
      app: ombi
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ombi
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ombi
          image: linuxserver/ombi:4.53.4
          ports:
            - name: ingress
              containerPort: 3579
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: ombi
              mountPath: /config
      volumes:
        - name: ombi
          persistentVolumeClaim:
            claimName: ombi
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
