namespace: server
resources:
  - deployment.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: ombi
      routes:
        - match: Host("ombi.mchill.io")
          disableForwardAuth: true
        - match: Host("overseerr.mchill.io")
          disableForwardAuth: true
  - name: persistence
    valuesInline:
      app: ombi
      size: 128Mi
