apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.app }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.size }}"
  storageClassName: ""
  volumeName: "{{ .Values.app }}"
