master:
  hosts:
    raspberrypi-1:
      ansible_host: 192.168.1.210
      ansible_user: mchill
laptops:
  hosts:
    laptop:
      ansible_host: 192.168.1.215
      ansible_user: mchill
  vars:
    longhorn_partition: /dev/sda1
rpis:
  hosts:
    raspberrypi-1:
      ansible_host: 192.168.1.210
      ansible_user: mchill
    raspberrypi-2:
      ansible_host: 192.168.1.211
      ansible_user: mchill
    raspberrypi-3:
      ansible_host: 192.168.1.212
      ansible_user: mchill
  vars:
    longhorn_partition: /dev/sda3
