all:
  vars:
    ansible_user: mchill
    ansible_python_interpreter: auto_silent

ungrouped:
  hosts:
    pihole:
      ansible_host: 192.168.1.2
    comet:
      ansible_host: 192.168.1.12
      ansible_user: root
    raspberrypi:
      ansible_host: 192.168.1.13

proxmox_hosts:
  hosts:
    beelink1:
      ansible_host: 192.168.1.30
    beelink2:
      ansible_host: 192.168.1.31
    beelink3:
      ansible_host: 192.168.1.32

k3s_servers:
  hosts:
    k3s_server_1:
      ansible_host: 192.168.1.51
      k3s_primary: true
    k3s_server_2:
      ansible_host: 192.168.1.52
    k3s_server_3:
      ansible_host: 192.168.1.53

k3s_agents:
  hosts:
    k3s_agent_1:
      ansible_host: 192.168.1.54
    k3s_agent_2:
      ansible_host: 192.168.1.55
    k3s_agent_3:
      ansible_host: 192.168.1.56
