- name: Configure inotify limits
  become: true
  block:
    - name: Set inotify sysctl values
      ansible.builtin.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_file: /etc/sysctl.d/99-inotify.conf
        reload: true
      loop:
        - { name: fs.inotify.max_user_instances, value: 1024 }
        - { name: fs.inotify.max_user_watches, value: 1048576 }
