kind: Deployment
apiVersion: apps/v1
metadata:
  name: bazarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: bazarr
          image: ghcr.io/linuxserver/bazarr:1.4.0
          ports:
            - name: ingress
              containerPort: 6767
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: bazarr
              mountPath: /config
            - name: media
              mountPath: /tv
              subPath: libraries/tv/sd
            - name: media
              mountPath: /movies
              subPath: libraries/movies/sd
      volumes:
        - name: bazarr
          persistentVolumeClaim:
            claimName: bazarr
        - name: media
          persistentVolumeClaim:
            claimName: media
