kind: Deployment
apiVersion: apps/v1
metadata:
  name: bazarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: bazarr
          image: ghcr.io/linuxserver/bazarr:1.5.2
          ports:
            - name: ingress
              containerPort: 6767
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: bazarr
              mountPath: /config
            - name: libraries
              mountPath: /tv
              subPath: tv/sd
            - name: libraries
              mountPath: /movies
              subPath: movies/sd
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 512Mi
      volumes:
        - name: bazarr
          persistentVolumeClaim:
            claimName: bazarr
        - name: libraries
          persistentVolumeClaim:
            claimName: libraries
