apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  selector:
    matchLabels:
      app: plex
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: plex
          image: ghcr.io/linuxserver/plex:1.43.3
          ports:
            - name: ingress
              containerPort: 32400
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: ADVERTISE_IP
              value: http://192.168.1.82:32400,https://plex.mchill.io
          volumeMounts:
            - name: plex
              mountPath: /config
            - name: plex-bulk
              mountPath: /transcode
            - name: movies
              mountPath: /data/movies
              subPath: sd
            - name: movies-uhd
              mountPath: /data/movies-uhd
              subPath: uhd
            - name: movies
              mountPath: /data/movies-requested
              subPath: requested
            - name: extras
              mountPath: /data/extras
              subPath: sd
            - name: shows
              mountPath: /data/tv
              subPath: sd
            - name: shows-uhd
              mountPath: /data/tv-uhd
              subPath: uhd
            - name: shows
              mountPath: /data/tv-requested
              subPath: requested
            - name: music
              mountPath: /data/music
            - name: youtube
              mountPath: /data/youtube
          resources:
            limits:
              gpu.intel.com/i915: 1
            requests:
              gpu.intel.com/i915: 1
      volumes:
        - name: plex
          persistentVolumeClaim:
            claimName: plex
        - name: plex-bulk
          persistentVolumeClaim:
            claimName: plex-bulk
        - name: movies
          persistentVolumeClaim:
            claimName: movies
        - name: movies-uhd
          persistentVolumeClaim:
            claimName: movies-uhd
        - name: extras
          persistentVolumeClaim:
            claimName: extras
        - name: shows
          persistentVolumeClaim:
            claimName: shows
        - name: shows-uhd
          persistentVolumeClaim:
            claimName: shows-uhd
        - name: music
          persistentVolumeClaim:
            claimName: music
        - name: youtube
          persistentVolumeClaim:
            claimName: youtube
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 2Gi
