apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  selector:
    matchLabels:
      app: plex
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: plex
          image: ghcr.io/linuxserver/plex:1.43.3
          ports:
            - name: ingress
              containerPort: 32400
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: ADVERTISE_IP
              value: http://192.168.1.82:32400,https://plex.mchill.io
          volumeMounts:
            - name: plex
              mountPath: /config
            - name: scratch
              mountPath: /transcode
              subPath: plex/transcode
            - name: scratch
              mountPath: /db-backups
              subPath: plex/db-backups
            - name: media
              mountPath: /data/movies
              subPath: movies/sd
            - name: media
              mountPath: /data/movies-uhd
              subPath: movies/uhd
            - name: media
              mountPath: /data/movies-requested
              subPath: movies/requested
            - name: media
              mountPath: /data/extras
              subPath: extras/sd
            - name: media
              mountPath: /data/tv
              subPath: shows/sd
            - name: media
              mountPath: /data/tv-uhd
              subPath: shows/uhd
            - name: media
              mountPath: /data/tv-requested
              subPath: shows/requested
            - name: media
              mountPath: /data/music
              subPath: music
            - name: media
              mountPath: /data/youtube
              subPath: youtube
          resources:
            limits:
              gpu.intel.com/i915: 1
            requests:
              gpu.intel.com/i915: 1
      volumes:
        - name: plex
          persistentVolumeClaim:
            claimName: plex
        - name: scratch
          persistentVolumeClaim:
            claimName: scratch
        - name: media
          persistentVolumeClaim:
            claimName: media
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 2Gi
