kind: Deployment
apiVersion: apps/v1
metadata:
  name: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: nextcloud
          image: linuxserver/nextcloud:31.0.1
          ports:
            - name: ingress
              containerPort: 80
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: nextcloud
              mountPath: /config
              subPath: config
            - name: applications
              mountPath: /data
              subPath: nextcloud
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 0.1
              memory: 256Mi
        - name: db
          image: mariadb:11.7.2
          env:
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: nextcloud
          envFrom:
            - secretRef:
                name: nextcloud
          volumeMounts:
            - name: nextcloud
              mountPath: /var/lib/mysql
              subPath: mysql
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.1
              memory: 512Mi
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
        - name: applications
          persistentVolumeClaim:
            claimName: applications
