apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server: https://kubernetes.default.svc
  name: in-cluster
contexts:
- context:
    cluster: in-cluster
    user: headlamp-sa
  name: in-cluster
current-context: in-cluster
users:
- name: headlamp-sa
  user:
    tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
