apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
spec:
  selector:
    matchLabels:
      app: tdarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tdarr
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: tdarr-server
          image: haveagitgat/tdarr:2.85.01
          ports:
            - name: ingress
              containerPort: 8265
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: serverIP
              value: 0.0.0.0
            - name: serverPort
              value: "8266"
            - name: webUIPort
              value: "8265"
          volumeMounts:
            - name: tdarr
              mountPath: /app/server
              subPath: server
            - name: tdarr
              mountPath: /app/configs
              subPath: configs
            - name: scratch
              mountPath: /temp
              subPath: tdarr
            - name: media
              mountPath: /media/movies
              subPath: movies/sd
            - name: media
              mountPath: /media/movies-uhd
              subPath: movies/uhd
            - name: media
              mountPath: /media/movies-requested
              subPath: movies/requested
            - name: media
              mountPath: /media/tv
              subPath: shows/sd
            - name: media
              mountPath: /media/tv-uhd
              subPath: shows/uhd
            - name: media
              mountPath: /media/tv-requested
              subPath: shows/requested
        - name: tdarr-node
          image: haveagitgat/tdarr_node:2.85.01
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: nodeIP
              value: 0.0.0.0
            - name: nodePort
              value: "8267"
            - name: serverIP
              value: 0.0.0.0
            - name: serverPort
              value: "8266"
          volumeMounts:
            - name: tdarr
              mountPath: /app/configs
              subPath: configs
            - name: scratch
              mountPath: /temp
              subPath: tdarr
            - name: media
              mountPath: /media/movies
              subPath: movies/sd
            - name: media
              mountPath: /media/movies-uhd
              subPath: movies/uhd
            - name: media
              mountPath: /media/movies-requested
              subPath: movies/requested
            - name: media
              mountPath: /media/tv
              subPath: shows/sd
            - name: media
              mountPath: /media/tv-uhd
              subPath: shows/uhd
            - name: media
              mountPath: /media/tv-requested
              subPath: shows/requested
      volumes:
        - name: tdarr
          persistentVolumeClaim:
            claimName: tdarr
        - name: scratch
          persistentVolumeClaim:
            claimName: scratch
        - name: media
          persistentVolumeClaim:
            claimName: media
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 1Gi
