apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
spec:
  selector:
    matchLabels:
      app: tdarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tdarr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: tdarr-server
          image: haveagitgat/tdarr:2.85.01
          ports:
            - name: ingress
              containerPort: 8265
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: serverIP
              value: 0.0.0.0
            - name: serverPort
              value: "8266"
            - name: webUIPort
              value: "8265"
          volumeMounts:
            - name: tdarr
              mountPath: /app/server
              subPath: server
            - name: tdarr
              mountPath: /app/configs
              subPath: configs
            - name: tdarr-bulk
              mountPath: /temp
            - name: movies
              mountPath: /media/movies
              subPath: sd
            - name: movies-uhd
              mountPath: /media/movies-uhd
              subPath: uhd
            - name: movies
              mountPath: /media/movies-requested
              subPath: requested
            - name: shows
              mountPath: /media/tv
              subPath: sd
            - name: shows-uhd
              mountPath: /media/tv-uhd
              subPath: uhd
            - name: shows
              mountPath: /media/tv-requested
              subPath: requested
        - name: tdarr-node
          image: haveagitgat/tdarr_node:2.85.01
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: nodeIP
              value: 0.0.0.0
            - name: nodePort
              value: "8267"
            - name: serverIP
              value: 0.0.0.0
            - name: serverPort
              value: "8266"
          volumeMounts:
            - name: tdarr
              mountPath: /app/configs
              subPath: configs
            - name: tdarr-bulk
              mountPath: /temp
            - name: movies
              mountPath: /media/movies
              subPath: sd
            - name: movies-uhd
              mountPath: /media/movies-uhd
              subPath: uhd
            - name: movies
              mountPath: /media/movies-requested
              subPath: requested
            - name: shows
              mountPath: /media/tv
              subPath: sd
            - name: shows-uhd
              mountPath: /media/tv-uhd
              subPath: uhd
            - name: shows
              mountPath: /media/tv-requested
              subPath: requested
      volumes:
        - name: tdarr
          persistentVolumeClaim:
            claimName: tdarr
        - name: tdarr-bulk
          persistentVolumeClaim:
            claimName: tdarr-bulk
        - name: movies
          persistentVolumeClaim:
            claimName: movies
        - name: movies-uhd
          persistentVolumeClaim:
            claimName: movies-uhd
        - name: shows
          persistentVolumeClaim:
            claimName: shows
        - name: shows-uhd
          persistentVolumeClaim:
            claimName: shows-uhd
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 1Gi
