apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-uhd
spec:
  selector:
    matchLabels:
      app: sonarr-uhd
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr-uhd
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: sonarr
          image: ghcr.io/linuxserver/sonarr:4.0.19
          ports:
            - name: ingress
              containerPort: 8989
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: MAX_NAME
              value: "140"
          volumeMounts:
            - name: sonarr-uhd
              mountPath: /config
            - name: media
              mountPath: /tv-uhd
              subPath: shows/uhd
            - name: scratch
              mountPath: /trash
              subPath: sonarr-uhd
            - name: scratch
              mountPath: /data
              subPath: qbittorrent
      volumes:
        - name: sonarr-uhd
          persistentVolumeClaim:
            claimName: sonarr-uhd
        - name: scratch
          persistentVolumeClaim:
            claimName: scratch
        - name: media
          persistentVolumeClaim:
            claimName: media
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
