libraries:
  Movies:
    collection_files:
      - file: config/movies.yml
    settings:
      asset_directory: /data/movies/assets
    operations:
      mass_poster_update: unlock
      mass_background_update: unlock
  Shared Movies:
    collection_files:
      - file: config/movies.yml
    settings:
      asset_directory: /data/movies/assets
    operations:
      mass_poster_update: unlock
      mass_background_update: unlock
  Movie Extras:
    collection_files:
      - file: config/extras.yml
    metadata_files:
      - file: config/extras.yml
    settings:
      asset_directory: /data/extras/assets
    operations:
      mass_poster_update: unlock
      mass_background_update: unlock
  TV Shows:
    collection_files:
      - file: config/tv.yml
    settings:
      asset_directory: /data/tv/assets
    operations:
      mass_poster_update: unlock
      mass_background_update: unlock
  Shared TV Shows:
    collection_files:
      - file: config/tv.yml
    settings:
      asset_directory: /data/tv/assets
    operations:
      mass_poster_update: unlock
      mass_background_update: unlock
settings:
  create_asset_folders: true
  sync_mode: sync
  minimum_items: 2
  default_collection_order: release
  tvdb_language: eng
  verify_ssl: true
plex:
  url: http://plex.server.svc.cluster.local.:80
  token: $PLEX_TOKEN
tmdb:
  apikey: $TMDB_API_KEY
  language: en
