apiVersion: batch/v1
kind: CronJob
metadata:
  name: podcast-dl
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          securityContext:
            fsGroup: 1000
          restartPolicy: OnFailure
          containers:
            - name: podcast-dl
              image: node:22.14.0
              command:
                - /bin/bash
                - -c
                - |
                  apt update
                  apt install -y ffmpeg
                  npm install -g podcast-dl@9.1.0
                  for d in /podcasts/*/; do
                    [ -f "${d}rss.txt" ] || continue
                    podcast-dl --url $(cat "${d}rss.txt") \
                      --out-dir "$d" --episode-template "{{guid}}" \
                      --include-meta --include-episode-meta --include-episode-images --add-mp3-metadata
                  done
              env:
                - name: TZ
                  value: America/New_York
                - name: UID
                  value: "1000"
                - name: GID
                  value: "1000"
              volumeMounts:
                - name: libraries
                  mountPath: /podcasts
                  subPath: podcasts
              resources:
                limits:
                  memory: 512Mi
                requests:
                  cpu: 0.5
                  memory: 512Mi
          volumes:
            - name: libraries
              persistentVolumeClaim:
                claimName: libraries
