---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-api
  namespace: democratic-csi
spec:
  encryptedData:
    TRUENAS_API_KEY: AgB/MSMP0JcXx1z9vjjIpE5SPj4y4c9DqAi60u6ni7uDGQZIPT3kguKcGJZB/2FWkARAmRoPbhI1cMirUAQ7nJv/ZDG9MIp8clE9BpK7JyRZm2oyex2XdG6uLJTPBor3JbWlbc5+nRJZJr86BSENv3+toYNqMIhs9D06PDggJPjA/BiQlk3rY2L2LmaWcV5eGF7oqtUdkVSr/4L54zM25KvEOud28kBbAnB5f9b42GvPBpp6U6kEMTNQ2xLftV7pB/XUJk6FHWh5UC7RkajOom6Or//1IXsMSC6tidaJuimxwhQ684+E9u99Z1feOyqWasQoAgzs0LSJN/fgRIZLHW7SgICXGXobX8L9WQV/aHcndmEj1Oh1dMGanPC54W2UKt0KKAYDYFGwF0ZGmAXvqVbzektJxgdiNdzFDJaqn2rNU+szsm0/nLckkCHLMY3cLv6nPZZnSwZfrsKGxcsQ90AUI7W+S8em2/Kx9lZkFjJpmy3cwWqyVDWouYy+vT4MKDnVwynY6vP95ShfwIfKjmvoRfQes3+NUbLvZzHYhDGcAWQCyEDSEv+QrRYTnq6QXfUygAPm+IyJmVidzKub96XbtRGpFtrY9HVCYXvhNopZLl+gTCQobY7NP/59Ts2a1iNn1Xm8bq7S02Ic4OiZOV+Q60lwotb31NW4UufHJ7V+ivXOw063OPUKM7EX12Kt5HdlpducR6ShZBo5VLeiCXjaTfRmuvl2lkprh/veTeICN1IDdDzfAHNSCHPcMJlyanN1g6m4MS7qcoD59lqOqMTkPuM=
  template:
    metadata:
      name: truenas-api
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-chap
  namespace: democratic-csi
spec:
  encryptedData:
    node-db.node.session.auth.authmethod: AgCBqiqbdenV8VkU/8c2c9ndPvRPNKaRJalHHRzBJXksi6s+4J9cXnMsArey78ipbPXpxjnEDocbKjzqFO1/q6KLV488qHAtxl/fKPsCOXpB1KO4+oz41a0dyjc2I5kqy/t8p8CA8ARXiMF3u+lNUjLQJOJBnGY4OGnOfNVw4MJKDI3Jw9u0WZmZFGdjxUQ9rTInzg+l6dmA/LEzcogH9KtlgGnBt+I0Y81uG/8DrT13oSFXmjnxgHFBJiLRfg2p7pybpIIe4q/ZD0e39cCdtEK9mO/dmP4trVXGMc0q+22N2udhKG8AuXyOVvWpPrKQTWsaHbXiU9Etn4WHHjqmU1bic3RLebHzx+L2Pd4+4kQ3wN5sFK6Ni+lMsSZJs6R1fxC4fWX82sZmAktKpUw6XjbSuj2kVRaniEpvvEbm0HXSaPGtOvOU98g2W9k08Njh4HCG+evV9YqYOOL+a3hGNS+6kIwXmyGXnDlyvvkjHnp1/tldDeF5q0PuWWKHaobaKjYmkTABGwhZHgUVLp+ULEtry4tCLTLimT1HYRUdG6EJmmpw5Oh+y/V2jVB/AaZ+s0/xO8NfV5KIFoOdFc4FmmI2qihPMXTYANLNEGiEu96DXHWyzi3Nb5woSTGn77bRt4jfbkckyVuix6EdAXJkyXNRdi39Pm2/JDSlYPm4fwJMF0c1pjpf8g7lGORwbpxCKCSdJM+2
    node-db.node.session.auth.password: AgBDBULQc5ICuNsC84paZDowq0C92fBeBKr8gQCrSTxFPTmA1z1bCLeLNmyAPwOdE82/V1DG8mfTRMXa6itJSj/OyCnom9aDLIURIem4zbfiwrnW0+5uXVE4+g/FYhnroB78hCBUrY9FAqrzUkLEFl+W18Uk2sE2gtBZHFWdDoQck5v8wgOefPxoSHPvSxg/6pkDerj5CAUA2X6BamFbBfpe3/caiM8m2fY4GfAprw8T54TcRDhA9LW78NHMoUntZxvaaREa71esg72ozCGfG1t7Xs9LLnHdug6J+rY6iTS0CbsRDzqjgLu63zzzE3N0Niqjppmqi4KrZmtPrqtLUoOPHAQUEPlZXafBSLwrmRjwNt9KmySKUwB4L9qQSBhdXm05iEvIqtdZNLbcoJ9koRkEdEdwoY+NrDxjYxf8SwVO9OxOc1zIdd7/dRszWEwMhl04x2bdD35HcsHv1R7tpjf365PjsRe46dc2jzqqOE/l72iRLLFk4/4lZQ3Ehif+mXXL2X3zvmJ5TUYzPk3x4xXCco6oO8phe6ZdA9/CVLt6j5Wx5Pf25sDAa+PlUGfmLJFwSzDrvvFwHAp9rHFVz7gaOBx1jXBaoPs4ZskgL5ecR0xE0kYIZvHo4K/Za9YPcbyPuhEFh2Qn9KghtWLZe0Xw3DS4q4uPl82Fsk4eU+YVIQiDArU7oHL53i1+Wii+3MuLsI0tXl1GiSC68WlDMUl6
    node-db.node.session.auth.username: AgDNxUvP92zsFdWKiOEmy2KGUyX0mCP+2ccVEkkVMSipgMnB9XIxMFQbIZwAEYgiYzoYXeHxoL665KHgTQP1ogrfi7IKZ1kOGsGiA9dZrHy+l0KiW1Lp4rZBVz4+ElnVPI5PdVoR/nNxsM4qIXRRfK4MBN0StG7IKioCY0mnhoQKJjsehjw6tofPNA553OyaZeNPi2M0ze4tPGAqt/J9lueqvEA/f73t7nMuFF6NpZvIAOJmMfkj8uqpeNPTT/6wdBz0c2BFZtqVmY9HicH0c83MNcSE+uR73EgnUmlMNu6D6jnb8OeES5zfnCCaW1ILhMr6ktuPb4C2OgVZbdZh9eNZ4fSOTfuaFonG6LOE6QSIho+eyCNUyGBWIn5VEQS+IWrnM/Z3DkIomRDnSot8s2YJpqhSDoCMnqhXPyPF8NzWgSS4pfnT2T9md7MzyV9/YjPReOIeYOzDyuIdg9rY8v9qbDv+Z3wG1oJBjLUrd/pHlCdqebdZU3H8ML82jHkcyZW5HrFU9LtB5/v8jLP12xvLsiZrJ6zmopHFoI+oBTdb4a8ZJQQzS3DHQDewg40rcYhdkT/PNZFA8MTiuTJZ+ICnNisTVvKq2TKwgc2GHGXEKs9QkcO0TZI/DCvj6Rx2megk1D2FAn0EKHRPfDGHSW1IR6LFm7de8bKNZM21oxjWYHeGFaTlEbmB0c6FYUtSG6A1JPK+KGrSGTQR
  template:
    metadata:
      name: truenas-chap
      namespace: democratic-csi
    type: Opaque
