---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-api
  namespace: democratic-csi
spec:
  encryptedData:
    TRUENAS_API_KEY: AgDSD/BG2B8JoZBsZK0uPcVq+qzL4a89FT4mViy61ksrcQzuhUbdbn0VtfvhGUeBy0lq3UrctdUVX6sT/wZsjmcO1uvbFj2myxiAxuVD4XYzeP5VoFTfSVLbyxT5WrUZWNXD/yQ8/dzdJplZYKeYzpQmlgrNmLFD7492s0F1xTWrJyQN1mE6yeBYCpy/MTNphMdq7HEMxw02wXQGk7rXI8+Z7ESHJoq5Dp2SACL3cpdh77q2ISWk8OXzGU5VyPochH7cRzbW/kaUSVrQVWjEHEl5BkpBED9CAawLYp/Un5yP3L2jQptfS62Y9Mqp0NoJ3LcLcFb+7VOn/VP7KSt2a5Afd0/PoihjyJqP4rZK5OV5mxiNjSpU5dDeM7xLtPMWnZO//VzRe10N7V0UmDeieYUBOgmqhgoRguNNJ2pIN6N5Znpenfk3wcU/OP8tH7CNxFcc0Ys40MMjAFkhIjynZNjYFQR+HTCJKNajKpOnqRnPDCAmSPbQrpcnz87cvqCNNTQTk5Z+WLxBJxgNcmVmyDV2EnosbU04x5MCA5xTAP9+5mePTK6LCB9aMjezueH1aXCBxCNzKz8NkBkgGVWBOlseCMu6c9m2HyDJ0M+anW5tPF+5eD6SpjhiVhlgWKlDZvfstNx3QAbbhyi3/GiWCf/cHP+RlWorlqWsnppKoG9aAzDGPcVotHOPj94fJ4S3b8TdDEzu3OOqk1GV3cSK2WLbmBy12McaY5LJ0TB2I0/9d3owbvSWA/WSoKmJoyVNkNW2rQK2g/4t80/oboPa+YrCkwE=
  template:
    metadata:
      name: truenas-api
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-chap
  namespace: democratic-csi
spec:
  encryptedData:
    node-db.node.session.auth.authmethod: AgApbIe9iBxu7xzUwIDHXAUGgKciw49pFTpPi/9o7Us26bsTb1FnLkfJqMWrs0sSXA91nbINK+30JRD7bEZMgEBACqsSFbSiq10D3vdODMGGJdierQH91CNNhp08zcQAI02szrWxg5Ykin+C6YJ+2wqkleMv+ptlnFSqizWCVq3/q0gqZZ+e9w4xWG4eKHzMbx3qwSKSFFBTOXQtLvB19VcE1af/KE9Y3Algpx9xcYHnL9mVsTLPnqEarsQGOUS/e63JSweweybPJ24GbfHdO72iRMduQiCwvcxujzcnV6XGVm9aKx3piaPWZ5m3ZzBwDY4USC55JH2y9272/Xvf9Ub2sd2Nmx8UiBNbqr9YgDDuhSuViHLokCSD03sljsonYGxOqfljQjeXNSIJjQ+uLuGCUl3F9lTV2J4gVM9Ll7bTo2hdYVf2j6Oylt6prbx5h9i5y6DaVfidIyLYFK2XmzOPhDvvdKdpuUvrBv8H95gFBWAWrPTxyunWam+JQOu5qReT3hKz2JhAXGhR7QJMqWUDLjKSwZCdg+6dL2If/0mPnA51IRsRIzJr1KzHofDGf/3N7p3QUi7xZlr+5L/6C9+F6QHXAyni/5FiVKRssRiC7BYyVuVk8Eh2io4RY2TUj8Xhj48dmv//YIqh22oO49yyKffQ65GzLzG+/vtFZOf7RQ21OLYZVxvNgxVzLzZB7ogYMblX
    node-db.node.session.auth.password: AgAyAxy5xY7Fky7uRPgA2EovgtshXakR7wCVXpXFYcBxfH+ueVblONozYbAc9zWIa0r7Wueyup2QzPzL6PhsWbDXKsV524vhNYX1HGFolVpipcj06CQBAJnQKM23h5sGmu9OXr1OwGuqQ0WVCJKEl4W7AxWNYYtWLrvmLChFVr7p2ROuVBvDhynTwjaDmZln7LGANVeIxS088X4R9eJQjMy9WUz+TJcgEfDGUyhe/VGc0nzYdxKlKYOrNq7XMWAVPKz0MfIuvnEXfj7LeKn1COqBjR3dgGrYoBUmSUXtGbwcGWe2u5Z7/vfkNlBoyK5Mb+wdyXE9REpwBMQNSE2QsiflHIsKmveMqiq3ANrblSW6V6SuvxP6q3F+cWQYYeK0V1RcaoFBb5TR3rDOxC7ZrmjNLszEyGEXI48lXP6DelFahIluxIz5kU73KSbZRWjO+mf8N6eS/eXDDnWERDxn5OMTJ/4pzUqcv3dQI1Um5SmuEcFKcoAILv5xWJr75kdpfSQtE7vgjmOfUk2e8HHK23bQySk0ydhMdYKHbhcL/yYoWUrrdMvSsXuYIOf2bY00NKZo0+JFui3CHx+YK2JqE+W+SLYfbBcScnYZUVIxVacGv7nC6RlXbABhWHwY/aEDNK3JRrb4f1w/r7rffjo/r/+ev6qbxAwtuqC/GJdYcojqVsSoaGSC4H9a4/rz+oxsbDuA/HCNDRxuqkLzf+62RkoH
    node-db.node.session.auth.username: AgC0KnUkaIcFQIy4W1l0sZz0tLiYWjhyHwkcXWV+UzC3a2mGnE/qncJ3hJe1rP0/Th1UxxM+XBE9zBJMOJHPNnOMz6Bxkef5Yuckcz9Uh+Vh6B8nQ4nMhNK4oToUQ0pMVVW5Hxyrz0Ynhu3K1dd4RIc7Jo7jtanjIlROLTiYeM1cG9EncZgr8/Md+DR+NAFxozI2SCmKflMjeDX/ieGnKMsXBRtOt4iVN08w0DZ6Iovu8L5SonxryYLdff03G7fbqEYnhY6Zn3rsBHldisJ6SSepOTwkxp5HiGaJLXvdcHOdxVyl0TLxa9TXrSSBQThshpzl00Frge0lCDIFAKsoNWDnIVERPDYgP1Q3COm8GIMcWYquYR/E7Tem6FWacDYI2+hrBGJwOxoPE6h/H7dLDRhts4Oi0I9nWFE05hVOBYJKmTH3jTCUPaPT4pvVPGlQfjHvEBSFwjFNJRHT4Lo2K76SdoTgD60u/w9zZhDp3XYgb+jVpfmar8bqCgg4TVob0MZSEB7Bo4Ce9Qn7Qpm2j4qrbdWFtwHfseQqP4ucwwqEt0XlFGnVaXIYy3H7fEcO9OE2LyhembJ6BTXYIRFSJNufvXYQ1BRYgYlEOryVOaurQStutFf6SC0j80ihQOK/1kD6gT0khRFjEqAZR3rGV8jFsRXptjUw10HKpAFleaK1wB0w1tIRuG8P3d0+nQHv55tWK8+bjhhwaES+
  template:
    metadata:
      name: truenas-chap
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-credentials
  namespace: democratic-csi
spec:
  encryptedData:
    password: AgBWofh2zt0vlVdpvAQdRHGjFuuvHC8Hs/tN4jXK4LPI4EttJGcHNs7QoClKseiFn4zQxnnAfhW0YJrJM6+xOdTj27WoQLFkRiOqBQN+C4NDyMaoJWdFpezkCejEE7//AvYKRFVCvSoiA7Y3KEc4yG27O6t+SrsQ5tZ5zTwstYgNEJd5f4n/HNQ5NP94/UU09l8hkwCVeL8sMyGM07IlaXi8dGaZ1zf8JkCbE0ao1tjr6rw0wDSS8w6PuOkLSfn+DWHNIDgBEpRa0qlAou2SigHfqxZElrM1fW2juaW5kMa9nhqiwPbafqAfszL0mGGMJ2GGv7XVcSgKIMhoO2BM1sjcQWxgABHSZ4PtPfYqlIBfhCjHzYRbt/TvPe8ttYOkzqt8hTpDwWyqReqHDWtnbUTBANptpZKMU0EFQTi+IqN5QGYk/3era0kW+Ww6+H+jjVlEayULHsOcn/cJCOhv1LYVHfM2C48i9Halw3AFOqQa34nhg+qhAaSSEkBo0vVDGXWJ6/Uwwckl11YRbsgu9iYYMAZpvK0d9W6+ZBwfnGUx+cdMlEqgyYMUV5BMWX4FqMjj4hpwcwS0xgmtAos9t6wXn6gqBwIYJbuohC1Vw2WW5EOTOTAx6d8NUidkNtK2eIT7UmLBXmE7ZeHgcEQT6lKPNmZl8/4l7ZsMb1rZ7VYO6StU+HaYbPk7PRwx3dA8WsfV4oV5BY+20vQY1lRS3aWSkI71nQHs7jfPCIBO3rOFhQ==
    username: AgArw+N+BlkkkNW/P/TfEnef94Bq86jkLdBcuAyAb6c8Qw+AnEU0h8jz86dSahFM9fHcfdfGghm5O1G7dDiKCVHLExiwOug4uMNReVbvzBWgt9ZZBaZ3D3frxKKltW0mpI7gQ2HapK0euXy4Q7c7oYU4AJg5vALV6x2b67VbiyXCItYiXVYW2xZ2+yYP74w5ljrZUvR64s1/E+e788zrtcU3iQaTuI1A5l2qFCrMhN17KZ8QVwsuztscioQFH/1JjbttKraaqix7L2ojbduh4mHNxj0cEQYfYh92QnNi1eYQp4t6el+zx13MQb8mRVxY06kZO53W5Cc0PZrjJsIJ9i69OW61ZOuUe1+i5GYeJImcBIjgyAlxDJAoSeqoAs9s7lTpsE+CL5qm5smChqg9ELHuIs52hDYyADaBadcBiaEiIAjx00wHHBfk3KCHsV3iZfciqgxcMLyRskrQd8exjvQbinT8gI6uSOYXeI3AGJH4zsyVH5LINa4jSGFu3lwxG1k9SW9LQG3RDRPrnD0i4gZnv1LeMH6VopfKvNWflmmC9n0vYCZkDHm0YXz4aScqYJoVg1QnwQs7WdI4uZspXPst2c/6hHeXZ1hMynG+nuiW7szOJeriP4dE6Ok7owaag5ScPDnVAqKb/U67f+qfe/i+kcPCD1DcgcrV9qycb6wb+Bzt5v+rcZeHJetYJZEirQ979n7HiPWUHsyh
  template:
    metadata:
      name: truenas-credentials
      namespace: democratic-csi
    type: Opaque
