---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-api
  namespace: democratic-csi
spec:
  encryptedData:
    TRUENAS_API_KEY: AgBWHgzZ6JKh4PtxANDEorGetRsH/An0hBQzDb2Iir4MGa+cRDTwG6Cw6DUNjX1l81wPDRP7KCaGpGLKuRS5et02m+Z92lQVUPaqYhycDi3efbfMrYr/J+ugcAE45lfM21XPshKceBPQaudCv8zhzgnlCBE/2yPbO0sQPIwYUdnoYYzVJeb5u6i47oT+JcZggwSMWtikXkyJCeU0vzl0Xu54evSA5G8vFmGvC1chhGPOl4q1DU/HFrO7QI9Y01AG3F5ezdtEE+7Skyq4ADCt8swNHiJTCHfzlgwkETo+VgcGiT54rLAL2NC7jFw2Wv7h5nEYtZT1qfGEO4lle72WAl6C9s4rlALJwspsFYay7N6lsZ5hZqdXl1DnsfwxN0wjuFXXG2m+CdKhvebSg/vIwlfjKCAIToguK9jgblEA5j9OrE99rqhOADS665YUJnrzQLNUbzLwtpKeDamXoULHujnjPwXLA1F/AaqwHAnVcV7Cc/k+1cQEEbB8DtIPbXrzcp0JhEckK0NDCT4HxfXsNQvWi9Ha4Eb/9knjIl13zgSaOXtwEOe+MexxS423piQhIgDoXJgZHw+usB/U+Pc6MIxfWlvPTR+CIMO/XBJCb7AKMCG9NCm0HOl4tz1bWvGBieuqWvBbu6bYgH6i0D5Z+VQlVaSnpWy710xIZMhk/opDda9/trSOhYZeOfOwS+yrErmpkJCFgF/8K9Ifat2V+65352b0sHLz6AUNRYMlr+e8kNQ4fwcaaBznV0AuYcBGcsUTUs/RaKC2GoN8TNAolyMqPY0=
  template:
    metadata:
      name: truenas-api
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-chap
  namespace: democratic-csi
spec:
  encryptedData:
    node-db.node.session.auth.authmethod: AgCjJo4dpAfsQ1s7mycffjZ34ltn6fq7g+dUYnRAMyXeCOGJ+rHnZoduD5hpHbEwinTOcjO19Ixfo63vrmYFqtoU7ytQqFgnN79nI72Vqw4N3cAv9cYmbTIWVDHMYnJaSs4cMoe5gT+QaDCx6KSbxvvTbgRIPi+84X+2XzK9L0Wo6sLQLdIewG6dQe71hpxp/bAM+gtEUbvj7Yv2k6L23eGYBpaW7vyEhjJTHG1y5J8pvt0hx6PEbkOh2U68KMp2U5wzXWkBYjjBYDM7jqjQgKQg6nqoM95iK7T+zDt7cf8Pfg4ErxImkwVmi57U0qQO1kiswEZ/Iuey54xBqc1Ve4UBydgjZHx3HizWCr1klexx8Oi9E3eRIvLXtFQkx+/QpZmEBAt+9B2r30E9bu2JRxaHJCM4QJWWXmuBZllHgehVqHKuU7XrL3TasduD0dKhBoG9MI1OnjoQ8T+YJyj9UcxxBx9zsWIW//3uuxy+niE0WTFKYIISPMQ2UonBHRcQLFSXtHRKnBCvHEM7UwlNPybXaPdvIdsWx2VMM8cHmNKl+LTMzOJl+DR0wN0BlTh4nn+f8lZQrL3KO+0d+B2EOhaB/zOvVPHfML82G2XWL7a8sNKG447x8CFkrb5jYPmTu1uvzliGVVJNI2wTs+qoJfJFiGWZFizlYePdEi0OvuTSkVD8Anutwge+VPt2jDhdT00zaFBn
    node-db.node.session.auth.password: AgB61miD0EdKqfh9bkteHFPbg+nUvBvMWmBT0p1O7v1NTcIeA9minVYAi6fC+81Ay65alk7F0xK8IART3bpbdU5YgTyyL7iIjb+Rslg108bnx5p9XxlzUgKCJfpBynMWYVebDUIoa93JLgNBsy+Dfa6LZfmJpR14wmtX7/bYd9A3KvAiPGShEKv42u1pfU3q0PjBdbhvacSYA/FNBp0wnrxlMOa8p7lw37KPix5WyTwenfLQ3LH46DefUnwgPJmaic4v56otOnu26pOEV4IXMqxEXdM7TgTG1i6LTbKB8SsiC7lJcY1g5GMJSSQ+Cwt1LaAuHLzr/UDfD1rNPXchvx/wGkaYRmI2bhh/8cFea8plgIipJzA9PXuF3J/dLt6NTIyjXmvuSgCqITtBLNLqROLqwi9FLiPbAuCfeeG+I+ctWSJWHcMMIR8Z19LUqMRW7EDy9YYJVGAlMh/s0NYyw2eBZ8IJx3nSGt/2L4TL/3Ho2ir/coA+4yGrflQT8dU0uPa8VgXMqYs5x1bcy/A2qXidZRQTwglWoerUy6FaNtVo/UY4Aky7D4Cu8OEX0UGzhcTT8Y+ES6ZVrAikbiWPfXk/5DW5LxnBnzSvFCULvR5JuajQ+EQvUIRDs/imI+QLQnYyoFA2twXTnfbbxDdTxKcoCWQINnsJhktGCJgzizHfaP7olnPBGGDMh/k1hk5xvMhKxZsXoRis/WbM1aombyo2
    node-db.node.session.auth.username: AgDaUL2AKfEqwisoIBAZg0jZYj+xgzbjQRXMVukzs8sj5uHMlX1KL5vHwe0p35uQ89T2mUHRannD+NpMdxf/3Uz5rS41xPn2AJ/la6iktzKimNwklZTOOFvYVGqyAR+vRZwrpKXYqN15qyzfiw2QXlfuAvd0E1zPVZdE8l2nnBcfakV1hGOVXpWrJVeAM+e/UUOTSngqPGMb9IpDWLZICTxzq8EEo1hJTy4y24dW5hu+/6tq21q66Jao1TKMrUjr5Zua9eD3bl4mKSNgoHw4ppxD1K/OozLzDhF2ZFqG/81e46QcllNoA5WOHaFdZAOlDl7iUBNxrR+4PlMVZEAYCvd3cOnt4ECsTaP4Bd97rnN3e5PCVFjIfUGNtHICjjFmWhPqKIbDRmHabqJIw7wBdHTnWU1CIe5Cb6R8kTRezxGVKHlbrVKOgDVqW1E+5KM11OpoKbKUUslHDLoD1WThZN9XbeyLUg6fmjRXBFYOQgEwD1XWhc2Yr4oONv+kWDmb8m5ppH1JwVL/sn6zTxG2XFgar+SL23EKboh1+LrcrKAH8prTz7+vBhxKrTBlivXQohAya3Lc6AYHpsEvE8Ic8CUtCLr4/FSH/OtGiQnp5hxovbW1+FVr05Muxd8eLHK2R/pjGALsBy9vm5ojd95tEtMKju20GHzJTzc1/u1o4RWrWLZfrxjOel5QUrD5KDVsX27u/Dxt/Yqr2980
  template:
    metadata:
      name: truenas-chap
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-credentials
  namespace: democratic-csi
spec:
  encryptedData:
    password: AgAwy2TCC9FnLH294HyFgSDBMqGPiXZFXjKhTMXxoHkwiMeQQzu58CAIUvZeqhvmFhI6Nodb4tDYC+pVUMdGza3X0sTXzk0zbOfsL4wclyDrUZnkRtMxzghCC6A80YeWE3tjUyZMpNtp4s9mCDLahrC/83kzw2rz6zXhfVKTmWbDSsPzpdRoQjoTvEyJXUUI4Jb+Jy4+8ev/M1BtldZVTQyomH1xGVjpr4AsH3m/MjkAKfX1CkdO4Z7Tsv5M0Hx6fQGxtDfYK8uTBJxoltpnSh1EIa5ibNsCYYPK+cl54GUMCWRejACMCeH0Hg/Ksw7srY2/x1q1jeYckvST0FWvKfSl3IM21ptOzy0iI84/BukYGP59l3f7hWJ561FkqAJP1HZP6KAb3Pbkpu1lveAVr+ELQ3Y68tSvMnDdTAn8rlhoX2lZLnrkAKifRynawvSvU3umT12F1j6Mxapxf7Gpc94POXvyqQzMyuyQFwkFRjGeWuEk9MBUAD/NgKr72VDMx4WsK/u0ZGXiIvyFoR+ON8n1EdC2nCXnsIl5C7Ylo+5NQ/xaWbr7RbpjSxqZtG0UTkX+EYh04fDPCndl6GlGFo/I3E3/U4vdqkOUU8ylekywua0bWPXjyhtQCzJKma0W8rmwgqc0UGQRtMAtavXnt5b+DxBEhwJbwlYNH3XKiOcvBmDdiFE8k2+I42VbXGBM/iywT5a2/bfNhaS8x+pLO9Tr2lUffz78HLik6I3DbpmWvg==
    username: AgBmcUgCtaVLmicwvfD9UfkAR8V9VateOA3uf6NzK3EuFHsawNUe8ALYSK2EmWCFqIlO/FdZApvsP8MCWvzW4tN1X9L8m0EQHxNvcXRpDYKOprD0MwFoO9rm67W1oVm6IR0fSABPrGFRxeZvFRn5aan4SK0Wpoge6lWr/+NonRSfhVxjaMtKPpIiDX+YoIjNmTcky++Gt3EE29aJ8o71pCPgo6XZpH8SBES5LJq/mFYu5L5xp32YQ9SFMwN+HVcy7n90wjCcTYeRDKemk/1ChKM8+m1/GsOdqZCMt6nimQcs+0ZwtHEmGeNcWbTmnX8Nm835lJ6vwUMhXSKSc4BuV5ngCjsApJ+pMh7412guaEuAj25/hgCvxt75eVCIKYQRn4VXlndOUWHcPd6FnhNnT0EMLzrSXX5zYmTD8IznXvVOHh6jKkUldKwI5o98lnthdgeuETRMFpZinDyFzGkGtiZO/UVmYEXIALAOf8bXSr5b9M/v4qwKWi1RpeVrY5TOjOtiqQUNysS4FLABrxeLey0phUlyaAwx/pnoGl2lfiPpXrKhomj+MLIsJPPFivNturFzbwAzXgIW6sb0hP18p5EgjdilISy7BG7Ot4mxkWIzo/G8P3tXZpjwS/30a9bFWtRKCnd1UH1hrI/AfptT3yBrSMUnOrUI/e1oyLWUwjHK66CnFDw15ExpLfiW5zepf7T5SrkfVHUicDrD
  template:
    metadata:
      name: truenas-credentials
      namespace: democratic-csi
    type: Opaque
