---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tubearchivist
  namespace: server
spec:
  encryptedData:
    ELASTIC_PASSWORD: AgB3XO3QUTlOZon7MG/kLNFrM+QWyo/69sAiCVIIDiN+Sz4KVXWzqp3ycUntTs/tCY7Eq25SqZX7HnDAYRKaQQRdIfftJsYhfKdg1Ho8Vfx6esz0GpFWztis82zZ8RZTQUhW3JcntSk1ef8WHYm9bGfVFMl/VNJCZ6OTdcPmdZ4tLeQQhcLfstJohjCJCiek6bhUgucdrZv1ylznrj9AxfbNxOMit1ukHdWVAdSkIMMibvmoAskPaGPEwvdsgQzaxPX0bGSuTL/Ji7T9li0N8lnmuvPTNvS1Iwitcc/pQe+5gMWvp5+58xHJ0q5lwh78ND17/cvyhe+EfBsAQKjk+UdqHZli3IdD+OxQIIaP7xAGLKbYjF6uEBveyZEDs+msmDbU4J3s5dym4pIvUbDctSPsPy2fUTaWUp/DUm84JxOZpQlmKJLAle6Z8bmymsz/5ydqmqx0qEL7bqaF+5V0XbP3jUtenwxQ0mW8dE2NKyojlTjXZGSox+C4DM3Lu71n05IlUkxynaxg67FcxoDETA3HntxHYcApQTtu7/eP6sOBUR74CBQhxx1xenYPj4H0V4n+IL4katU7tmeyCrYZ+MQg9VVaekuDitkC9KgU1bxsdrrfruYeuDsmQLJ4kJafksvy5tsw9IANukRAF+7TWPHNsQSvCX+5jXTfK/s+eUPNQCg2QqV+hdnTJBIv2ofcqSedG4cbSlmOKQzPgbYz1E/2hUP5BHw+y5CPWzxW2zv4lg==
    TA_TOKEN: AgBnPFpHaqi+Ry4co3JALpz+Xuw5wb2L459fcMKneXYGkGnzWdB9KL+NW1p/i/zeEsNDiUw2XtgKR1tk0G5pJoA7lXf5yPg4YRT1zAnQulIBEVkbFrCm/LIV0bUNnEHllKHEzYdEnqySFoRZb5gbw8LYX+NmWc26BKChWlDHJoV0ccnqvGcOtkvZAdGWD0y0LTU+VkMlOAtypJ6ymne3rN8ZYMCb8XiRjAdrN1pn0t8NAvIccwJzPEQFoZpDik6YvMz7zrvTXtHsOG5HW0VqEI0MSMr/+MWBgflAXpHTdPfagyAW40TsRD8RZUtsVmkmT1FiVGC3hImzbFRYHlAcwL/wjxmucJJbSjoErlZe9Lgb3bXfzXPCHFeW/cQ1d2g6nJjmyXMbf5RB1nietj+ZEYrY+QGlrYH8E8vOmISPW+eA1OPlt0P8yftgknGa2rzS4cym1RKkFr2EZpRYdyrIlBsbzxgw76OT8SksFpPsvgwTyzJxgN6xkP9zYpWtYRhwPGwZTYXgJ4IMINvDzTiA/UbT2yCH9zLpY12Pvi+EIoJMWXYPkheKgAAYb1N3ZeXvZemUUABk7zh8sQKhoOCxTOD1lcXPITWFJGz1HRjU2uHdk1gBBQHrDucKvxGX9A+VTEE+RfGJSWiGBBZRB48QX8QqftxBb5aAgloBtNy0Vi/WPIf7Tio1SxlpNyKGdq39bbyC7PdLTTQXgkgNURtdmeSOlG2G6NdP9j5vxOILuUEYqckbbK8nx1wE
  template:
    metadata:
      name: tubearchivist
      namespace: server
    type: Opaque
