apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: minecraft
          image: itzg/minecraft-server:2026.7.2
          ports:
            - name: ingress
              containerPort: 25565
          env:
            - name: TZ
              value: America/New_York
            - name: EULA
              value: "TRUE"
            - name: MEMORY
              value: 2500M
            - name: VERSION
              value: 1.16.4
            - name: TYPE
              value: FABRIC
            - name: MODRINTH_PROJECTS
              value: fabric-api,phosphor,lithium
          volumeMounts:
            - name: minecraft
              mountPath: /data
            - name: config
              mountPath: /data/ops.json
              subPath: ops.json
            - name: config
              mountPath: /data/whitelist.json
              subPath: whitelist.json
      volumes:
        - name: minecraft
          persistentVolumeClaim:
            claimName: minecraft
        - name: config
          configMap:
            name: minecraft
      resources:
        limits:
          cpu: 1
          memory: 3Gi
        requests:
          cpu: 500m
          memory: 3Gi
