---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-api
  namespace: monitoring
spec:
  encryptedData:
    TRUENAS_API_KEY: AgApKveZjivrhrYHGJYKDubL3zMDxqN2MwbVp5CfhnfZifxMpiOqIpk/xdGc6xVhYumvCLupEXWi6U7E068argcC3x68c38tJnmE5HogClKckIWy9mSVnMa1/8G87wCJxqOtZhzn37IE4KTV0blt2ONjf6Pkyj2g6G1IA9jLKmQGrHVwNH/vdo5yn7kKZrVRjQ+9vyNqOarmGw/RPg6pm/Pg02XGbUJBvZUEAFEq5ZDCPiqYCjkVQGWwhst1vPqtctL/KAOdQjKjXuLRcDsJuyP2dvRGPmz3iezPgl3tV+UMZ9UiJYTvIFOBb1utX82DJip1H51wyhA26F2P6INdDU5edEuo42TNVacE8QC2m8JsQ0h+BGjRLHzX1hiZO55T3EFlBua+qThQXpuQqnrTX4IL06qZUg/tDSJ0sdykcq63fPSSOo1L9Wt9I+CwUgePmHRx+jejI5194HBNl7Aq5BcBPFB1tWl7o5f6KFyKF3v0tqQnoADKHjWcRMNuEVKxlpGb3+373USQXAo37OaQXrDLr33ro1VOXpF+IYvbLUv3IoTYG6g8mcN95bfB4cCrlKRR7UbCLgpGSRjGU71dRfcLo+DCFGQoxkVp7FOW67Yc9+SGwwUXJFi9HF8x8Jx1A2K7SrQc9Vpj3aBb7sBTU11B95+AyyzA13Ph3mR5OOxXVundc0CsjAkjd2WkgZYD1KFltKk7Eu9kaOnPabvikxvGZnpxX0UMm7e+Ft8ACqkFt3WdhtOK1Al36WD8ybPllZ96/Uz6ysgD5RvNPIcCvt0xLH4=
  template:
    metadata:
      name: truenas-api
      namespace: monitoring
    type: Opaque
