---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-api
  namespace: monitoring
spec:
  encryptedData:
    TRUENAS_API_KEY: AgC10fLdpW0mJAx9M+HyKm9LbSww+Mwq1ub5JhJesGno25L0jXQ8YxdJzbrKTKAHm/l+LOgARwKCUDhl/alFb7QRxifRFTjKLRa8XA4tCWiaIG+U3pKTCeLtCCVyuqBmI7g84oz72Sf84yMc/yfolf5lxVCx8OC6NGV7ksvpF6vKos631XqsWq0oOT1ZlWU0J/dAYe7blP7ynCybDYffkle7+VWYqTqgvA44EUsYhdhRabo5rFhXXXh47MVgFBq0wdfoHU33TYssW484y0R45az6SKd7Pa3Fqhp8JnVk3hiyfRISapxKsk7AlfoO8yo7vS0yoCe32QuzttY/bDJ4R2iWsQq9J8mIj5+kxbNTg0LbhFjPnjUXAUUZnnmxUHQuLU47P+LH9zJTlyYE1prh8zdkQ/oeDRH+Vlyit954xIs8J3EQYYhlxYebSUGnCvQTxJIA8cDYagHBsO3y0S4oxJttvcgw63vCS74uuldI3l+HwguvVyAFkw/I77rlvt2MkqeN70JQd1OuQFkulzIAqvXMI7SfNfbPOSBUuOT4SjKEIZfHwVMnT45D9AXygzYJ74r2PBaTFUsjN5WSOT4Htp2OMDgX+Lj3WWLbKEhnk7zmOuhOZq+sTapublPhz5TQhObkfR4ygJE1txkaMZxBxLCGJtD9w//7tgJt73UPIEHKeD7Bndt6sp4Y84GP2y/tnP9+5Dwq6sLdYvx3BsBT8AdEs6L3UoNRLNNjkCkDHJqDUL1OzjBqIRUCpHQnNLugyB3pDFzH8QXfJqcAPoWe1rE5NQ0=
  template:
    metadata:
      name: truenas-api
      namespace: monitoring
    type: Opaque
