---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-api
  namespace: monitoring
spec:
  encryptedData:
    TRUENAS_API_KEY: AgDBuf0earGlKDEDtlJk+dd1xE9x7wcSKfy6jWIgzBFgJc2Hp3FP3FyH0M/pLx3qqogpnJRIuE0EDOMCZV14xzcFs2ntUBCDSybtDSTUC/L5ASjKJ5ulCjjnWngy4sWyFU7uVAQSbOE5fj3e+Vg+BjwjB5xzx23Zh6F8gnDhZhTjO5fL5Nxlh8B6zMALZNgUi8y4OmAZy3CdAUxld/4ncBdvS89OgmlKvhNXWveGfTeATVmSipZDMyLmP7gy4wv1N3KaKTT7mptB49BZxMSagNkmHGsZivNmciDnFjI+iBOfrCdqzqW47QamMfMIq5PRrlqimHZXTMkbS73KXIX8qK7Hk+4lVPVg4UX+KQNt11ScQzULFbHEs8y4TUYEXd6PhE9AuPQwPXtIAVZ7SWdbHJmhoAqCwrPDmGJ5L3PC6YArdn5JtCQ0ajk4CovFJog0N8gAREO7JlL9vNIgJzwHkOK3Ue9GnlIsfW85C/YbzjScyvcyWU7VIpJLGpw2kggi3ryMPPwftQufMKiVTJNonjMifJ2Ru5Edz/4al6USWizMv11fSJiRD5B8Jb+yHxE5swVwN9aDwXB1net42xWGDZ+THINKShcetTlxwkTFJSVqQtRzYGK3oUKfd+I7F6VYAyzEBZDyTPsHIaorFPY9LZuJlT6hucerH9atIPrSwP4NvPTaC3d9a9m2Z9wzLUeY6dkYI2vpmvldQpCI9q9IBdyDHbdq/bQfv+3++wIgshodMzb3riqfuJJ40fNJXwtkdf4x2RS7Mq6cbJW3qL9nD1r6uGk=
  template:
    metadata:
      name: truenas-api
      namespace: monitoring
    type: Opaque
