---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent
  namespace: server
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgAh/nHkB/4kCTaZO7i/Z+74wJYsi4RuuG/rrDKUyjPQR9v0Q4k47XTMPEhnIwBNfOiSi+U5UMjY0tqWPk+dKIh5W5KEb+EzDcqU70O0zahMO4FmrjkoPTWuOA4EjbS2ZgEzNqwUfFk/L/6Uvrmc9q5zylTE4kT2WLgelFfBqxphpp5P+GjpjG94sIFWYa2l/C4BYRAUdclgyYwz+T9ZsKzwbNkAVLrtCb577GHbbvtYlhsIAFOFAnCUMUVWlvJxXxosPbc4XE7GRxli0lw1TMXBzZTnqBaFNsDRFfMZtVdEr+DioIg4TI6mvDXVF1MPWHd4bJ1t5SfWyd/AJ4Nwx7E1GjmMz+UUyUndCnH4ofzkMM+H15bZa6RAAm9FCOB2ZvA2DZzZ40CzO2PIgwrW4sXnW3uZ36tLU8t+LQ62j1gjGqh9GLE82G3udCu/9XjtvqDCVmJR0Cpm6GrjoYUeebxaW371hPippz3K+ATBHoMwPBTv97WhNDYgIEXgeluhoDg8yEKQdkPG5FxfkH496t1XZxd3P4fL4ZqZxjb1yZUi2OopjpLO/U3bmoKbg171wiy19K099n+L+Zvc2DqjS52su9ZQDENBFz2xF5WVJopw9DMPmSfZeVsKrFuwghY4ANkgsaTwsagP4qshTTveE6h7vxlOLI3pAfbZqULL7a3RbCPO+yQaScyLUGGVVLJwQp1dm7jaNZTLp9ACaaFQ/3LS
    OPENVPN_USERNAME: AgDM8PZiO1TTMKe5Hh6uNdUBgFsh4c5cvXfNuWt+zad2WRXArg75UTFc3YaDlzB8XUM24dd/55DDn3vIWugYZEikYRZsj5fWu+inrIOhmj17chD2+QrQpg+b86lXFnTbeVwH08YVHFYexx4fWmiUCkAngTOAKb+5xg0f9dRkIb8KK11ooDX+JjfBHNqoEJ32emZltfPvE1q8W/ZWuyCXJVEMczZKP4J3gxKQspBHBEx4L+RdNJKt2i2n5p9OmbivWqja06phipALNO+LrALNy1OTkcJ29CrrVboj/Yed7xBKCQ8WQ3O/ge8OD8pWQfOS5SNXvv7E4jb8X+sC0pLbKv8kF/z9XMkYUKtLbAcqN5oeRngi5wQkd8r6F7Z4j8UYGzfvlfYk6pcPdrXXcqjyV5mwKfrEL5rs22HMluabOtDDinAaZ5JAj1fYkGUxXZ+K5AoJIaTS2zImOI5oobg1+39vymyDqvnqpvN40gFvHOu2LnhT5t6d5x9XUBjaT+ch5Ex0cWWajQPTsVeFMtSwLDDttKc2FhFLRKEhMjw9gTuYnZSiPnCoo7clPJiLXFyOP95e1D6OKzxTC+XtBgmZ8rP1FF2o/errF6pf9kggLnl0Vv0TwBb4RNWJdA7ijwnN6mVIp5pLAvupHbWsXtwYMPopR5E67TSiaM1Ad8Hh/8nCKN8AoP8Uuz7S0QTMQJ4YGar7qQpNsFfRscDO8vwAiJlc
  template:
    metadata:
      name: qbittorrent
      namespace: server
    type: Opaque
