apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webnut
  namespace: server
spec:
  encryptedData:
    UPS_PASSWORD: AgBh2niSswaubPXJ4pGyMH45gRlEjfvIkDF38wKsescjVWGEhBbdRzVQa8RqSQ6OB3Pke12sObtY88jCpRfT9BZ+Vvlg8Kxoe8X7SeqvcEeejJgC7PlJM8SwPbtQJR1dMDZtskwMbgryzFfUsYu5zlaxXGbIOexyTiPCR5NPEjcN6LB90Zx77g3h2qisMwRucS2XtCjH8BH0E3bJzdrb9/7QnzVhQlWPN5B+6Jb2H9XS4DdVU5R4dCl7gTW6aDoV0R/2Tv8j3OdsIpn3TXEZw+NJ5BSF6XqclSW3uzLqv+kz1gZBZ9q8z6D1UmKiyXrDkcHyWhQxuczLKcL9ViqOzIlrTActNsFdqaI2K8ZBMw1D/wzRaFQ4nWQV2wvmUyKuXk5omc6u0ocTEi1EJ3PQPmISOmP9vV53SBOXOLS3pSN+wzbwVgu1cXOeRNcSbE+qoX6XPJffzBRGFjH4x20VKcmAr2WAkyyddqMQG1pFhGeX/3RNwN0MW43pNoBHSSnOz1hIpMGeUPzKhyft96KjIlQkQMmIQ0xVsm81IQPp2n/OVdAXz/NMwgS4BpnkcIT0gJ5IWH5fdod3QL1eN+7Vejfi7AkmCIgmJTo5cT1dqVlFY1SqHBA87RNNwIBtZ3H3n6qD3MoXB9Qx5RRKw2OHCwCvKmXIfzFVelKZPGzB+Gf0RTLkrJDiQBiDH8ouoRt9wFKfi2TsgxM=
    UPS_USER: AgB/zmLXMFpzHiS4Ty4T7cw47vYLY/r4h4RonXd/fyd8Bp3RxCiBEoQTeZP75/lcwvwGdieLn253++KA6Hg8ogAXr2tzYq3OQbyAffNeiIw61KWcBKEqdJsq7yVLwR1/B/+HODv2ddcTbVWEAmmaWuyfUIRVmYDq4dlZGgqD1gmOx5jVwPNRIE6TXX+KMDZXX5ZM8NZ7Ky5G+Q92wukcJbDY9CmAgiSd4932RA/fcaaC66oDF5wFebl5AdJkaCIo7w2GmzBhpq+v1g4glTcqXAsCBykg6UI+aeb8ij7hUv7w4By9q9CJne4OkEPFQatHrZm5Vm72GSfhWOL05LSh81vAVsjc9bvcrwZb0nWsgeRnaJMSrXv5L5qE9suATHAOtK6lQUm4JwhrrotwV/A2ibaUj98+bTeZp8CeyWUNmnSfCazStXPm6GrnJxM8YjqMh3z0yKN7yUgjFJjGMrzul5Dcj1Z0vaFM1Q1o3/lm0qDmqFamfjr8WPLi1rY/eYY20I+r+qCuUF+6T4TCKZMK5ElVeKNaiBmwpZ7BC6PWY8Tli42iBprDA/eBGWmeULGE7J8oIODUtHuFflmWybpImM5WwOYa6YkirOMKN1f3sbYy5goPpA+kFFLGziSc9PYZO6mo5XSZHsqnGgjrSsj7BVOc8+GliVs3mvAbweNidZuvtrpGYXd9qmNIcFz1wrKj5CYQrlHEQDIb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: webnut
      namespace: server
    type: Opaque

