apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webnut
  namespace: server
spec:
  encryptedData:
    UPS_PASSWORD: AgBQ3hwogDqPe8iz2KHGApy+RArf4WmpLSv2S+V96i4iQgEogN+sS2ePxrEtCI/p5aKFP6CiXhahoIxPVJEZ9RDt3dsDyqLcfio0PKR9fEyZ8yLDBVTaDez4Z/6XGy9t3kR+u9EyLudJMKJpXeoIICXg4G7Lg0JHqK+0RcnjF+h9mdUeSC4P4kwWy6dKoe5WRXNtnc+NEWRMmf06gOxRYgBar8ktQTR8kI6K13D8BGBf3mAGk3Sdyin2P+NeCAHY5a4qn1BMWj9pOAfHrdSrZ+LNsz2P85/j2rIjECAsra1mD57lkce6xq/PkxNHJEGZz3yx2b4VFNDcbJcVEvFA9qNgWl7vu33W5tAbcZozH2FMk0rVDefcair1Eycg0+QnEgSTiHx4F0mnvGWMVFnLk4LRzr7CJwmzh0BJLtwWh0vrhhPB5bVSbV7SxHri3IkJhxLSlLw/vaZBuG94GoFCyB3zdIGEefVZY79jNbNdanlp7nSny4naLjdhcm6xXS0yo+lyzMLttxwt2+SBCJLSNjVw/yOkXr9B33dqeXQW6wSY4kuxfWyvAcJ9wiGganoN+v1Y6LBuZDH8SKXDDaezzzkMzVMWLwRDxYH0F7OTjhUagFEdl3YC8BbTQNVXG4gd2cLA5R3VaaDdM0D9GY532GJ5iTB5VJ6GdxSoJQHXa2ybH2bZXUrhi0VITPmXMVsN5SOoD0Hzcj0=
    UPS_USER: AgCOol8Q29XmEECEHhQwX3lNSBM1nRUtnYBP8mCM7wW+5tnik2dyvTMVzekhdBWIGALUQXyJU3RldkrJDdykqIU+NBOE/S9H8le/rSheCr/pBjhXlJk7o/DEjRyBzl959p+lWPfxWWyXfE+3HzZQbW3y4Mb4fOnI1a4Fxm0xbXHrk6WrlWPQYAYREZm4l28Qb/OoKPwJqep3826dSi6Fl/r7+cnz2BtCm0YJCzisz7fjG5GLhriHHK5FOXAUv+NqnIeLdV7uQyuA4IPWUdCPAyKgISSZaZ8jsVRei7+N+n2ASknhiFZfr1Ud4TIDn5YEdvgIMSO/M8wxu8AxUGppfZCwh9WVxB5q1s4npogIboM5d0W4fgkeClU8cLOz+kBOYYLwmGdUHhp3mWtkmNGVe1NHe9k0MAU2truCbR//Vc8A0cMqqAq8LG87GSjwwKNYtCK2REHjQwsFqsYAT2RkZj76u2ebwdOSBPkTa1PB4ShbvEvKKByiQpAeSGi8cOexK9cJXuKIyHorAU9lrVXZGVpL9kmmqq8V/4b+rOTkiDxiLlyVT/Mm18toyiRrbG/N4XymEaL+oG9S+eujitJ1aOuW05YyJ/GNOUcDSMrpjCPAtKDpJzkwqEJSDGmvuaz1fdvSaC8TQTY3FOVYTYFRD0bmPen6S6JLKhlsHq216SqEyxBNpB2pRBulbPXF6ySPZ5GbvlAHUCqT
  template:
    metadata:
      creationTimestamp: null
      name: webnut
      namespace: server
    type: Opaque

