{{- if .Values.endpoint.ip }}
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .Values.app }}
  labels:
    kubernetes.io/service-name: {{ .Values.app }}
addressType: IPv4
endpoints:
  - addresses:
      - {{ .Values.endpoint.ip }}
ports:
  - name: ingress
    port: {{ .Values.endpoint.port }}
    protocol: TCP
{{- end }}
