{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.app }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
{{- range .Values.ingress.routes }}
{{- $service := default dict .service }}
    - kind: Rule
      match: {{ .match }}
      services:
        - kind: {{ default "Service" $service.kind }}
          name: {{ default $.Values.app $service.name }}
{{- if ne $service.kind "TraefikService" }}
          scheme: {{ default "http" $service.scheme }}
          port: {{ default 80 $service.port }}
{{- end }}
{{- if or (not .disableForwardAuth) .middlewares }}
      middlewares:
{{- if not .disableForwardAuth }}
        - name: forward-auth
          namespace: traefik
{{- end }}
{{- range .middlewares }}
        - name: {{ .name }}
          namespace: {{ default "server" .namespace }}
{{- end }}
{{- end }}
{{- if .priority }}
      priority: {{ .priority }}
{{- end }}
{{- end }}
{{- end }}
