{{- if .Values.loadBalancer.ip }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-lb
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.loadBalancer.ip }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.loadBalancer.targetPort }}
      port: {{ .Values.loadBalancer.port }}
      targetPort: {{ .Values.loadBalancer.targetPort }}
      protocol: {{ .Values.loadBalancer.protocol }}
  selector:
    app: {{ .Values.app }}
{{- end }}
