namespace: argo
helmGlobals:
  chartHome: ../../../helm/charts
helmCharts:
  - name: ingress
    valuesInline:
      app: argo
      service:
        enabled: false
      ingress:
        routes:
          - match: Host("argo.mchill.io")
            service:
              name: argo-argo-workflows-server
              port: 2746
