namespace: server
resources:
  - deployment.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: audiobookshelf
      ingress:
        routes:
          - match: Host("books.mchill.io")
            disableForwardAuth: true
  - name: persistence
    valuesInline:
      app: audiobookshelf
      size: 512Mi
