namespace: server
resources:
  - endpoint.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: proxmox
      service:
        disableSelector: true
      ingress:
        routes:
          - match: Host("proxmox.mchill.io")
            service:
              scheme: https
