apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: proxmox
      endpoint:
        ip: 192.168.1.30
        port: 8006
      ingress:
        routes:
          - match: Host("proxmox.mchill.io")
            service:
              scheme: https
