namespace: server
resources:
  - endpoint.yaml
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: ingress
    valuesInline:
      app: proxmox
      addSelector: false
      routes:
        - match: Host("proxmox.mchill.io")
          scheme: https
