apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matthewchill7@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsNames:
            - mchill.io
            - "*.mchill.io"
            - "*.remote.mchill.io"
        dns01:
          cloudflare:
            email: matthewchill7@gmail.com
            apiTokenSecretRef:
              name: cert-manager-webhook-tokens
              key: cloudflare-token
