resources:
  - cluster-issuer.yaml
  - namespace.yaml
  - sealed-secret.yaml
helmCharts:
  - name: cert-manager
    includeCRDs: true
    version: v1.8.1
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cert-manager
    valuesInline:
      installCRDs: true
