apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-webhook-tokens
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCWi9BUhSN205FsH6JCsA/NUWkBBw1ir+lCf54mPFvY3C1lhVQdraVxZWg9389KbTilRQAflLpn500SWE7Xog5ko/6pgTmRTjypcyzBh+veGdsZ2hTGTdiultNvhSab7nZ3pxVAbtue0rO8Xh4AWrIFp1SmOV+dChdUYmN91JlAJH7FO5tTz61RhCd5jJjQOuNEU5dJ6NknurAyh5T+eCvJeJhjmHhbl4vy8PRasVvJ3vrm96aEaj1fFL/zOLpR/oJIBrR5q1YV/cbxThhpk+IY3FHN7dZ7uKhJlr4kljLRpZYrRUj8oioxqMjC8Lb+I2J96y3chbsDUFTLTItIEI3aGokuMfwZ8TQj+R4eomwIoj0vZ6gxJ1D4DDV7nvu4CUaux5p7UJkFh32AGToUcrx9AG6KoPoB+KW3M6WwumYMllB53Aka5MFPUn3oeumZytTGzYzX8CdcKO0qFZsnqwt5u0858PIy4+Gmu16bD+TbaAO6zJ6HwNlkX8v3pQ2aVQY2Qzy4j/yS4WwLYmOZJzXwWyglk2pOJXAQemAa8/Useev9uV71zOBSajsyE89OZPiJYd0jJJSb62UxYSHQ/I6HSonZoJrl3GZ+TgI9NIlLn1zXoBM19xckhdMKCDleTDsb1v/wg9/y5jbx01je4Aip6f0rUl1EIZrFDIeK537QfZmIwqgnQhLsfO/wdCCfYrXHzUf+1B7voSasxiuHqeFFFqUaBJHAxNY+kJrhkHwhKJYAeG49sfWK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cert-manager-webhook-tokens
      namespace: cert-manager
    type: Opaque

