apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-webhook-tokens
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAgyMcOMflv6FdKjwL98D1zP3ppfnYOHn1/4HgQmc8sVPTToKJoXslqxatcs6gY+IYTu28OyZJkzGlw1DtVDs/wogexuTmRJORBcyfFlXXjGizjrKxcvmnx5hlwfu65xnMhH1Lou77nhBAu7pV7q1PbBXDuL8UwMAtsARtcTPARaS3v/kUxo8Oh+fq7Gk7dk+UEztNJCRmw0dUf3eGRxAqhSnMCa1LKAht5g8uI7kjQ7aR7E+snpsiZhohfQ5L7nN7Mrm2Pa4I/utAuYUDn5BRxkN5euX0JerYUoMNAiTsPsyLMoQ2iLFtCOxwvKhsBk/xq8AVX9oTEk9YvX9a5iTJ38ECRAJnDz/1TnyNg3sT11IYmXCOubl2/Hpwg7pOl5HSd/eoYW8lkii4Yp3CoD33h5x7ruglZ+09yo3Mla/EeKlU8AZ/oL/UuRyRmDG1bGiSWAUQBq9m0CZ2SpaR+mBVqbkToSGeW51IummPVisuf0xfhHjRI94kDH0tSIskTbCI70BfoC5iNQzr23/ZQ4PH+IUtaGQTMBnmBLJP1ISrh6WYO23sjyb6w0B9y+9MnPgbsCNGyo5x/7r0TTCIqP9uC34sEJMxaydscYq1zaTaMqVMJtrdLVdGWOp/olPw/7SmDe11kN+Y5qBewdEVhsEJwKtRpp3HumrNQuqldEahsxctziInXRwBh71hBsLMhnXhrVoxme/YvOct9DKOz2IvQQb8RyMXTUOsJb+CihndCXoNQ3KwFKIC8
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cert-manager-webhook-tokens
      namespace: cert-manager
    type: Opaque

