apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-webhook-tokens
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgASq1oLej/AUdNFrz4eEEhZELKPQG8wx/W+9473Mc5dTL65A7q/yNZelth1FdY+nL51d+UI46iD6HlZwtB+sn7a51QyTyUhEObqPYleKXhopNzyL0jT8nrZvUn4VjgWWgkRngyyvf7GyuDZaG4r0DRIKmw6ikeS1I4IakCMBglZbx7RuYI1ffTSHSo41kO8vd+5+hDiKm4wpWmWyaOt98v1I2B7AlI14b4/Gehg2tli8YI0qt1kNcKoeDrc7QVMJKT7GcvtBGhJxBiuW9DGmlw/u4CUd6eDsJhcLQLg6zMXk4ZZxWa6pN/XEWnnccGviJeFfm4GONLJyuCNUffkIpf7C/E+hTlumexNQpUreRS6q3p1bvInMnT+Rc6qFFlZTuCnt74THUxfP2hfF9m5tYfRGXZv+74vfJ7D4udsJHJPbIfDK565CBzhjuGqIciBUUTlQWaDhEkCmakV6qLsMHnW3tPb0Sbauxz8SQTjSAHs/RhMEUWf82LcAPvOZOQ1lX9niQFNGOwyLPfg0iMitRW2YG3G+n5cLo/M5KMDcM3o3YBle+rPH+giYPGjGQ6cdxahE43qTDakVODsSxmu+r4VY2VRZm7p0VbYIAIpgTs0et2W7Noy3HqOJj7vuLUtOLXYKpxsF1JVAPrqFTMHfJ88M+z7VEP/AmqelMdOULWPKtgHceTzP/4IXILQcdFotz5GNhkr6dl9suJsCOq3VNShQV8DAGmqtkivqATR/OH0fz8PePhAhYKd
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager-webhook-tokens
      namespace: cert-manager
    type: Opaque

