---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-manager-webhook-tokens
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCiRKcOiGPnTy4zt7ijUE2FXASlMn9MUKgPdVXDMyjNj585wovLII2527v3CcoAWWWjqF85OpvG7/8X/UyuBj9wEMP+aOA3ZBENv2wAMVQPLRTWX33VF2iRxI9z9YY0Sre/ziwonbuTyDZgMrYBGEg+n2Q1MvKXIan3sLa4yu38z0+JlF7T2XAk2nuYBjyX3ziGhlHBusz0T9f3AG+24Z0dJ4P3gKI9VDSHzzH2OxL4vdS81Dx1D/l8C7/DawiHgU6AxSwU6RkEbs8rrzI5gxlUuVG5nkmldEuX3GixEmFDnsYF6+QWg4g5qtLfbpbXupNp3XyClFi17yYlPll7OzEB1G3wxQD6GoeUADwmM/ORhJ6XCGvVwgRDFeqD+lS/bbNnb/k57Fvb82o8JV89W6Tofm49/JOpdzgsYB2rUA357vSgvLWIsPcxs78Le+MsA/mjmHaIYGlL8DMPJeRemNo9kvVHp84T1kFfYvcaKXNnD+bf3NdVeLRZ9CeOYXwcpmtPMDvqySK/D7iMgdGWoN3+R8xmTZHuwuRU6mdLAKcTyJRVKJjOpQgJrLKxtyaT7umuYCybdZJH1eqLShPCJE3t3uQmBSd+yEf8bRc5lUhNDmC7IdNxpphE2rsyhMOMQymbh7C6eVzQPJ9TLOLMuESZvRmsouNipgw4YO6GBOFXoIVp3Y5F7rdFpVVJkI/hHX8yi6Wsds1VYljmHP+0SSG0n+H+nDxPKetzQ3SoGOCeayL8ei16nV2H
  template:
    metadata:
      name: cert-manager-webhook-tokens
      namespace: cert-manager
    type: Opaque
