---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-manager-webhook-tokens
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgARVG/qWocQeNB10EoX8VeWnz2hqn+X8P3/se4X6bIiD9qbTk0shpb8wSySRvXvFtUTcTiGkCBbkDhcGAp87stQOhD6ir82wpUqcR2GYXL+tc0jRl5x6HAMKyFbYiN3GFGEVjUGSMahcU8hsubPbPhqcUEUE7ujE1okESZs7H66iGTQ4YEebbeiQqlXhpLe8oNXr5Mo+r/4Aw+joxaNpiPsklbg5MnLy/8RYig0Ib9/2K70bNMGfQzstdv+H9cauoFyYSGoTVtnjro/QXRweiJQJli/vu+XZ+0c5TZ8eCjo1z4eXH3pta7vkzP9/65E7Rrirwd64UNp+jdnpnzwybMvM2kuXvR/RdhS7ryCe1Wji/kSEgcs+vcrylCDVWwRw/Li/RLplnIuBUFhs0CG4xSurRhTR83YZ5ML+PsDZAIjO6ZiudmvjwC6IJ2zWD8NGt4++zXloC2OqJAU1F1QpUEJ1FO1vZlMrQQjZAQ7T0lzq1tlEW1MfeG6Vmjhc/5x6OXkeFcscqhLtIXycYnmn8dcZ2WjmjqJg3MjCNusuoN/j8XCPNNQfc7YZO29zksh5+sHUX32gxca9GGB2/ejV+4IUFYwmrRkfDkKLAj+YGo/DnINCJwC1SAKiXDMKJEu4Oin0UZxiAyorWtaOfPum+XOtG9AgConrvQVxiMqLehLXZIOjwNbD9O+OxbnPP2K9Nvt43qUmpPdP1w59KVOO3QJbOsFU1VoxmF/WkERmYs1NI+Pr4TNQ33P
  template:
    metadata:
      name: cert-manager-webhook-tokens
      namespace: cert-manager
    type: Opaque
