apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-webhook-tokens
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgDE7NZQIe9QAKgkBFUPbpHh4vq9DpJjbtsu9XRFUWDVSzvc79ZzXt76if2BJ38+Zkq1J4wV0JDiIGZuZhvsDEg8xOWimQyYca7f5JkSGLo/B/EsjqLxCojYK0ckD2YyNEy6E4tFk4Nubuwhz7WoftuKALAqPiBfLHwwpDQLXyOMkkb0J1n3owj9qaKAkJ9iX9J0b2069f19Xj8xibbzngN0JEuRV1EmTyPYJNfhpMemaex6Gtj+74oCg4RGNuMisoTKsFNqp3zo+0KQpOMIDpZnuYFEL/ijhsCzS6KsqP9BGq5UimiHioOdeh87iAOGGEfxBo+vexCZJ2lf9QNfAU9kvW2DFVBeZL4j6O87YFKnOy9BaLNtlllX5WL48CozqjMxODVrE4GyQTajAO02ZdllzEqDD8qyjn3G62iPTswbryu8S80p6F3Q58sblUX165FwA8/c9K+AJHh0zzYUPzWgLNB+N9OtkZDbl3mL0F28fMVy6Iqc7PWQ1T+gCqqNuIYQQwTauvCJ2Sh+GE53hE6EUA8M5bVND0inU183qn+YKXX7DTjZyBmSiizr/J88V/C4e2bhQbaP/KnGGyajuC64Tj0N5ZXU/bkX3v6pzH/oXpf2y8X336nu6Csc3p1/j3zO7fGrBjpAkcANyZi40BWYsOtAuL1SptHWBbSzUqlMCiW1152ZOS5shLLvXOjIAWzTwqS5lSCFwPeuRhB3RTDS+wvvjomUV1WpiIhjjIIEEqC9WKOyyDyf
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cert-manager-webhook-tokens
      namespace: cert-manager
    type: Opaque

