collections:
  Matthew:
    radarr_taglist: trakt
    smart_label:
      all:
        label: <<smart_label>>
  Mom:
    radarr_taglist: shil771
    smart_label:
      all:
        label: <<smart_label>>
  Kamaria:
    radarr_taglist: kamaria.
    smart_label:
      all:
        label: <<smart_label>>
