apiVersion: batch/v1
kind: CronJob
metadata:
  name: plex-meta-manager-permissions
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          securityContext:
            fsGroup: 1000
          restartPolicy: OnFailure
          initContainers:
            - name: render-config
              image: bash:5.2.21
              args:
                - -c
                - |
                  apk add --no-cache curl gettext
                  envsubst < /config_src/config.yaml > /config/config.yml
                  curl -X PUT "http://plex.server.svc.cluster.local.:80/library/sections/1/all?type=18&label%5B0%5D.tag.tag=Matthew&X-Plex-Token=$PLEX_TOKEN"
                  curl -X PUT "http://plex.server.svc.cluster.local.:80/library/sections/2/all?type=18&label%5B0%5D.tag.tag=Matthew&X-Plex-Token=$PLEX_TOKEN"
              envFrom:
                - secretRef:
                    name: plex-meta-manager
              volumeMounts:
                - name: plex-meta-manager
                  mountPath: /config
                  subPath: permissions
                - name: config
                  mountPath: /config_src/config.yaml
                  subPath: config.yaml
          containers:
            - name: plex-meta-manager
              image: meisnate12/plex-meta-manager:v1.20.0
              args:
                - --run
                - --read-only-config
              env:
                - name: TZ
                  value: America/New_York
              volumeMounts:
                - name: plex-meta-manager
                  mountPath: /config
                  subPath: permissions
                - name: config
                  mountPath: /config/movies.yml
                  subPath: movies.yml
                - name: config
                  mountPath: /config/extras.yml
                  subPath: extras.yml
                - name: config
                  mountPath: /config/tv.yml
                  subPath: tv.yml
          volumes:
            - name: plex-meta-manager
              persistentVolumeClaim:
                claimName: plex-meta-manager
            - name: config
              configMap:
                name: plex-meta-manager-permissions
